/* Grupo Saúde V4 — camada de dados local substituível por um adapter de API. */
const App = (() => {
  'use strict';
  const KEY = 'grupo_saude_v4_demo_2';
  // Fonte atual dos indicadores operacionais; o adapter futuro poderá fornecer "clicloud-api".
  const MANUAL_INDICATOR_SOURCE = 'manual';
  const $ = id => document.getElementById(id);
  const now = () => new Date().toISOString();
  const today = () => now().slice(0, 10);
  const esc = value => String(value ?? '').replace(/[&<>'"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  const uid = prefix => `${prefix}_${Date.now()}_${Math.random().toString(36).slice(2, 7)}`;
  const fmt = iso => new Intl.DateTimeFormat('pt-PT', {dateStyle:'short', timeStyle:'short'}).format(new Date(iso));
  const demoClinics = [
    {id:'c1', name:'Clínica Central', lat:38.7223, lng:-9.1393, radius:250, specialties:{Fisioterapia:['Dra. Ana Silva','Dr. Luís Costa'], Fisiatria:['Dr. Rui Matos'], Osteopatia:['Dra. Sara Reis']}},
    {id:'c2', name:'Clínica Norte', lat:41.1579, lng:-8.6291, radius:250, specialties:{Fisioterapia:['Dr. Tiago Luz'], Psicologia:['Dra. Inês Melo'], Nutrição:['Dra. Marta Dias']}},
    {id:'c3', name:'Clínica Sul', lat:38.5244, lng:-8.8882, radius:250, specialties:{Fisioterapia:['Dra. Ana Silva','Dr. Pedro Sá'], Fisiatria:['Dra. Eva Lima']}}
  ];
  // Sem utilizadores fictícios: os acessos são criados a partir dos colaboradores reais guardados no RH.
  const users = [];
  const requestStages = ['Novo pedido','Por contactar','Contactado','A aguardar vaga','Proposta de consulta','Marcado'];
  const indicatorDefs=[{id:'consultations',label:'Consultas a trabalhar/marcar'},{id:'waitClicloud',label:'Lista de Espera Clicloud'},{id:'suspended',label:'Suspensos'},{id:'revals',label:'Reavaliações'},{id:'confirmations',label:'Consultas por confirmar'},{id:'internalQueue',label:'Lista interna de pedidos'}];
  const candidateStages = ['Candidato','Contacto','Entrevista','Proposta','Documentação','Contratação/Admissão','Ativo'];
  const baseTasks = [
    {id:'open_team',name:'Registar consultas e vagas por profissional',phase:'open',required:true,clinics:['all'],role:'Administrativa',frequency:'Diária',deadline:'09:30',response:'profissionais',action:'agenda',active:true},
    {id:'open_counts',name:'Registar Lista de Espera Clicloud',phase:'open',required:true,clinics:['all'],role:'Administrativa',frequency:'Diária',deadline:'09:30',response:'número',action:'wait',active:true},
    {id:'open_suspended',name:'Registar suspensos',phase:'open',required:true,clinics:['all'],role:'Administrativa',frequency:'Diária',deadline:'09:30',response:'número',action:'suspended',active:true},
    {id:'planning',name:'Preencher vagas existentes (Planning)',phase:'live',required:true,clinics:['all'],role:'Administrativa',frequency:'Diária',deadline:'12:00',response:'ação',action:'planning',active:true},
    {id:'waitcalls',name:'Trabalhar Lista de Espera Clicloud',phase:'live',required:false,clinics:['all'],role:'Call center',frequency:'Diária',deadline:'17:00',response:'ação',action:'wait',active:true},
    {id:'suspendedcalls',name:'Trabalhar utentes suspensos',phase:'live',required:false,clinics:['all'],role:'Administrativa',frequency:'Diária',deadline:'17:00',response:'ação',action:'suspended',active:true},
    {id:'confirm',name:'Confirmar consultas do dia seguinte',phase:'live',required:true,clinics:['all'],role:'Administrativa',frequency:'Diária',deadline:'16:00',response:'ação',action:'confirm',active:true},
    {id:'revalcalls',name:'Contactar utentes para reavaliação',phase:'live',required:true,clinics:['all'],role:'Administrativa',frequency:'Diária',deadline:'17:00',response:'ação',action:'reval',active:true},
    {id:'close_consults',name:'Registar resultado das consultas por médico',phase:'close',required:true,clinics:['all'],role:'Administrativa',frequency:'Diária',deadline:'19:00',response:'profissionais',action:'agenda',active:true},
    {id:'close_counts',name:'Confirmar Lista de Espera Clicloud final',phase:'close',required:true,clinics:['all'],role:'Administrativa',frequency:'Diária',deadline:'19:00',response:'número',action:'wait',active:true},
    {id:'close_suspended',name:'Confirmar suspensos finais',phase:'close',required:true,clinics:['all'],role:'Administrativa',frequency:'Diária',deadline:'19:00',response:'número',action:'suspended',active:true}
  ];

  function seed() {
    const t = today();
    const yesterday = new Date(Date.now()-86400000).toISOString().slice(0,10);
    return {
      version:3, currentUser:'u1', opClinic:'c1', opDate:t, opPhase:'open', tasks:baseTasks,
      days:{[`${t}_c1`]:{date:t,clinic:'c1',closed:false,exception:null,taskStatus:{},open:{professionals:[{name:'Dra. Ana Silva',kind:'doctor',selected:true,consults:8,slots:0},{name:'Dr. Luís Costa',kind:'doctor',selected:true,consults:6,slots:0},{name:'Terapeuta Rita Neves',kind:'therapist',selected:true,consults:7,slots:2}],wait:5,suspended:2,revals:2,saved:false},close:{professionals:[{name:'Dra. Ana Silva',kind:'doctor',done:0,missed:0,rescheduled:0,cancelled:0,slots:0},{name:'Dr. Luís Costa',kind:'doctor',done:0,missed:0,rescheduled:0,cancelled:0,slots:0},{name:'Terapeuta Rita Neves',kind:'therapist',done:0,missed:0,rescheduled:0,cancelled:0,slots:2}],wait:0,suspended:0,revals:0,saved:false},appointments:[]}},
      requests:[
        {id:'r1',created:`${yesterday}T09:15:00Z`,clinic:'c1',specialty:'Fisioterapia',doctor:'Dra. Ana Silva',name:'Carla Sousa',phone:'910 000 101',notes:'Prefere manhã',stage:'A aguardar vaga',owner:'u1',history:[]},
        {id:'r2',created:`${t}T08:40:00Z`,clinic:'c1',specialty:'Fisiatria',doctor:'Dr. Rui Matos',name:'José Ramos',phone:'910 000 202',notes:'Reavaliação após 9.º tratamento',stage:'Por contactar',owner:'u1',history:[]},
        {id:'r3',created:`${t}T10:10:00Z`,clinic:'c2',specialty:'Psicologia',doctor:'Dra. Inês Melo',name:'Leonor Vaz',phone:'910 000 303',notes:'Primeira consulta',stage:'Novo pedido',owner:'u2',history:[]},
        {id:'r4',created:`${yesterday}T11:00:00Z`,clinic:'c1',specialty:'Osteopatia',doctor:'Dra. Sara Reis',name:'Nuno Alves',phone:'910 000 404',notes:'',stage:'Marcado',owner:'u1',completed:`${t}T11:20:00Z`,history:[]}
      ],
      conversations:[{id:'cv1',title:'Vaga urgente — Carla Sousa',members:['u1','u2','u3'],requestId:'r1',messages:[{id:'m1',from:'u2',at:`${t}T09:12:00Z`,text:'Existe possibilidade de transferência para a Clínica Norte?',readBy:['u2']},{id:'m2',from:'u3',at:`${t}T09:25:00Z`,text:'Vou confirmar com a equipa clínica.',readBy:['u3','u1']}]}],
      jobRoles:[{id:'jr1',name:'Fisioterapeuta',active:true},{id:'jr2',name:'Administrativa',active:true},{id:'jr3',name:'Psicólogo/a',active:true}],
      contractTypes:[{id:'ct1',name:'Contrato sem termo',active:true,items:[{id:'i1',name:'Contrato assinado',required:true},{id:'i2',name:'Documento de identificação',required:true},{id:'i3',name:'IBAN',required:true}]},{id:'ct2',name:'Prestação de serviços',active:true,items:[{id:'i4',name:'Contrato de prestação',required:true},{id:'i5',name:'Cédula profissional',required:true},{id:'i6',name:'Seguro profissional',required:true}]}],
      candidates:[{id:'p1',name:'Beatriz Freitas',email:'beatriz@example.pt',phone:'930 000 111',role:'jr1',clinic:'c1',contract:'ct2',stage:'Documentação',notes:'Entrada prevista este mês',nif:'245000111',niss:'11000000001',iban:'PT50000000000000000000000',address:'Rua da Saúde, 1',birthDate:'1994-05-12',active:true,documents:[{itemId:'i4',name:'Contrato de prestação',required:true,status:'Validado',sentBy:'u4',sentAt:now(),reviewedBy:'u4',reviewedAt:now()},{itemId:'i5',name:'Cédula profissional',required:true,status:'Pendente de validação',sentBy:'u4',sentAt:now()},{itemId:'i6',name:'Seguro profissional',required:true,status:'Em falta'}],history:[]}],
      timeEntries:[],timeOccurrences:[],internalQueue:[],
      audit:[]
    };
  }
  let state;
  function load(){ try { state=JSON.parse(localStorage.getItem(KEY)) || seed(); } catch { state=seed(); } migrate(); }
  function syncState(){try{state=JSON.parse(localStorage.getItem(KEY))||state}catch{}}
  function migrate(){
    state.audit ||= []; state.tasks ||= baseTasks; state.jobRoles ||= [{id:'jr1',name:'Fisioterapeuta',active:true},{id:'jr2',name:'Administrativa',active:true}]; state.timeEntries ||= []; state.timeOccurrences ||= []; state.internalQueue ||= [];
    const waitTask=state.tasks.find(t=>t.id==='waitcalls'); if(waitTask){waitTask.name='Atualizar contador Lista de Espera Clicloud';waitTask.action='waitClicloud'}
    const confirmTask=state.tasks.find(t=>t.id==='confirm');if(confirmTask)confirmTask.action='confirmations';
    Object.values(state.days||{}).forEach(d=>{[...(d.open?.professionals||[]),...(d.close?.professionals||[])].forEach(p=>{if(!p.kind)p.kind=/^(Dr\.|Dra\.)/.test(p.name)?'doctor':'therapist'});d.indicators ||= {};indicatorDefs.forEach(def=>{if(!d.indicators[def.id]){const legacy={waitClicloud:d.open?.wait,suspended:d.open?.suspended,revals:d.open?.revals}[def.id];d.indicators[def.id]={source:MANUAL_INDICATOR_SOURCE,opening:+legacy||0,current:+legacy||0,closing:null,history:[]}}})}); state.candidates.forEach(c=>{if(!state.jobRoles.some(r=>r.id===c.role)){const role=state.jobRoles.find(r=>r.name===c.role);if(role)c.role=role.id} if(!c.documents){const ct=state.contractTypes.find(x=>x.id===c.contract);c.documents=(ct?.items||[]).map(i=>{const old=c.checks?.[i.id]||{};return {itemId:i.id,name:i.name,required:i.required,status:old.validated?'Validado':old.delivered?'Pendente de validação':'Em falta',sentBy:old.delivered?old.by:null,sentAt:old.delivered?old.at:null,reviewedBy:old.validated?old.by:null,reviewedAt:old.validated?old.at:null}})}});
    persist(false);
  }
  function persist(render=true){ localStorage.setItem(KEY,JSON.stringify(state)); if(render) renderAll(); }
  function user(id=state.currentUser){ return users.find(x=>x.id===id) || users[0]; }
  function clinic(id){ return clinics.find(x=>x.id===id); }
  function audit(module, action, detail='') { state.audit.unshift({id:uid('log'),at:now(),by:state.currentUser,module,action,detail}); }
  function toast(message){ const el=$('toast'); el.textContent=message; el.classList.add('show'); setTimeout(()=>el.classList.remove('show'),2200); }
  function options(items,value,label=x=>x){ return items.map(x=>`<option value="${esc(value(x))}">${esc(label(x))}</option>`).join(''); }
  function modal(title, body){ $('modalTitle').textContent=title; $('modalBody').innerHTML=`<div class="modal-body">${body}</div>`; $('modal').showModal(); }
  function closeModal(){ $('modal').close(); }
  function liveClinics(){const s=state;const master=(s.clinics||[]).filter(c=>c.active!==false&&c.operational!==false&&c.id!=='administracao');return master.length?master:demoClinics}
  function actor(){return state.employees?.[state.currentUser]||(state.users||[]).find(x=>String(x.id)===String(state.currentUser))||{id:'u1',name:'CEO',role:'CEO'}}
  function opClinics(){const all=liveClinics(),u=actor(),r=String(u.role||u.kind||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toUpperCase();if(r==='CEO'||r==='ADMINISTRACAO')return all;if(r==='ADMINISTRATIVA'){const ids=(Array.isArray(u.clinics)&&u.clinics.length?u.clinics:(u.clinic?[u.clinic]:[])).map(String);return all.filter(x=>ids.includes(String(x.id)))}return []}
  function day(){ const key=`${state.opDate}_${state.opClinic}`; if(!state.days[key]){const indicators={};indicatorDefs.forEach(x=>indicators[x.id]={source:MANUAL_INDICATOR_SOURCE,opening:null,current:0,closing:null,history:[]});state.days[key]={date:state.opDate,clinic:state.opClinic,closed:false,exception:null,taskStatus:{},open:{professionals:[],saved:false},close:{professionals:[],saved:false},indicators,appointments:[]}} return state.days[key]; }
  function recordIndicator(d,type,value,phase,source=MANUAL_INDICATOR_SOURCE) { const entry=d.indicators[type]||(d.indicators[type]={source,opening:null,current:0,closing:null,history:[]}); const previous=entry.current; if(phase==='abertura')entry.opening=value;if(phase==='fecho')entry.closing=value;entry.current=value;entry.source=source;entry.history.push({clinic:d.clinic,date:d.date,at:now(),by:state.currentUser,value,previous,phase,source}); audit('Indicadores',`${indicatorDefs.find(x=>x.id===type)?.label||type}: ${previous} → ${value}`,`${d.date}/${d.clinic}; ${phase}; ${source}`); return previous; }
  function indicatorFields(d,prefix,phase){return indicatorDefs.map(x=>{const v=phase==='abertura'?(d.indicators[x.id].opening??d.indicators[x.id].current):phase==='fecho'?(d.indicators[x.id].closing??d.indicators[x.id].current):d.indicators[x.id].current;return `<div><label>${esc(x.label)}</label><input id="${prefix}_${x.id}" type="number" min="0" value="${v}"><div class="meta">Objetivo operacional: 0 · valor absoluto</div></div>`}).join('')}
  function taskList(phase){ return state.tasks.filter(t=>t.active&&t.phase===phase&&(t.clinics.includes('all')||t.clinics.includes(state.opClinic))); }

  function renderAll(){ renderUsers(); renderDashboard(); renderOperation(); renderRequests(); renderChat(); renderHr(); renderTasks(); renderAudit(); updateUnread(); }
  function renderUsers(){ const el=$('currentUser'), old=state.currentUser; el.innerHTML=options(users,x=>x.id,x=>`${x.name} · ${x.role}`); el.value=old; }
  function renderDashboard(){
    const todays=Object.values(state.days).filter(d=>d.date===today()); const allTasks=todays.flatMap(d=>Object.values(d.taskStatus)); const done=allTasks.filter(x=>x.status==='done').length;
    const newToday=state.requests.filter(r=>r.created.slice(0,10)===today()).length, marked=state.requests.filter(r=>r.stage==='Marcado').length;
    $('dashboardContent').innerHTML=`<div class="cards"><div class="card"><div class="muted">Execução de tarefas</div><div class="metric green">${allTasks.length?Math.round(done/allTasks.length*100):0}%</div><div class="meta">${done} de ${allTasks.length} registos</div></div><div class="card"><div class="muted">Novos pedidos hoje</div><div class="metric">${newToday}</div><div class="meta">Em todas as clínicas</div></div><div class="card"><div class="muted">Pedidos marcados</div><div class="metric green">${marked}</div><div class="meta">Total da demonstração</div></div><div class="card"><div class="muted">Clínicas fechadas</div><div class="metric">${todays.filter(d=>d.closed).length} / ${clinics.length}</div><div class="meta">No dia de hoje</div></div></div><div class="card"><h3>Estado operacional por clínica</h3>${clinics.map(c=>{const d=state.days[`${today()}_${c.id}`], tasks=d?Object.values(d.taskStatus):[], complete=tasks.filter(x=>x.status==='done').length, pct=tasks.length?Math.round(complete/tasks.length*100):0;return `<div style="padding:9px 0"><div class="actions" style="justify-content:space-between"><b>${esc(c.name)}</b><span class="pill ${d?.closed?'green':'orange'}">${d?.closed?'Fechada':'Em operação'} · ${pct}%</span></div><div class="kpi-bar"><span style="width:${pct}%"></span></div></div>`}).join('')}</div>`;
  }

  function renderOperation(){
    const available=opClinics();if(!available.length){$('operationContent').innerHTML='<div class="notice">Sem clínica operacional atribuída a este colaborador.</div>';return}if(!available.some(x=>String(x.id)===String(state.opClinic)))state.opClinic=available[0].id;const d=day(), phases={open:'Abertura',live:'Durante o dia',close:'Fecho'};
    $('operationContent').innerHTML=`<div class="card"><div class="form-grid"><div><label>Clínica</label><select id="opClinic">${options(available,x=>x.id,x=>x.name)}</select></div><div><label>Data</label><input id="opDate" type="date" value="${state.opDate}"></div><div><label>Responsável</label><input value="${esc(user().name)}" disabled></div><div><label>Estado</label><div class="pill ${d.closed?'green':'orange'}">${d.closed?'Dia fechado':'Em operação'}</div></div></div></div><div class="tabs">${Object.entries(phases).map(([k,v])=>`<button class="${state.opPhase===k?'on':''}" onclick="App.setPhase('${k}')">${v}</button>`).join('')}</div><div id="phasePanel">${state.opPhase==='open'?openingPanel(d):state.opPhase==='live'?livePanel(d):closingPanel(d)}</div>`;
    $('opClinic').value=state.opClinic; $('opClinic').onchange=e=>{state.opClinic=e.target.value;persist()}; $('opDate').onchange=e=>{state.opDate=e.target.value;persist()};
  }
  function professionalRows(d, close=false, kind='doctor'){
    const all=close?d.close.professionals:d.open.professionals, rows=all.map((p,index)=>({p,index})).filter(x=>x.p.kind===kind);
    if(!rows.length) return '<p class="muted">Ainda não existem profissionais. Adicione os que têm consulta.</p>';
    return `<div class="table-wrap"><table><thead><tr><th>${kind==='doctor'?'Médico':'Técnico / terapeuta'}</th>${close?'<th>Realizadas</th><th>Faltas</th><th>Reagendadas</th><th>Canceladas</th>':'<th>Tem consulta</th><th>Consultas</th>'}${kind==='therapist'?'<th>Vagas amanhã</th>':''}<th></th></tr></thead><tbody>${rows.map(({p,index})=>`<tr><td><input value="${esc(p.name)}" onchange="App.updateProfessional(${index},'name',this.value,${close})"></td>${close?['done','missed','rescheduled','cancelled'].map(k=>`<td><input type="number" min="0" value="${p[k]||0}" onchange="App.updateProfessional(${index},'${k}',this.value,true)"></td>`).join(''):`<td><input type="checkbox" ${p.selected?'checked':''} onchange="App.updateProfessional(${index},'selected',this.checked,false)"></td><td><input type="number" min="0" value="${p.consults||0}" onchange="App.updateProfessional(${index},'consults',this.value,false)"></td>`}${kind==='therapist'?`<td><input type="number" min="0" value="${p.slots||0}" onchange="App.updateProfessional(${index},'slots',this.value,${close})"></td>`:''}<td><button class="danger" onclick="App.removeProfessional(${index},${close})">×</button></td></tr>`).join('')}</tbody></table></div>`;
  }
  function openingPanel(d){return `<div class="card"><div class="actions" style="justify-content:space-between"><h3>Médicos com consulta</h3><button class="secondary" onclick="App.addProfessional(false,'doctor')">+ Médico</button></div>${professionalRows(d,false,'doctor')}<div class="actions" style="justify-content:space-between;margin-top:20px"><h3>Técnicos / terapeutas e vagas de Planning</h3><button class="secondary" onclick="App.addProfessional(false,'therapist')">+ Técnico/terapeuta</button></div>${professionalRows(d,false,'therapist')}<h3 style="margin-top:20px">Valores absolutos de abertura</h3><div class="notice">Introdução manual enquanto não existe API Clicloud. Cada indicador é independente e tem como objetivo operacional chegar a 0.</div><div class="form-grid">${indicatorFields(d,'open','abertura')}</div><button class="primary" style="margin-top:14px" onclick="App.saveIndicators('abertura')">Guardar abertura</button>${indicatorHistory(d)}</div><div class="card"><h3>Tarefas de abertura</h3>${taskRows('open',d)}</div>`}
  function currentIndicatorPanel(d){return `<div class="card"><h3>Atualização progressiva dos contadores</h3><div class="notice">A Lista de Espera Clicloud é apenas um contador absoluto e não corresponde ao funil individual de Pedidos.</div><div class="form-grid">${indicatorFields(d,'current','atualização')}</div><button class="primary" style="margin-top:14px" onclick="App.saveIndicators('atualização')">Guardar valores atuais</button><div class="table-wrap" style="margin-top:14px"><table><thead><tr><th>Indicador</th><th>Abertura</th><th>Atual</th><th>Objetivo</th></tr></thead><tbody>${indicatorDefs.map(x=>`<tr><td>${x.label}</td><td>${d.indicators[x.id].opening??'—'}</td><td><b>${d.indicators[x.id].current}</b></td><td>0</td></tr>`).join('')}</tbody></table></div>${indicatorHistory(d)}</div>`}
  function indicatorHistory(d){return `<details style="margin-top:14px"><summary><b>Histórico completo dos indicadores</b></summary>${indicatorDefs.flatMap(def=>(d.indicators[def.id]?.history||[]).map(h=>`<div class="audit-line"><span>${fmt(h.at)}</span><b>${esc(def.label)}</b><span>${h.previous} → ${h.value} · ${esc(user(h.by).name)} · ${esc(clinic(h.clinic).name)} · ${esc(h.phase)}</span></div>`)).sort((a,b)=>b.localeCompare(a)).join('')||'<p class="muted">Sem alterações.</p>'}</details>`}
  function taskRows(phase,d){const list=taskList(phase);return list.map(t=>{const st=d.taskStatus[t.id]||{status:'todo'};return `<div class="task-row"><div><b>${esc(t.name)}</b> ${t.required?'<span class="pill">Obrigatória</span>':''}<div class="meta">${esc(t.deadline||'Sem limite')} · ${esc(t.role)} ${st.at?`· ${esc(user(st.by).name)}, ${fmt(st.at)}`:''}</div></div><span class="pill ${st.status==='done'?'green':st.status==='doing'?'orange':''}">${st.status==='done'?'Concluída':st.status==='doing'?'Em curso':'Por fazer'}</span><div class="actions">${phase==='live'?`<button class="primary" onclick="App.openTaskAction('${t.id}')">Abrir ação</button>`:''}<button class="secondary" onclick="App.setTask('${t.id}','${st.status==='done'?'todo':'done'}')">${st.status==='done'?'Reabrir':'Concluir'}</button></div></div>`}).join('')||'<p class="muted">Sem tarefas ativas.</p>'}
  function livePanel(d){return `${currentIndicatorPanel(d)}<div class="card"><h3>Tarefas vivas</h3>${taskRows('live',d)}</div>`}
  function closingPanel(d){return `<div class="card"><h3>Valores absolutos de fecho</h3><div class="form-grid">${indicatorFields(d,'close','fecho')}</div><button class="primary" style="margin-top:14px" onclick="App.saveIndicators('fecho')">Guardar fecho</button><div class="notice ok"><b>Abertura → atual → fecho</b>${indicatorDefs.map(x=>`<br>${x.label}: ${d.indicators[x.id].opening??'—'} → ${d.indicators[x.id].current} → ${d.indicators[x.id].closing??'—'}`).join('')}</div>${indicatorHistory(d)}</div><div class="card"><h3>Resultados por profissional</h3><h3>Médicos</h3>${professionalRows(d,true,'doctor')}<h3 style="margin-top:18px">Técnicos / terapeutas</h3>${professionalRows(d,true,'therapist')}</div><div class="card"><h3>Tarefas de fecho</h3>${taskRows('close',d)}<div class="actions" style="margin-top:14px"><button class="primary" onclick="App.attemptClose()">${d.closed?'Reabrir dia':'Fechar dia e criar resumo'}</button>${!d.closed?'<button class="danger" onclick="App.authorizedException()">Exceção autorizada</button>':''}</div>${d.summary?`<div class="notice ok"><b>Resumo diário:</b> ${esc(d.summary)}</div>`:''}</div>`}
  const sum=(arr,k)=>arr.reduce((n,x)=>n+(+x[k]||0),0); const delta=(a,b)=>`${(+b||0)-(+a||0)>=0?'+':''}${(+b||0)-(+a||0)}`;
  function setPhase(p){state.opPhase=p;persist()}
  function addProfessional(close,kind){const d=day(), arr=close?d.close.professionals:d.open.professionals;arr.push(close?{name:'',kind,done:0,missed:0,rescheduled:0,cancelled:0,slots:0}:{name:'',kind,selected:true,consults:0,slots:0});persist()}
  function removeProfessional(i,close){(close?day().close.professionals:day().open.professionals).splice(i,1);persist()}
  function updateProfessional(i,k,v,close){const p=(close?day().close.professionals:day().open.professionals)[i];p[k]=k==='name'||k==='selected'?v:+v;persist(false)}
  function saveIndicators(phase){const d=day(),prefix=phase==='abertura'?'open':phase==='fecho'?'close':'current';indicatorDefs.forEach(x=>recordIndicator(d,x.id,+$(`${prefix}_${x.id}`).value,phase));if(phase==='abertura'){d.open.saved=true;d.open.at=now();d.open.by=state.currentUser;['open_team','open_counts','open_suspended'].forEach(id=>d.taskStatus[id]={status:'done',at:now(),by:state.currentUser})}if(phase==='fecho'){d.close.saved=true;d.close.at=now();d.close.by=state.currentUser;['close_counts','close_suspended'].forEach(id=>d.taskStatus[id]={status:'done',at:now(),by:state.currentUser})}persist();toast(`Valores de ${phase} guardados`)}
  function saveOpening(){saveIndicators('abertura')}
  function saveClosing(){saveIndicators('fecho')}
  function setTask(id,status){const d=day(),old=d.taskStatus[id]?.status||'todo';d.taskStatus[id]={status,at:now(),by:state.currentUser};audit('Tarefas',status==='todo'?'Tarefa reaberta':'Tarefa concluída',`${id}: ${old} → ${status}; ${d.date}/${d.clinic}`);persist()}
  function openTaskAction(id){const d=day(),t=state.tasks.find(x=>x.id===id);d.taskStatus[id]={status:'doing',at:now(),by:state.currentUser};audit('Tarefas','Ação iniciada',`${id}; ${d.date}/${d.clinic}`);const indicatorId={waitClicloud:'waitClicloud',suspended:'suspended',confirmations:'confirmations',reval:'revals'}[t.action];if(indicatorId){const def=indicatorDefs.find(x=>x.id===indicatorId);modal(t.name,`<div class="notice">Atualize o número absoluto restante. Objetivo: 0.</div><label>${def.label}</label><input id="taskIndicator" type="number" min="0" value="${d.indicators[indicatorId].current}"><label style="margin-top:10px">Observação</label><textarea id="taskIndicatorNote"></textarea><button class="primary" style="margin-top:12px" onclick="App.finishIndicatorTask('${id}','${indicatorId}')">Guardar atualização</button>`);persist(false);return}if(t.action==='planning'){const rows=d.open.professionals.filter(x=>x.kind==='therapist'&&x.slots>0).map((p,i)=>`<tr><td>${esc(p.name)}</td><td>${p.slots}</td><td><input id="fill_${i}" type="number" min="0" max="${p.slots}" value="0"></td><td><input id="note_${i}"></td></tr>`).join('');modal(t.name,`<div class="table-wrap"><table><thead><tr><th>Técnico/terapeuta</th><th>Vagas</th><th>Preenchidas</th><th>Resultado</th></tr></thead><tbody>${rows||'<tr><td colspan="4">Sem vagas.</td></tr>'}</tbody></table></div><button class="primary" style="margin-top:12px" onclick="App.finishTaskAction('${id}')">Guardar</button>`);persist(false);return}toast('Tarefa iniciada');persist()}
  function finishIndicatorTask(taskId,indicatorId){const d=day(),value=+$('taskIndicator').value,note=$('taskIndicatorNote').value;recordIndicator(d,indicatorId,value,'atualização');d.indicators[indicatorId].history.at(-1).note=note;d.taskStatus[taskId]={status:value===0?'done':'doing',at:now(),by:state.currentUser};persist();closeModal();toast(value===0?'Objetivo atingido: 0':'Progresso guardado')}
  function finishTaskAction(id){const d=day(),t=state.tasks.find(x=>x.id===id);if(t.action==='confirm') (d.appointments||[]).forEach(a=>a.status=$(`result_${a.id}`)?.value||a.status);if(t.action==='planning'){const therapists=d.open.professionals.filter(x=>x.kind==='therapist'&&x.slots>0);d.planningActions=d.planningActions||[];therapists.forEach((p,i)=>d.planningActions.push({at:now(),by:state.currentUser,clinic:d.clinic,date:d.date,professional:p.name,filled:+($(`fill_${i}`)?.value||0),note:$(`note_${i}`)?.value||''}))}d.taskStatus[id]={status:'done',at:now(),by:state.currentUser};audit('Tarefas','Resultados registados',`${t.name}; ${d.date}/${d.clinic}`);persist();closeModal();toast('Resultados guardados')}
  function attemptClose(){const d=day();if(d.closed){d.closed=false;audit('Operação','Dia reaberto',`${d.date}/${d.clinic}`);persist();return}const pending=[...taskList('live'),...taskList('close')].filter(t=>t.required&&d.taskStatus[t.id]?.status!=='done');if(pending.length){toast(`${pending.length} tarefa(s) obrigatória(s) pendente(s)`);modal('Fecho bloqueado',`<div class="notice bad">Conclua as tarefas obrigatórias: <b>${pending.map(x=>esc(x.name)).join(', ')}</b>, ou use uma exceção autorizada com justificação.</div>`);return}completeClose(d)}
  function completeClose(d,reason=''){d.closed=true;d.closedAt=now();d.closedBy=state.currentUser;d.summary=`${clinic(d.clinic).name}: ${sum(d.close.professionals,'done')} realizadas, ${sum(d.close.professionals,'missed')} faltas, ${sum(d.close.professionals,'rescheduled')} reagendadas; Lista de Espera Clicloud ${d.indicators.waitClicloud.current}; suspensos ${d.indicators.suspended.current}; confirmações ${d.indicators.confirmations.current}.`;if(reason)d.exception={reason,by:state.currentUser,at:now()};audit('Operação',reason?'Fecho com exceção autorizada':'Dia fechado',`${d.date}/${d.clinic}${reason?`; justificação: ${reason}`:''}`);persist();closeModal();toast('Dia fechado e resumo criado')}
  function authorizedException(){modal('Exceção autorizada',`<label>Justificação obrigatória</label><textarea id="exceptionReason" placeholder="Explique por que razão o dia pode ser fechado com tarefas pendentes"></textarea><label style="margin-top:10px">Confirmação de gestor</label><input id="managerCode" type="password" placeholder="Código de demonstração: 2026"><div class="actions" style="margin-top:14px"><button class="danger" onclick="App.confirmException()">Autorizar e fechar</button></div>`)}
  function confirmException(){const reason=$('exceptionReason').value.trim();if(!reason||$('managerCode').value!=='2026'){toast('Indique justificação e código válido');return}completeClose(day(),reason)}

  function requestMetrics(){const requests=state.requests,worked=requests.filter(r=>r.history.length||r.stage!=='Novo pedido').length, marked=requests.filter(r=>r.stage==='Marcado');const avg=marked.length?Math.round(marked.reduce((n,r)=>n+((new Date(r.completed||now())-new Date(r.created))/3600000),0)/marked.length):0;return {worked,marked:marked.length,avg};}
  function renderRequests(){const m=requestMetrics();$('waitContent').innerHTML=`<div class="cards"><div class="card"><div class="muted">Novos hoje</div><div class="metric">${state.requests.filter(r=>r.created.slice(0,10)===today()).length}</div></div><div class="card"><div class="muted">Trabalhados</div><div class="metric">${m.worked}</div></div><div class="card"><div class="muted">Marcados</div><div class="metric green">${m.marked}</div></div><div class="card"><div class="muted">Espera média até marcação</div><div class="metric">${m.avg} h</div></div></div><div class="funnel">${requestStages.map(stage=>`<div class="funnel-col"><div class="funnel-head"><span>${stage}</span><span>${state.requests.filter(r=>r.stage===stage).length}</span></div>${state.requests.filter(r=>r.stage===stage).map(requestCard).join('')}</div>`).join('')}</div><div class="notice"><b>Lista interna:</b> utentes cuja marcação ainda não foi concluída. Objetivo operacional: manter próximo de 0. Não corresponde à Lista de Espera Clicloud.</div><div class="card" style="margin-top:14px"><h3>Lista interna e resultados fora do funil</h3>${state.requests.filter(r=>['Lista interna','Sem resposta','Recusou','Suspenso','Cancelado'].includes(r.stage)).map(requestCard).join('')||'<span class="muted">Sem registos.</span>'}</div>`;}
  function requestCard(r){return `<div class="funnel-card" onclick="App.openRequest('${r.id}')"><b>${esc(r.name)}</b><div class="meta">${esc(clinic(r.clinic)?.name)} · ${esc(r.specialty)}</div><div class="meta">${esc(r.doctor)} · ${esc(user(r.owner).name)}</div></div>`}
  function openRequestForm(){const u=user(), defaultClinic=u.clinic;modal('Novo pedido',`<div class="form-grid"><div><label>Clínica pretendida</label><select id="rClinic" onchange="App.refreshRequestSpecialties()" ${!u.canChangeClinic?'disabled':''}>${options(clinics,x=>x.id,x=>x.name)}</select></div><div><label>Especialidade</label><select id="rSpecialty" onchange="App.refreshRequestDoctors()"></select></div><div><label>Médico</label><select id="rDoctor"></select></div><div><label>Nome do utente</label><input id="rName"></div><div><label>Telefone / contactos</label><input id="rPhone"></div><div class="span-2"><label>Observações</label><textarea id="rNotes"></textarea></div></div><div class="meta" style="margin-top:10px">Entrada e responsável são registados automaticamente.</div><button class="primary" style="margin-top:14px" onclick="App.addRequest()">Criar pedido</button>`);$('rClinic').value=defaultClinic;refreshRequestSpecialties()}
  function refreshRequestSpecialties(){const c=clinic($('rClinic').value);$('rSpecialty').innerHTML=options(Object.keys(c.specialties),x=>x);refreshRequestDoctors()}
  function refreshRequestDoctors(){const c=clinic($('rClinic').value),spec=$('rSpecialty').value;$('rDoctor').innerHTML=options(c.specialties[spec]||[],x=>x)}
  function addRequest(){if(!$('rClinic').value||!$('rName').value.trim()||!$('rPhone').value.trim()){toast('Clínica pretendida, nome e contacto são obrigatórios');return}const r={id:uid('r'),created:now(),clinic:$('rClinic').value,specialty:$('rSpecialty').value,doctor:$('rDoctor').value,name:$('rName').value.trim(),phone:$('rPhone').value.trim(),notes:$('rNotes').value.trim(),stage:'Novo pedido',owner:state.currentUser,history:[]};state.requests.push(r);audit('Pedidos','Novo pedido criado',`${r.name} · ${clinic(r.clinic).name}`);persist();closeModal();toast('Pedido criado')}
  function openRequest(id){const r=state.requests.find(x=>x.id===id);modal(r.name,`<div class="form-grid"><div><label>Clínica</label><input disabled value="${esc(clinic(r.clinic).name)}"></div><div><label>Especialidade</label><input disabled value="${esc(r.specialty)}"></div><div><label>Médico</label><input disabled value="${esc(r.doctor)}"></div><div><label>Responsável</label><select id="editOwner">${options(users,x=>x.id,x=>x.name)}</select></div><div><label>Estado / resultado</label><select id="editStage">${options([...requestStages,'Lista interna','Sem resposta','Recusou','Suspenso','Cancelado'],x=>x)}</select></div><div class="span-2"><label>Resultado / nota da ação</label><textarea id="requestResult" placeholder="Ex.: contacto efetuado, aceita proposta para dia..."></textarea></div><div class="span-2"><label>Patologia a tratar (obrigatória quando Suspenso)</label><input id="requestPathology" value="${esc(r.pathology||'')}"></div></div><div class="actions" style="margin-top:12px"><button class="primary" onclick="App.updateRequest('${r.id}')">Guardar ação</button><button class="secondary" onclick="App.startRequestChat('${r.id}')">Conversar sobre pedido</button></div><h3 style="margin-top:20px">Histórico</h3>${r.history.slice().reverse().map(h=>`<div class="audit-line"><span>${fmt(h.at)}</span><b>${esc(user(h.by).name)}</b><span>${esc(h.from)} → ${esc(h.to)} · ${esc(h.note)}</span></div>`).join('')||'<p class="muted">Sem alterações.</p>'}`);$('editOwner').value=r.owner;$('editStage').value=r.stage}
  function updateRequest(id){const r=state.requests.find(x=>x.id===id),old=r.stage,newStage=$('editStage').value,note=$('requestResult').value.trim(),pathology=$('requestPathology').value.trim();if(newStage==='Suspenso'&&!pathology)return toast('Indique a patologia a tratar');r.pathology=pathology;r.stage=newStage;r.owner=$('editOwner').value;if(newStage==='Marcado'&&!r.completed)r.completed=now();r.history.push({at:now(),by:state.currentUser,from:old,to:newStage,note});audit('Pedidos','Pedido trabalhado',`${r.name}: ${old} → ${newStage}${note?`; ${note}`:''}`);persist();closeModal();toast('Ação registada')}

  let activeConversation=null;
  function unreadCount(){return state.conversations.flatMap(c=>c.messages).filter(m=>m.from!==state.currentUser&&!m.readBy.includes(state.currentUser)).length}
  function updateUnread(){const n=unreadCount();$('unread').textContent=n;$('navUnread').textContent=n||''}
  function renderChat(){if(!activeConversation)activeConversation=state.conversations[0]?.id;const c=state.conversations.find(x=>x.id===activeConversation);$('chatContent').innerHTML=`<div class="split"><div class="card" style="padding:0">${state.conversations.map(x=>`<div class="conversation ${x.id===activeConversation?'active':''}" onclick="App.selectConversation('${x.id}')"><b>${esc(x.title)}</b><div class="meta">${x.requestId?'Associada a pedido':''} · ${x.messages.length} mensagens</div></div>`).join('')||'<p class="modal-pad muted">Sem conversas.</p>'}</div><div class="card">${c?`<h3>${esc(c.title)}</h3>${c.requestId?`<button class="secondary" onclick="App.openRequest('${c.requestId}')">Ver pedido associado</button>`:''}<div class="messages" id="messages">${c.messages.map(m=>`<div class="bubble ${m.from===state.currentUser?'mine':''}"><b>${esc(user(m.from).name)}</b><div>${esc(m.text)}</div><div class="meta">${fmt(m.at)} · ${m.readBy.length>1?'Lida':'Enviada'}</div></div>`).join('')}</div><div class="actions" style="margin-top:10px"><input id="chatMessage" placeholder="Escrever mensagem…" onkeydown="if(event.key==='Enter')App.sendMessage()"><button class="primary" onclick="App.sendMessage()">Enviar</button></div>`:'<p class="muted">Selecione ou crie uma conversa.</p>'}</div></div>`;if(c&&$('chat').classList.contains('active')){c.messages.forEach(m=>{if(!m.readBy.includes(state.currentUser))m.readBy.push(state.currentUser)});persist(false);updateUnread();setTimeout(()=>{const el=$('messages');if(el)el.scrollTop=el.scrollHeight},0)}}
  function selectConversation(id){activeConversation=id;renderChat()}
  function sendMessage(){const input=$('chatMessage'),text=input.value.trim();if(!text)return;const c=state.conversations.find(x=>x.id===activeConversation);c.messages.push({id:uid('m'),from:state.currentUser,at:now(),text,readBy:[state.currentUser]});audit('Chat','Mensagem enviada',c.title);persist();renderChat()}
  function newConversation(){modal('Nova conversa',`<label>Assunto</label><input id="convTitle"><label style="margin-top:10px">Destinatários</label>${users.filter(x=>x.id!==state.currentUser).map(x=>`<label class="check"><input type="checkbox" name="member" value="${x.id}"><span>${esc(x.name)} · ${esc(clinic(x.clinic).name)}</span></label>`).join('')}<button class="primary" style="margin-top:12px" onclick="App.createConversation()">Criar conversa</button>`)}
  function createConversation(){const title=$('convTitle').value.trim(),members=[...document.querySelectorAll('[name=member]:checked')].map(x=>x.value);if(!title||!members.length){toast('Indique assunto e destinatário');return}const c={id:uid('cv'),title,members:[state.currentUser,...members],requestId:null,messages:[]};state.conversations.push(c);activeConversation=c.id;audit('Chat','Conversa criada',title);persist();closeModal()}
  function startRequestChat(requestId){const r=state.requests.find(x=>x.id===requestId);let c=state.conversations.find(x=>x.requestId===requestId);if(!c){c={id:uid('cv'),title:`Pedido — ${r.name}`,members:users.map(x=>x.id),requestId,messages:[]};state.conversations.push(c);audit('Chat','Conversa associada a pedido',r.name)}activeConversation=c.id;closeModal();showView('chat');persist()}

  function roleName(id){return state.jobRoles.find(x=>x.id===id)?.name||id}
  function missingDocs(c){return (c.documents||[]).filter(d=>d.required&&d.status!=='Validado').length}
  function renderHr(){const active=state.candidates.filter(x=>x.active),pending=state.timeOccurrences.filter(x=>x.status==='Pendente').length;$('hrContent').innerHTML=`<div class="cards"><div class="card"><div class="muted">Processos ativos</div><div class="metric">${active.length}</div></div><div class="card"><div class="muted">Documentos por regularizar</div><div class="metric red">${active.reduce((n,c)=>n+missingDocs(c),0)}</div></div><div class="card"><div class="muted">Ocorrências de ponto pendentes</div><div class="metric red">${pending}</div><button class="secondary" onclick="App.manageTimeOccurrences()">Analisar</button></div><div class="card"><div class="muted">Livro de ponto</div><button class="primary" onclick="App.prepareClock()">Próxima marcação</button><button class="secondary" onclick="App.temporaryExit()">Saída temporária</button><button class="secondary" onclick="App.requestTimeCorrection()">Pedir correção</button></div></div><div class="actions" style="margin-bottom:12px"><button class="secondary" onclick="App.manageContracts()">Tipos de contrato</button><button class="secondary" onclick="App.manageJobRoles()">Funções/cargos</button></div><div class="kanban">${candidateStages.map(stage=>`<div class="kanban-col"><div class="funnel-head"><span>${stage}</span><span>${active.filter(x=>x.stage===stage).length}</span></div>${active.filter(x=>x.stage===stage).map(c=>`<div class="funnel-card" onclick="App.openCandidate('${c.id}')"><b>${esc(c.name)}</b><div class="meta">${esc(roleName(c.role))} · ${esc(clinic(c.clinic).name)}</div>${missingDocs(c)?`<span class="pill red">${missingDocs(c)} por regularizar</span>`:'<span class="pill green">Documentos OK</span>'}</div>`).join('')}</div>`).join('')}</div>`}
  function contractFor(c){return state.contractTypes.find(x=>x.id===c.contract)}
  function docsFromContract(contractId){const ct=state.contractTypes.find(x=>x.id===contractId);return (ct?.items||[]).filter(i=>i.active!==false).map(i=>({itemId:i.id,name:i.name,required:i.required,status:'Em falta'}))}
  function openCandidateForm(){modal('Novo colaborador / candidato',`<div class="form-grid"><div><label>Nome</label><input id="pName"></div><div><label>Email</label><input id="pEmail" type="email"></div><div><label>Telefone</label><input id="pPhone"></div><div><label>Função/cargo</label><select id="pRole">${options(state.jobRoles.filter(x=>x.active),x=>x.id,x=>x.name)}</select></div><div><label>Clínica</label><select id="pClinic">${options(clinics,x=>x.id,x=>x.name)}</select></div><div><label>Tipo de contrato</label><select id="pContract">${options(state.contractTypes.filter(x=>x.active),x=>x.id,x=>x.name)}</select></div><div><label>NIF</label><input id="pNif"></div><div><label>NISS</label><input id="pNiss"></div><div class="span-2"><label>IBAN</label><input id="pIban"></div><div><label>Data de nascimento</label><input id="pBirth" type="date"></div><div class="span-2"><label>Morada</label><input id="pAddress"></div></div><div class="notice">A checklist será gerada automaticamente a partir do tipo de contrato.</div><button class="primary" onclick="App.addCandidate()">Criar ficha</button>`)}
  function addCandidate(){if(!$('pName').value.trim())return toast('Nome obrigatório');const contract=$('pContract').value,c={id:uid('p'),name:$('pName').value,email:$('pEmail').value,phone:$('pPhone').value,role:$('pRole').value,clinic:$('pClinic').value,contract,stage:'Candidato',nif:$('pNif').value,niss:$('pNiss').value,iban:$('pIban').value,birthDate:$('pBirth').value,address:$('pAddress').value,notes:'',active:true,documents:docsFromContract(contract),history:[]};state.candidates.push(c);audit('RH','Ficha criada e checklist gerada',c.name);persist();closeModal()}
  function documentRows(c){return (c.documents||[]).map((d,i)=>`<div class="check"><div style="flex:1"><b>${esc(d.name)}</b> ${d.required?'<span class="pill">Obrigatório</span>':''}<div><span class="pill ${d.status==='Validado'?'green':d.status==='Rejeitado'?'red':'orange'}">${d.status}</span></div><div class="meta">${d.sentAt?`Enviado por ${esc(user(d.sentBy).name)} em ${fmt(d.sentAt)}. `:''}${d.reviewedAt?`${d.status} por ${esc(user(d.reviewedBy).name)} em ${fmt(d.reviewedAt)}.`:''}</div></div><input id="doc_${i}" type="file" style="max-width:190px"><button class="secondary" onclick="App.uploadDocument('${c.id}',${i})">Enviar</button>${d.status==='Enviado'?`<button class="primary" onclick="App.submitDocument('${c.id}',${i})">Submeter para validação</button>`:''}${['RH','Gestor'].includes(user().role)?`<button class="primary" onclick="App.reviewDocument('${c.id}',${i},'Validado')">Validar</button><button class="danger" onclick="App.reviewDocument('${c.id}',${i},'Rejeitado')">Rejeitar</button>`:''}</div>`).join('')}
  function openCandidate(id){const c=state.candidates.find(x=>x.id===id);modal(c.name,`<div class="form-grid"><div><label>Etapa</label><select id="candidateStage">${options(candidateStages,x=>x)}</select></div><div><label>Contrato</label><select id="candidateContract">${options(state.contractTypes.filter(x=>x.active),x=>x.id,x=>x.name)}</select></div><div><label>Função/cargo</label><select id="candidateRole">${options(state.jobRoles.filter(x=>x.active),x=>x.id,x=>x.name)}</select></div><div><label>NIF</label><input id="candidateNif" value="${esc(c.nif||'')}"></div><div><label>NISS</label><input id="candidateNiss" value="${esc(c.niss||'')}"></div><div><label>IBAN</label><input id="candidateIban" value="${esc(c.iban||'')}"></div><div class="span-2"><label>Morada</label><input id="candidateAddress" value="${esc(c.address||'')}"></div><div class="span-2"><label>Notas</label><textarea id="candidateNotes">${esc(c.notes||'')}</textarea></div></div><h3 style="margin-top:16px">Documentos</h3>${missingDocs(c)?'<div class="notice bad">Existem documentos obrigatórios em falta ou por validar.</div>':''}${documentRows(c)}<div class="actions" style="margin-top:14px"><button class="primary" onclick="App.saveCandidate('${id}')">Guardar ficha</button><button class="danger" onclick="App.archiveCandidate('${id}')">Arquivar</button></div>`);$('candidateStage').value=c.stage;$('candidateContract').value=c.contract;$('candidateRole').value=c.role}
  function saveCandidate(id){const c=state.candidates.find(x=>x.id===id),oldContract=c.contract,newContract=$('candidateContract').value;c.stage=$('candidateStage').value;c.role=$('candidateRole').value;c.nif=$('candidateNif').value;c.niss=$('candidateNiss').value;c.iban=$('candidateIban').value;c.address=$('candidateAddress').value;c.notes=$('candidateNotes').value;if(oldContract!==newContract){c.contract=newContract;const existing=new Map(c.documents.map(x=>[x.itemId,x]));c.documents=docsFromContract(newContract).map(x=>existing.get(x.itemId)||x)}c.history.push({at:now(),by:state.currentUser,action:'Ficha atualizada'});audit('RH','Ficha atualizada',c.name);persist();closeModal()}
  function uploadDocument(id,index){const c=state.candidates.find(x=>x.id===id),file=$(`doc_${index}`).files?.[0];if(!file)return toast('Selecione um ficheiro');const d=c.documents[index];d.status='Enviado';d.fileName=file.name;d.sentBy=state.currentUser;d.sentAt=now();delete d.reviewedBy;delete d.reviewedAt;audit('RH','Documento enviado',`${c.name}: ${d.name}`);persist();openCandidate(id)}
  function submitDocument(id,index){const c=state.candidates.find(x=>x.id===id),d=c.documents[index];if(d.status!=='Enviado')return;d.status='Pendente de validação';audit('RH','Documento submetido para validação',`${c.name}: ${d.name}`);persist();openCandidate(id)}
  function reviewDocument(id,index,status){if(!['RH','Gestor'].includes(user().role))return toast('Apenas RH/Administração pode validar');const c=state.candidates.find(x=>x.id===id),d=c.documents[index];if(!d.sentAt)return toast('O documento ainda não foi enviado');d.status=status;d.reviewedBy=state.currentUser;d.reviewedAt=now();audit('RH',`Documento ${status.toLowerCase()}`,`${c.name}: ${d.name}`);persist();openCandidate(id)}
  function archiveCandidate(id){const c=state.candidates.find(x=>x.id===id);c.active=false;audit('RH','Colaborador arquivado',c.name);persist();closeModal()}
  function manageJobRoles(){modal('Funções e cargos',`${state.jobRoles.map(r=>`<div class="task-row"><input id="role_${r.id}" value="${esc(r.name)}"><span class="pill">${r.active?'Ativa':'Inativa'}</span><div><button class="secondary" onclick="App.saveJobRole('${r.id}')">Guardar</button><button class="danger" onclick="App.toggleJobRole('${r.id}')">${r.active?'Inativar':'Ativar'}</button></div></div>`).join('')}<div class="actions"><input id="newRole" placeholder="Nova função"><button class="primary" onclick="App.addJobRole()">Adicionar</button></div>`)}
  function addJobRole(){const name=$('newRole').value.trim();if(!name)return;state.jobRoles.push({id:uid('jr'),name,active:true});audit('RH','Função criada',name);persist();manageJobRoles()}function saveJobRole(id){const r=state.jobRoles.find(x=>x.id===id);r.name=$(`role_${id}`).value;audit('RH','Função editada',r.name);persist();manageJobRoles()}function toggleJobRole(id){const r=state.jobRoles.find(x=>x.id===id);r.active=!r.active;audit('RH','Função alterada',r.name);persist();manageJobRoles()}
  function manageContracts(){modal('Tipos de contrato e checklists',`${state.contractTypes.map(ct=>`<div class="card"><div class="actions"><input id="ct_${ct.id}" value="${esc(ct.name)}"><button class="secondary" onclick="App.saveContract('${ct.id}')">Guardar nome</button><button class="danger" onclick="App.toggleContract('${ct.id}')">${ct.active?'Inativar':'Ativar'}</button></div>${ct.items.map((i,n)=>`<div class="check"><input id="ci_${ct.id}_${n}" value="${esc(i.name)}"><label><input id="cr_${ct.id}_${n}" type="checkbox" ${i.required?'checked':''}> Obrigatório</label><button class="secondary" onclick="App.saveContractItem('${ct.id}',${n})">Guardar</button></div>`).join('')}<div class="actions"><input id="newItem_${ct.id}" placeholder="Novo documento"><button class="secondary" onclick="App.addContractItem('${ct.id}')">Adicionar</button></div></div>`).join('')}<div class="actions"><input id="newContract" placeholder="Novo tipo"><button class="primary" onclick="App.addContractType()">Criar tipo</button></div>`)}
  function syncContractDocs(contractId){const ct=state.contractTypes.find(x=>x.id===contractId);state.candidates.filter(c=>c.contract===contractId).forEach(c=>{const existing=new Map((c.documents||[]).map(d=>[d.itemId,d]));c.documents=ct.items.filter(i=>i.active!==false).map(i=>({...existing.get(i.id),itemId:i.id,name:i.name,required:i.required,status:existing.get(i.id)?.status||'Em falta'}))})} function addContractType(){const name=$('newContract').value.trim();if(!name)return;state.contractTypes.push({id:uid('ct'),name,active:true,items:[]});audit('RH','Tipo de contrato criado',name);persist();manageContracts()}function saveContract(id){const ct=state.contractTypes.find(x=>x.id===id);ct.name=$(`ct_${id}`).value;audit('RH','Tipo de contrato editado',ct.name);persist();manageContracts()}function addContractItem(id){const name=$(`newItem_${id}`).value.trim();if(!name)return;state.contractTypes.find(x=>x.id===id).items.push({id:uid('i'),name,required:true,active:true});syncContractDocs(id);audit('RH','Documento configurado',name);persist();manageContracts()}function saveContractItem(id,n){const i=state.contractTypes.find(x=>x.id===id).items[n];i.name=$(`ci_${id}_${n}`).value;i.required=$(`cr_${id}_${n}`).checked;syncContractDocs(id);audit('RH','Checklist editada',i.name);persist();manageContracts()}function toggleContract(id){const ct=state.contractTypes.find(x=>x.id===id);ct.active=!ct.active;audit('RH','Contrato alterado',ct.name);persist();manageContracts()}
  const markTypes=['Entrada','Saída para almoço','Regresso do almoço','Saída'];
  function todaysEntries(){return state.timeEntries.filter(x=>x.user===state.currentUser&&x.at.slice(0,10)===today()&&markTypes.includes(x.type))}
  function prepareClock(){const u=user(),index=Math.min(todaysEntries().length,3),type=markTypes[index],planned=u.schedule[index],c=clinic(u.clinic);modal('Confirmar marcação de ponto',`<div class="notice"><b>${type}</b><br>Hora prevista: ${planned}<br>Hora atual: ${new Date().toLocaleTimeString('pt-PT',{hour:'2-digit',minute:'2-digit'})}<br>Clínica: ${esc(c.name)}<br>Localização: será validada por GPS antes de registar.</div><button class="primary" onclick="App.confirmClock('${type}','${planned}')">Confirmar com GPS</button>`)}
  function distanceM(a,b,c,d){const R=6371e3,p=x=>x*Math.PI/180,x=(c-a)*Math.PI/180,y=(d-b)*Math.PI/180,q=Math.sin(x/2)**2+Math.cos(p(a))*Math.cos(p(c))*Math.sin(y/2)**2;return 2*R*Math.atan2(Math.sqrt(q),Math.sqrt(1-q))}
  function confirmClock(type,planned){if(!navigator.geolocation)return toast('GPS indisponível');navigator.geolocation.getCurrentPosition(pos=>{const c=clinic(user().clinic),distance=distanceM(pos.coords.latitude,pos.coords.longitude,c.lat,c.lng),current=new Date(),[h,m]=planned.split(':').map(Number),target=new Date();target.setHours(h,m,0,0);const diff=Math.round((current-target)/60000),base={id:uid('te'),user:state.currentUser,clinic:c.id,type,planned,at:now(),geo:`${pos.coords.latitude.toFixed(5)}, ${pos.coords.longitude.toFixed(5)}`,distance};if(distance>c.radius||Math.abs(diff)>5){state.timeOccurrences.push({...base,status:'Pendente',reason:distance>c.radius?'Fora das instalações':`Fora da janela autorizada (${diff} min)`});audit('Ponto','Ocorrência pendente',`${type}; ${base.reason}`);toast('Fora das regras: enviado para aprovação')}else{state.timeEntries.push(base);audit('Ponto','Marcação registada',`${type}; ${base.at}; ${base.geo}`);toast(`${type} registada às ${current.toLocaleTimeString('pt-PT',{hour:'2-digit',minute:'2-digit'})}`)}persist();closeModal()},()=>toast('Não foi possível validar a localização'))}
  function temporaryExit(){const open=state.timeEntries.findLast?.(x=>x.user===state.currentUser&&x.type==='Saída temporária'&&!x.returnAt);const type=open?'Regresso de saída temporária':'Saída temporária';modal(type,`<label>Motivo / observação</label><textarea id="tempReason" ${open?'disabled':''}>${esc(open?.reason||'')}</textarea><div class="notice">Esta ocorrência ficará sempre pendente de aprovação da Administração.</div><button class="primary" onclick="App.confirmTemporary('${type}','${open?.id||''}')">Confirmar com GPS</button>`)}
  function confirmTemporary(type,exitId){const reason=$('tempReason').value.trim();if(type==='Saída temporária'&&!reason)return toast('Indique o motivo');navigator.geolocation.getCurrentPosition(pos=>{const c=clinic(user().clinic),entry={id:uid('te'),user:state.currentUser,clinic:c.id,type,at:now(),geo:`${pos.coords.latitude.toFixed(5)}, ${pos.coords.longitude.toFixed(5)}`,reason,status:'Pendente'};if(type.startsWith('Regresso')){const exit=state.timeEntries.find(x=>x.id===exitId);exit.returnAt=entry.at;exit.returnGeo=entry.geo;exit.durationMinutes=Math.round((new Date(entry.at)-new Date(exit.at))/60000)}else state.timeEntries.push(entry);state.timeOccurrences.push({...entry,exitId:exitId||entry.id});audit('Ponto',type,reason);persist();closeModal();toast(`${type} registado; aprovação pendente`)},()=>toast('GPS obrigatório'))}
  function manageTimeOccurrences(){modal('Ocorrências pendentes',`${state.timeOccurrences.filter(x=>x.status==='Pendente').map(x=>`<div class="card"><b>${esc(user(x.user).name)} · ${esc(x.type)}</b><div class="meta">${fmt(x.at)} · ${esc(clinic(x.clinic).name)} · GPS ${esc(x.geo)} · previsto ${esc(x.planned||'—')}</div><p>${esc(x.reason||'')}</p><input id="occ_${x.id}" placeholder="Observação da Administração"><button class="primary" onclick="App.reviewOccurrence('${x.id}','Aprovada')">Aprovar</button> <button class="danger" onclick="App.reviewOccurrence('${x.id}','Recusada')">Recusar</button></div>`).join('')||'<p class="muted">Sem ocorrências pendentes.</p>'}`)}
  function reviewOccurrence(id,status){if(!['RH','Gestor'].includes(user().role))return toast('Apenas Administração/RH');const x=state.timeOccurrences.find(x=>x.id===id);x.status=status;if(status==='Aprovada'&&markTypes.includes(x.type)&&!state.timeEntries.some(e=>e.id===x.id))state.timeEntries.push({id:x.id,user:x.user,clinic:x.clinic,type:x.type,planned:x.planned,at:x.at,geo:x.geo,approved:true});x.reviewNote=$(`occ_${id}`).value;x.reviewedBy=state.currentUser;x.reviewedAt=now();audit('Ponto',`Ocorrência ${status.toLowerCase()}`,`${x.type}; ${x.reviewNote}`);persist();manageTimeOccurrences()}
  function requestTimeCorrection(){modal('Pedir correção de ponto',`<label>Marcação a corrigir</label><select id="correctionEntry">${options(state.timeEntries.filter(x=>x.user===state.currentUser),x=>x.id,x=>`${x.type} · ${fmt(x.at)}`)}</select><label>Motivo e alteração pretendida</label><textarea id="correctionReason"></textarea><button class="primary" onclick="App.saveTimeCorrection()">Enviar para aprovação</button>`)}function saveTimeCorrection(){const entry=state.timeEntries.find(x=>x.id===$('correctionEntry').value),reason=$('correctionReason').value.trim();if(!entry||!reason)return;state.timeOccurrences.push({id:uid('occ'),user:state.currentUser,clinic:entry.clinic,type:'Correção de ponto',entryId:entry.id,planned:entry.planned,at:now(),geo:entry.geo,reason,status:'Pendente'});audit('Ponto','Correção pedida',reason);persist();closeModal()}

  function renderTasks(){$('tasksContent').innerHTML=`<div class="table-wrap"><table><thead><tr><th>Nome</th><th>Fase</th><th>Clínicas</th><th>Perfil</th><th>Periodicidade / limite</th><th>Resposta / módulo</th><th>Estado</th><th></th></tr></thead><tbody>${state.tasks.map(t=>`<tr><td><b>${esc(t.name)}</b>${t.required?' <span class="pill">Obrigatória</span>':''}</td><td>${{open:'Abertura',live:'Durante o dia',close:'Fecho'}[t.phase]}</td><td>${t.clinics.includes('all')?'Todas':t.clinics.map(x=>esc(clinic(x)?.name)).join(', ')}</td><td>${esc(t.role)}</td><td>${esc(t.frequency)} · ${esc(t.deadline)}</td><td>${esc(t.response)} · ${esc(t.action)}</td><td><span class="pill ${t.active?'green':''}">${t.active?'Ativa':'Arquivada'}</span></td><td><button class="secondary" onclick="App.toggleTask('${t.id}')">${t.active?'Arquivar':'Reativar'}</button></td></tr>`).join('')}</tbody></table></div>`}
  function openTaskForm(){modal('Nova tarefa',`<div class="form-grid"><div class="span-2"><label>Nome</label><input id="tName"></div><div><label>Fase</label><select id="tPhase"><option value="open">Abertura</option><option value="live">Durante o dia</option><option value="close">Fecho</option></select></div><div><label>Obrigatória</label><select id="tRequired"><option value="1">Sim</option><option value="0">Não</option></select></div><div><label>Clínica</label><select id="tClinic"><option value="all">Todas</option>${options(clinics,x=>x.id,x=>x.name)}</select></div><div><label>Responsável / perfil</label><input id="tRole" value="Administrativa"></div><div><label>Periodicidade</label><select id="tFrequency"><option>Diária</option><option>Semanal</option><option>Mensal</option><option>Pontual</option></select></div><div><label>Hora limite</label><input id="tDeadline" type="time" value="17:00"></div><div><label>Tipo de resposta</label><select id="tResponse"><option>sim/não</option><option>número</option><option>texto</option><option>checklist</option><option>seleção de médico/técnico</option></select></div><div><label>Ação / módulo associado</label><select id="tAction"><option value="none">Sem ação</option><option value="planning">Planning</option><option value="wait">Pedidos</option><option value="confirm">Confirmações</option><option value="reval">Reavaliações</option><option value="hr">RH</option></select></div></div><button class="primary" style="margin-top:14px" onclick="App.addTask()">Criar tarefa</button>`)}
  function addTask(){const name=$('tName').value.trim();if(!name)return toast('Nome obrigatório');const t={id:uid('task'),name,phase:$('tPhase').value,required:$('tRequired').value==='1',clinics:[$('tClinic').value],role:$('tRole').value,frequency:$('tFrequency').value,deadline:$('tDeadline').value,response:$('tResponse').value,action:$('tAction').value,active:true};state.tasks.push(t);audit('Configuração','Tarefa criada',t.name);persist();closeModal()}
  function toggleTask(id){const t=state.tasks.find(x=>x.id===id);t.active=!t.active;audit('Configuração',t.active?'Tarefa reativada':'Tarefa arquivada',t.name);persist()}
  function renderAudit(){$('auditContent').innerHTML=`<div class="card">${state.audit.map(a=>`<div class="audit-line"><span>${fmt(a.at)}</span><span><b>${esc(user(a.by).name)}</b><br><span class="pill">${esc(a.module)}</span></span><span><b>${esc(a.action)}</b><br><span class="meta">${esc(a.detail)}</span></span></div>`).join('')||'<p class="muted">A demonstração ainda não tem ações registadas.</p>'}</div>`}
  function showView(id){syncState();if(window.RoleAccessAdminV4&&!RoleAccessAdminV4.guard(id))return;document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.id===id));document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===id));$('nav').classList.remove('open');if(id==='chat')renderChat()}
  function resetDemo(){if(!confirm('Repor todos os dados de demonstração?'))return;state=seed();audit('Sistema','Dados de demonstração repostos','');persist();toast('Demonstração reposta')}
  function init(){load();document.querySelectorAll('[data-view]').forEach(b=>b.addEventListener('click',()=>showView(b.dataset.view)));$('menuBtn').onclick=()=>$('nav').classList.toggle('open');$('currentUser').onchange=e=>{state.currentUser=e.target.value;audit('Sessão','Utilizador de teste alterado',user().name);persist()};renderAll()}
  document.addEventListener('DOMContentLoaded',init);
  return {setPhase,addProfessional,removeProfessional,updateProfessional,saveOpening,saveClosing,setTask,openTaskAction,finishTaskAction,attemptClose,authorizedException,confirmException,openRequestForm,refreshRequestSpecialties,refreshRequestDoctors,addRequest,openRequest,updateRequest,newConversation,createConversation,selectConversation,sendMessage,startRequestChat,openCandidateForm,addCandidate,openCandidate,saveCandidate,archiveCandidate,manageContracts,addContractType,addContractItem,toggleContract,openTaskForm,addTask,toggleTask,resetDemo,saveIndicators,finishIndicatorTask,uploadDocument,submitDocument,reviewDocument,manageJobRoles,addJobRole,saveJobRole,toggleJobRole,saveContract,saveContractItem,prepareClock,confirmClock,temporaryExit,confirmTemporary,manageTimeOccurrences,reviewOccurrence,requestTimeCorrection,saveTimeCorrection};
})();
