/* Grupo Saúde V4 — camada de dados local substituível por um adapter de API. */
const App = (() => {
  'use strict';
  const KEY = 'grupo_saude_v4_demo_2';
  const MANUAL_INDICATOR_SOURCE = 'manual';
  const $ = id => document.getElementById(id);
  const now = () => new Date().toISOString();
  const today = () => now().slice(0, 10);
  const esc = value => String(value ?? '').replace(/[&<>'"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  const uid = prefix => `${prefix}_${Date.now()}_${Math.random().toString(36).slice(2, 7)}`;
  const fmt = iso => new Intl.DateTimeFormat('pt-PT', {dateStyle:'short', timeStyle:'short'}).format(new Date(iso));
  const clinics = [
    {id:'c1', name:'Clínica Central', lat:38.7223, lng:-9.1393, radius:250, specialties:{Fisioterapia:['Dra. Ana Silva','Dr. Luís Costa'], Fisiatria:['Dr. Rui Matos'], Osteopatia:['Dra. Sara Reis']}, therapists:['Terapeuta Rita Neves','Terapeuta João Martins']},
    {id:'c2', name:'Clínica Norte', lat:41.1579, lng:-8.6291, radius:250, specialties:{Fisioterapia:['Dr. Tiago Luz'], Psicologia:['Dra. Inês Melo'], Nutrição:['Dra. Marta Dias']}, therapists:['Terapeuta Sofia Pinto','Terapeuta Bruno Reis']},
    {id:'c3', name:'Clínica Sul', lat:38.5244, lng:-8.8882, radius:250, specialties:{Fisioterapia:['Dra. Ana Silva','Dr. Pedro Sá'], Fisiatria:['Dra. Eva Lima']}, therapists:['Terapeuta Carla Nunes','Terapeuta Miguel Vaz']}
  ];
  const users = [
    {id:'u1', name:'Marta Ferreira', role:'Administrativa', clinic:'c1', canChangeClinic:true, schedule:['09:00','13:00','14:00','18:00']},
    {id:'u2', name:'Joana Lopes', role:'Administrativa', clinic:'c2', canChangeClinic:false, schedule:['09:00','13:00','14:00','18:00']},
    {id:'u3', name:'Paulo Rocha', role:'Gestor', clinic:'c1', canChangeClinic:true, schedule:['09:00','13:00','14:00','18:00']},
    {id:'u4', name:'Sofia Martins', role:'RH', clinic:'c1', canChangeClinic:true, schedule:['09:00','13:00','14:00','18:00']}
  ];
  const requestStages = ['Novo pedido','Por contactar','Contactado','A aguardar vaga','Proposta de consulta','Marcado'];
  const indicatorDefs=[{id:'consultations',label:'Consultas a trabalhar/marcar'},{id:'waitClicloud',label:'Lista de Espera Clicloud'},{id:'suspended',label:'Suspensos'},{id:'revals',label:'Reavaliações'},{id:'confirmations',label:'Consultas por confirmar'},{id:'internalQueue',label:'Lista interna de pedidos'}];
  const candidateStages = ['Candidato','Contacto','Entrevista','Proposta','Documentação','Contratação/Admissão','Ativo'];
  const baseTasks = [
    {id:'open_team',name:'Registar consultas e vagas por profissional',phase:'open',required:true,clinics:['all'],role:'Administrativa',frequency:'Diária',deadline:'09:30',response:'profissionais',action:'agenda',active:true},
    {id:'open_counts',name:'Registar Lista de Espera Clicloud',phase:'open',required:true,clinics:['all'],role:'Administrativa',frequency:'Diária',deadline:'09:30',response:'número',action:'wait',active:true},
    {id:'open_suspended',name:'Registar suspensos',phase:'open',required:true,clinics:['all'],role:'Administrativa',frequency:'Diária',deadline:'09:30',response:'número',action:'suspended',active:true},
    {id:'planning',name:'Preencher vagas existentes (Planning)',phase:'live',required:true,clinics:['all'],role:'Administrativa',frequency:'Diária',deadline:'12:00',response:'ação',action:'planning',active:true},
    {id:'waitcalls',name:'Trabalhar Lista de Espera Clicloud',phase:'live',required:false,clinics:['all'],role:'Call center',frequency:'Diária',deadline:'17:00',response:'ação',action:'wait',active:true},
    {id:'suspendedcalls',name:'Trabalhar utentes suspensos',phase:'live',required:false,clinics:['all'],role:'Administrativa',frequency:'Diária',deadline:'17:00',response:'ação',action:'suspended',active:true},
    {id:'confirm',name:'Confirmar consultas do dia seguinte',phase:'live',required:true,clinics:['all'],role:'Administrativa',frequency:'Diária',deadline:'16:00',response:'ação',action:'confirm',active:true},
    {id:'revalcalls',name:'Contactar utentes para reavaliação',phase:'live',required:true,clinics:['all'],role:'Administrativa',frequency:'Diária',deadline:'17:00',response:'ação',action:'reval',active:true},
    {id:'close_consults',name:'Registar resultado das consultas por médico',phase:'close',required:true,clinics:['all'],role:'Administrativa',frequency:'Diária',deadline:'19:00',response:'profissionais',action:'agenda',active:true},
    {id:'close_counts',name:'Confirmar Lista de Espera Clicloud final',phase:'close',required:true,clinics:['all'],role:'Administrativa',frequency:'Diária',deadline:'19:00',response:'número',action:'wait',active:true},
    {id:'close_suspended',name:'Confirmar suspensos finais',phase:'close',required:true,clinics:['all'],role:'Administrativa',frequency:'Diária',deadline:'19:00',response:'número',action:'suspended',active:true}
  ];
  function seed(){const t=today(),y=new Date(Date.now()-86400000).toISOString().slice(0,10);return {version:4,currentUser:'u1',opClinic:'c1',opDate:t,opPhase:'open',tasks:baseTasks,days:{[`${t}_c1`]:{date:t,clinic:'c1',closed:false,exception:null,taskStatus:{},open:{professionals:[{name:'Dra. Ana Silva',kind:'doctor',selected:true,consults:8,slots:0},{name:'Dr. Luís Costa',kind:'doctor',selected:true,consults:6,slots:0},{name:'Terapeuta Rita Neves',kind:'therapist',selected:true,consults:7,slots:2}],saved:false},close:{professionals:[],saved:false},appointments:[]}},requests:[{id:'r1',created:`${y}T09:15:00Z`,clinic:'c1',specialty:'Fisioterapia',doctor:'Dra. Ana Silva',name:'Carla Sousa',phone:'910 000 101',notes:'Prefere manhã',stage:'A aguardar vaga',owner:'u1',history:[]}],conversations:[],jobRoles:[{id:'jr1',name:'Fisioterapeuta',active:true},{id:'jr2',name:'Administrativa',active:true}],contractTypes:[],candidates:[],timeEntries:[],timeOccurrences:[],internalQueue:[],audit:[]}}
  let state;
  function load(){try{state=JSON.parse(localStorage.getItem(KEY))||seed()}catch{state=seed()}migrate()}
  function migrate(){state.audit||=[];state.tasks||=baseTasks;state.days||={};state.requests||=[];state.conversations||=[];state.jobRoles||=[];state.contractTypes||=[];state.candidates||=[];state.timeEntries||=[];state.timeOccurrences||=[];state.internalQueue||=[];Object.values(state.days).forEach(d=>{d.indicators||={};indicatorDefs.forEach(def=>d.indicators[def.id]||=( {source:MANUAL_INDICATOR_SOURCE,opening:null,current:0,closing:null,history:[]}));d.open||={professionals:[],saved:false};d.close||={professionals:[],saved:false}});persist(false)}
  function persist(render=true){localStorage.setItem(KEY,JSON.stringify(state));if(render)renderAll()}
  function user(id=state.currentUser){return users.find(x=>x.id===id)||users[0]}
  function clinic(id){return clinics.find(x=>x.id===id)}
  function audit(module,action,detail=''){state.audit.unshift({id:uid('log'),at:now(),by:state.currentUser,module,action,detail})}
  function toast(message){const el=$('toast');if(!el)return;el.textContent=message;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2200)}
  function options(items,value=x=>x,label=x=>x){return items.map(x=>`<option value="${esc(value(x))}">${esc(label(x))}</option>`).join('')}
  function modal(title,body){$('modalTitle').textContent=title;$('modalBody').innerHTML=`<div class="modal-body">${body}</div>`;$('modal').showModal()}
  function closeModal(){$('modal').close()}
  function day(){const key=`${state.opDate}_${state.opClinic}`;if(!state.days[key]){const indicators={};indicatorDefs.forEach(x=>indicators[x.id]={source:MANUAL_INDICATOR_SOURCE,opening:null,current:0,closing:null,history:[]});state.days[key]={date:state.opDate,clinic:state.opClinic,closed:false,taskStatus:{},open:{professionals:[],saved:false},close:{professionals:[],saved:false},indicators,appointments:[]}}return state.days[key]}
  function professionalsForClinic(kind){const c=clinic(state.opClinic);if(!c)return[];return kind==='doctor'?[...new Set(Object.values(c.specialties).flat())]:(c.therapists||[])}
  function professionalSelect(p,index,close,kind){const allowed=professionalsForClinic(kind),current=allowed.includes(p.name)?p.name:'';return `<select onchange="App.updateProfessional(${index},'name',this.value,${close})"><option value="">Selecionar…</option>${allowed.map(name=>`<option value="${esc(name)}" ${name===current?'selected':''}>${esc(name)}</option>`).join('')}</select>`}
  function professionalRows(d,close=false,kind='doctor'){const all=close?d.close.professionals:d.open.professionals,rows=all.map((p,index)=>({p,index})).filter(x=>x.p.kind===kind);if(!rows.length)return '<p class="muted">Ainda não existem profissionais. Adicione através da lista.</p>';return `<div class="table-wrap"><table><thead><tr><th>${kind==='doctor'?'Médico':'Técnico / terapeuta'}</th>${close?'<th>Realizadas</th><th>Faltas</th><th>Reagendadas</th><th>Canceladas</th>':'<th>Tem consulta</th><th>Consultas</th>'}${kind==='therapist'?'<th>Vagas amanhã</th>':''}<th></th></tr></thead><tbody>${rows.map(({p,index})=>`<tr><td>${professionalSelect(p,index,close,kind)}</td>${close?['done','missed','rescheduled','cancelled'].map(k=>`<td><input type="number" min="0" value="${p[k]||0}" onchange="App.updateProfessional(${index},'${k}',this.value,true)"></td>`).join(''):`<td><input type="checkbox" ${p.selected?'checked':''} onchange="App.updateProfessional(${index},'selected',this.checked,false)"></td><td><input type="number" min="0" value="${p.consults||0}" onchange="App.updateProfessional(${index},'consults',this.value,false)"></td>`}${kind==='therapist'?`<td><input type="number" min="0" value="${p.slots||0}" onchange="App.updateProfessional(${index},'slots',this.value,${close})"></td>`:''}<td><button class="danger" onclick="App.removeProfessional(${index},${close})">×</button></td></tr>`).join('')}</tbody></table></div>`}
  function renderAll(){renderUsers();renderDashboard();renderOperation();renderRequests();renderChat();renderHr();renderTasks();renderAudit();updateUnread()}
  function renderUsers(){const el=$('currentUser'),old=state.currentUser;el.innerHTML=options(users,x=>x.id,x=>`${x.name} · ${x.role}`);el.value=old}
  function renderDashboard(){const todays=Object.values(state.days).filter(d=>d.date===today());$('dashboardContent').innerHTML=`<div class="cards"><div class="card"><div class="muted">Clínicas em operação</div><div class="metric">${clinics.length-todays.filter(d=>d.closed).length}</div></div><div class="card"><div class="muted">Novos pedidos hoje</div><div class="metric">${state.requests.filter(r=>r.created.slice(0,10)===today()).length}</div></div></div>`}
  function indicatorFields(d,prefix,phase){return indicatorDefs.map(x=>{const e=d.indicators[x.id],v=phase==='abertura'?(e.opening??e.current):phase==='fecho'?(e.closing??e.current):e.current;return `<div><label>${esc(x.label)}</label><input id="${prefix}_${x.id}" type="number" min="0" value="${v}"></div>`}).join('')}
  function renderOperation(){const d=day();$('operationContent').innerHTML=`<div class="card"><div class="form-grid"><div><label>Clínica</label><select id="opClinic">${options(clinics,x=>x.id,x=>x.name)}</select></div><div><label>Data</label><input id="opDate" type="date" value="${state.opDate}"></div></div></div><div class="tabs"><button class="${state.opPhase==='open'?'on':''}" onclick="App.setPhase('open')">Abertura</button><button class="${state.opPhase==='live'?'on':''}" onclick="App.setPhase('live')">Durante o dia</button><button class="${state.opPhase==='close'?'on':''}" onclick="App.setPhase('close')">Fecho</button></div>${state.opPhase==='open'?openingPanel(d):state.opPhase==='close'?closingPanel(d):`<div class="card"><h3>Indicadores atuais</h3><div class="form-grid">${indicatorFields(d,'current','atualização')}</div><button class="primary" onclick="App.saveIndicators('atualização')">Guardar</button></div>`}`;$('opClinic').value=state.opClinic;$('opClinic').onchange=e=>{state.opClinic=e.target.value;persist()};$('opDate').onchange=e=>{state.opDate=e.target.value;persist()}}
  function openingPanel(d){return `<div class="card"><div class="actions" style="justify-content:space-between"><h3>Médicos com consulta</h3><button class="secondary" onclick="App.addProfessional(false,'doctor')">+ Médico</button></div>${professionalRows(d,false,'doctor')}<div class="actions" style="justify-content:space-between;margin-top:20px"><h3>Técnicos / terapeutas</h3><button class="secondary" onclick="App.addProfessional(false,'therapist')">+ Técnico/terapeuta</button></div>${professionalRows(d,false,'therapist')}<h3>Indicadores</h3><div class="form-grid">${indicatorFields(d,'open','abertura')}</div><button class="primary" onclick="App.saveIndicators('abertura')">Guardar abertura</button></div>`}
  function closingPanel(d){return `<div class="card"><h3>Resultados por profissional</h3><h3>Médicos</h3>${professionalRows(d,true,'doctor')}<button class="secondary" onclick="App.addProfessional(true,'doctor')">+ Médico</button><h3>Técnicos / terapeutas</h3>${professionalRows(d,true,'therapist')}<button class="secondary" onclick="App.addProfessional(true,'therapist')">+ Técnico/terapeuta</button><h3>Indicadores de fecho</h3><div class="form-grid">${indicatorFields(d,'close','fecho')}</div><button class="primary" onclick="App.saveIndicators('fecho')">Guardar fecho</button></div>`}
  function setPhase(p){state.opPhase=p;persist()}
  function addProfessional(close,kind){const arr=close?day().close.professionals:day().open.professionals,allowed=professionalsForClinic(kind),used=new Set(arr.filter(x=>x.kind===kind).map(x=>x.name)),name=allowed.find(x=>!used.has(x))||'';arr.push(close?{name,kind,done:0,missed:0,rescheduled:0,cancelled:0,slots:0}:{name,kind,selected:true,consults:0,slots:0});persist()}
  function removeProfessional(i,close){(close?day().close.professionals:day().open.professionals).splice(i,1);persist()}
  function updateProfessional(i,k,v,close){const p=(close?day().close.professionals:day().open.professionals)[i];if(k==='name'){const allowed=professionalsForClinic(p.kind);if(v&&!allowed.includes(v)){toast('Profissional inválido para esta clínica');return}p.name=v}else p[k]=k==='selected'?v:+v;persist(false)}
  function recordIndicator(d,type,value,phase){const e=d.indicators[type];if(phase==='abertura')e.opening=value;if(phase==='fecho')e.closing=value;e.current=value;e.history.push({at:now(),by:state.currentUser,value,phase})}
  function saveIndicators(phase){const d=day(),prefix=phase==='abertura'?'open':phase==='fecho'?'close':'current';indicatorDefs.forEach(x=>recordIndicator(d,x.id,+$(`${prefix}_${x.id}`).value,phase));audit('Indicadores',`Valores de ${phase} guardados`,`${d.date}/${d.clinic}`);persist();toast('Valores guardados')}
  function openRequestForm(){const u=user();modal('Novo pedido',`<div class="form-grid"><div><label>Clínica pretendida</label><select id="rClinic" onchange="App.refreshRequestSpecialties()" ${!u.canChangeClinic?'disabled':''}>${options(clinics,x=>x.id,x=>x.name)}</select></div><div><label>Especialidade</label><select id="rSpecialty" onchange="App.refreshRequestDoctors()"></select></div><div><label>Médico</label><select id="rDoctor"></select></div><div><label>Nome</label><input id="rName"></div><div><label>Telefone</label><input id="rPhone"></div></div><button class="primary" onclick="App.addRequest()">Criar pedido</button>`);$('rClinic').value=u.clinic;refreshRequestSpecialties()}
  function refreshRequestSpecialties(){const c=clinic($('rClinic').value);$('rSpecialty').innerHTML=options(Object.keys(c.specialties));refreshRequestDoctors()}
  function refreshRequestDoctors(){const c=clinic($('rClinic').value),spec=$('rSpecialty').value;$('rDoctor').innerHTML=options(c.specialties[spec]||[])}
  function addRequest(){const c=clinic($('rClinic').value),spec=$('rSpecialty').value,doctor=$('rDoctor').value;if(!c?.specialties[spec]?.includes(doctor))return toast('Selecione um médico válido');if(!$('rName').value.trim()||!$('rPhone').value.trim())return toast('Nome e contacto são obrigatórios');state.requests.push({id:uid('r'),created:now(),clinic:c.id,specialty:spec,doctor,name:$('rName').value.trim(),phone:$('rPhone').value.trim(),notes:'',stage:'Novo pedido',owner:state.currentUser,history:[]});persist();closeModal();toast('Pedido criado')}
  function renderRequests(){$('waitContent').innerHTML=`<button class="primary" onclick="App.openRequestForm()">+ Novo pedido</button><div class="funnel">${requestStages.map(stage=>`<div class="funnel-col"><div class="funnel-head"><span>${stage}</span><span>${state.requests.filter(r=>r.stage===stage).length}</span></div>${state.requests.filter(r=>r.stage===stage).map(r=>`<div class="funnel-card"><b>${esc(r.name)}</b><div class="meta">${esc(clinic(r.clinic)?.name)} · ${esc(r.specialty)} · ${esc(r.doctor)}</div></div>`).join('')}</div>`).join('')}</div>`}
  function renderChat(){$('chatContent').innerHTML='<div class="card"><p class="muted">Chat interno disponível na próxima iteração.</p></div>'}
  function renderHr(){$('hrContent').innerHTML='<div class="card"><p class="muted">Módulo RH preservado para desenvolvimento incremental.</p></div>'}
  function renderTasks(){$('tasksContent').innerHTML='<div class="card"><p class="muted">Configuração de tarefas preservada.</p></div>'}
  function renderAudit(){$('auditContent').innerHTML=`<div class="card">${state.audit.map(a=>`<div class="audit-line"><span>${fmt(a.at)}</span><b>${esc(a.module)}</b><span>${esc(a.action)}</span></div>`).join('')||'<p class="muted">Sem ações.</p>'}</div>`}
  function updateUnread(){if($('unread'))$('unread').textContent='';if($('navUnread'))$('navUnread').textContent=''}
  function showView(id){document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.id===id));document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===id));$('nav').classList.remove('open')}
  function resetDemo(){if(!confirm('Repor todos os dados de demonstração?'))return;state=seed();persist()}
  function init(){load();document.querySelectorAll('[data-view]').forEach(b=>b.addEventListener('click',()=>showView(b.dataset.view)));$('menuBtn').onclick=()=>$('nav').classList.toggle('open');$('currentUser').onchange=e=>{state.currentUser=e.target.value;persist()};renderAll()}
  document.addEventListener('DOMContentLoaded',init);
  return {setPhase,addProfessional,removeProfessional,updateProfessional,saveIndicators,openRequestForm,refreshRequestSpecialties,refreshRequestDoctors,addRequest,resetDemo};
})();
