/* Grupo Saúde V4 — camada de dados local substituível por um adapter de API. */
const App = (() => {
  'use strict';
  const KEY = 'grupo_saude_v4_demo_2';
  const $ = id => document.getElementById(id);
  const now = () => new Date().toISOString();
  const today = () => now().slice(0, 10);
  const esc = value => String(value ?? '').replace(/[&<>'"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  const uid = prefix => `${prefix}_${Date.now()}_${Math.random().toString(36).slice(2, 7)}`;
  const fmt = iso => new Intl.DateTimeFormat('pt-PT', {dateStyle:'short', timeStyle:'short'}).format(new Date(iso));
  const clinics = [
    {id:'c1', name:'Clínica Central', specialties:{Fisioterapia:['Dra. Ana Silva','Dr. Luís Costa'], Fisiatria:['Dr. Rui Matos'], Osteopatia:['Dra. Sara Reis']}},
    {id:'c2', name:'Clínica Norte', specialties:{Fisioterapia:['Dr. Tiago Luz'], Psicologia:['Dra. Inês Melo'], Nutrição:['Dra. Marta Dias']}},
    {id:'c3', name:'Clínica Sul', specialties:{Fisioterapia:['Dra. Ana Silva','Dr. Pedro Sá'], Fisiatria:['Dra. Eva Lima']}}
  ];
  const users = [
    {id:'u1', name:'Marta Ferreira', role:'Administrativa', clinic:'c1', canChangeClinic:true},
    {id:'u2', name:'Joana Lopes', role:'Administrativa', clinic:'c2', canChangeClinic:false},
    {id:'u3', name:'Paulo Rocha', role:'Gestor', clinic:'c1', canChangeClinic:true},
    {id:'u4', name:'Sofia Martins', role:'RH', clinic:'c1', canChangeClinic:true}
  ];
  const requestStages = ['Novo pedido','Por contactar','Contactado','A aguardar vaga','Proposta de consulta','Marcado'];
  const candidateStages = ['Candidato','Contacto','Entrevista','Proposta','Documentação','Contratação/Admissão','Ativo'];
  const baseTasks = [
    {id:'open_team',name:'Registar consultas e vagas por profissional',phase:'open',required:true,clinics:['all'],role:'Administrativa',frequency:'Diária',deadline:'09:30',response:'profissionais',action:'agenda',active:true},
    {id:'open_counts',name:'Registar lista de espera, suspensos e reavaliações',phase:'open',required:true,clinics:['all'],role:'Administrativa',frequency:'Diária',deadline:'09:30',response:'número',action:'pedidos',active:true},
    {id:'planning',name:'Preencher vagas existentes (Planning)',phase:'live',required:true,clinics:['all'],role:'Administrativa',frequency:'Diária',deadline:'12:00',response:'ação',action:'planning',active:true},
    {id:'waitcalls',name:'Trabalhar lista de espera / suspensos',phase:'live',required:false,clinics:['all'],role:'Call center',frequency:'Diária',deadline:'17:00',response:'ação',action:'wait',active:true},
    {id:'confirm',name:'Confirmar consultas do dia seguinte',phase:'live',required:true,clinics:['all'],role:'Administrativa',frequency:'Diária',deadline:'16:00',response:'ação',action:'confirm',active:true},
    {id:'revalcalls',name:'Contactar utentes para reavaliação',phase:'live',required:true,clinics:['all'],role:'Administrativa',frequency:'Diária',deadline:'17:00',response:'ação',action:'reval',active:true},
    {id:'close_consults',name:'Registar resultado das consultas por médico',phase:'close',required:true,clinics:['all'],role:'Administrativa',frequency:'Diária',deadline:'19:00',response:'profissionais',action:'agenda',active:true},
    {id:'close_counts',name:'Confirmar valores finais e vagas de amanhã',phase:'close',required:true,clinics:['all'],role:'Administrativa',frequency:'Diária',deadline:'19:00',response:'número',action:'resumo',active:true}
  ];

  function seed() {
    const t = today();
    const yesterday = new Date(Date.now()-86400000).toISOString().slice(0,10);
    return {
      version:2, currentUser:'u1', opClinic:'c1', opDate:t, opPhase:'open', tasks:baseTasks,
      days:{[`${t}_c1`]:{date:t,clinic:'c1',closed:false,exception:null,taskStatus:{},open:{professionals:[{name:'Dra. Ana Silva',selected:true,consults:8,slots:2},{name:'Dr. Luís Costa',selected:true,consults:6,slots:1}],wait:5,suspended:2,revals:2,saved:false},close:{professionals:[{name:'Dra. Ana Silva',done:0,missed:0,rescheduled:0,cancelled:0,slots:0},{name:'Dr. Luís Costa',done:0,missed:0,rescheduled:0,cancelled:0,slots:0}],wait:0,suspended:0,revals:0,saved:false},appointments:[{id:'a1',patient:'Alice Santos',doctor:'Dra. Ana Silva',time:'09:00',status:'Por confirmar'},{id:'a2',patient:'Manuel Pires',doctor:'Dr. Luís Costa',time:'10:30',status:'Por confirmar'}]}},
      requests:[
        {id:'r1',created:`${yesterday}T09:15:00Z`,clinic:'c1',specialty:'Fisioterapia',doctor:'Dra. Ana Silva',name:'Carla Sousa',phone:'910 000 101',notes:'Prefere manhã',stage:'A aguardar vaga',owner:'u1',history:[]},
        {id:'r2',created:`${t}T08:40:00Z`,clinic:'c1',specialty:'Fisiatria',doctor:'Dr. Rui Matos',name:'José Ramos',phone:'910 000 202',notes:'Reavaliação após 9.º tratamento',stage:'Por contactar',owner:'u1',history:[]},
        {id:'r3',created:`${t}T10:10:00Z`,clinic:'c2',specialty:'Psicologia',doctor:'Dra. Inês Melo',name:'Leonor Vaz',phone:'910 000 303',notes:'Primeira consulta',stage:'Novo pedido',owner:'u2',history:[]},
        {id:'r4',created:`${yesterday}T11:00:00Z`,clinic:'c1',specialty:'Osteopatia',doctor:'Dra. Sara Reis',name:'Nuno Alves',phone:'910 000 404',notes:'',stage:'Marcado',owner:'u1',completed:`${t}T11:20:00Z`,history:[]}
      ],
      conversations:[{id:'cv1',title:'Vaga urgente — Carla Sousa',members:['u1','u2','u3'],requestId:'r1',messages:[{id:'m1',from:'u2',at:`${t}T09:12:00Z`,text:'Existe possibilidade de transferência para a Clínica Norte?',readBy:['u2']},{id:'m2',from:'u3',at:`${t}T09:25:00Z`,text:'Vou confirmar com a equipa clínica.',readBy:['u3','u1']}]}],
      contractTypes:[{id:'ct1',name:'Contrato sem termo',active:true,items:[{id:'i1',name:'Contrato assinado',required:true},{id:'i2',name:'Documento de identificação',required:true},{id:'i3',name:'IBAN',required:true}]},{id:'ct2',name:'Prestação de serviços',active:true,items:[{id:'i4',name:'Contrato de prestação',required:true},{id:'i5',name:'Cédula profissional',required:true},{id:'i6',name:'Seguro profissional',required:true}]}],
      candidates:[{id:'p1',name:'Beatriz Freitas',email:'beatriz@example.pt',phone:'930 000 111',role:'Fisioterapeuta',clinic:'c1',contract:'ct2',stage:'Documentação',notes:'Entrada prevista este mês',active:true,checks:{i4:{delivered:true,validated:true,by:'u4',at:now()},i5:{delivered:true,validated:false,by:'u4',at:now()},i6:{delivered:false,validated:false}},history:[]}],
      timeEntries:[{id:'te1',user:'u1',at:now(),type:'Entrada',geo:'38.7223, -9.1393',signature:'Marta Ferreira'}],
      audit:[]
    };
  }
  let state;
  function load(){ try { state=JSON.parse(localStorage.getItem(KEY)) || seed(); } catch { state=seed(); } migrate(); }
  function migrate(){ if(!state.audit) state.audit=[]; if(!state.tasks) state.tasks=baseTasks; persist(false); }
  function persist(render=true){ localStorage.setItem(KEY,JSON.stringify(state)); if(render) renderAll(); }
  function user(id=state.currentUser){ return users.find(x=>x.id===id) || users[0]; }
  function clinic(id){ return clinics.find(x=>x.id===id); }
  function audit(module, action, detail='') { state.audit.unshift({id:uid('log'),at:now(),by:state.currentUser,module,action,detail}); }
  function toast(message){ const el=$('toast'); el.textContent=message; el.classList.add('show'); setTimeout(()=>el.classList.remove('show'),2200); }
  function options(items,value,label=x=>x){ return items.map(x=>`<option value="${esc(value(x))}">${esc(label(x))}</option>`).join(''); }
  function modal(title, body){ $('modalTitle').textContent=title; $('modalBody').innerHTML=`<div class="modal-body">${body}</div>`; $('modal').showModal(); }
  function closeModal(){ $('modal').close(); }
  function day(){ const key=`${state.opDate}_${state.opClinic}`; if(!state.days[key]) state.days[key]={date:state.opDate,clinic:state.opClinic,closed:false,exception:null,taskStatus:{},open:{professionals:[],wait:0,suspended:0,revals:0,saved:false},close:{professionals:[],wait:0,suspended:0,revals:0,saved:false},appointments:[]}; return state.days[key]; }
  function taskList(phase){ return state.tasks.filter(t=>t.active&&t.phase===phase&&(t.clinics.includes('all')||t.clinics.includes(state.opClinic))); }

  function renderAll(){ renderUsers(); renderDashboard(); renderOperation(); renderRequests(); renderChat(); renderHr(); renderTasks(); renderAudit(); updateUnread(); }
  function renderUsers(){ const el=$('currentUser'), old=state.currentUser; el.innerHTML=options(users,x=>x.id,x=>`${x.name} · ${x.role}`); el.value=old; }
  function renderDashboard(){
    const todays=Object.values(state.days).filter(d=>d.date===today()); const allTasks=todays.flatMap(d=>Object.values(d.taskStatus)); const done=allTasks.filter(x=>x.status==='done').length;
    const newToday=state.requests.filter(r=>r.created.slice(0,10)===today()).length, marked=state.requests.filter(r=>r.stage==='Marcado').length;
    $('dashboardContent').innerHTML=`<div class="cards"><div class="card"><div class="muted">Execução de tarefas</div><div class="metric green">${allTasks.length?Math.round(done/allTasks.length*100):0}%</div><div class="meta">${done} de ${allTasks.length} registos</div></div><div class="card"><div class="muted">Novos pedidos hoje</div><div class="metric">${newToday}</div><div class="meta">Em todas as clínicas</div></div><div class="card"><div class="muted">Pedidos marcados</div><div class="metric green">${marked}</div><div class="meta">Total da demonstração</div></div><div class="card"><div class="muted">Clínicas fechadas</div><div class="metric">${todays.filter(d=>d.closed).length} / ${clinics.length}</div><div class="meta">No dia de hoje</div></div></div><div class="card"><h3>Estado operacional por clínica</h3>${clinics.map(c=>{const d=state.days[`${today()}_${c.id}`], tasks=d?Object.values(d.taskStatus):[], complete=tasks.filter(x=>x.status==='done').length, pct=tasks.length?Math.round(complete/tasks.length*100):0;return `<div style="padding:9px 0"><div class="actions" style="justify-content:space-between"><b>${esc(c.name)}</b><span class="pill ${d?.closed?'green':'orange'}">${d?.closed?'Fechada':'Em operação'} · ${pct}%</span></div><div class="kpi-bar"><span style="width:${pct}%"></span></div></div>`}).join('')}</div>`;
  }

  function renderOperation(){
    const d=day(), phases={open:'Abertura',live:'Durante o dia',close:'Fecho'};
    $('operationContent').innerHTML=`<div class="card"><div class="form-grid"><div><label>Clínica</label><select id="opClinic">${options(clinics,x=>x.id,x=>x.name)}</select></div><div><label>Data</label><input id="opDate" type="date" value="${state.opDate}"></div><div><label>Responsável</label><input value="${esc(user().name)}" disabled></div><div><label>Estado</label><div class="pill ${d.closed?'green':'orange'}">${d.closed?'Dia fechado':'Em operação'}</div></div></div></div><div class="tabs">${Object.entries(phases).map(([k,v])=>`<button class="${state.opPhase===k?'on':''}" onclick="App.setPhase('${k}')">${v}</button>`).join('')}</div><div id="phasePanel">${state.opPhase==='open'?openingPanel(d):state.opPhase==='live'?livePanel(d):closingPanel(d)}</div>`;
    $('opClinic').value=state.opClinic; $('opClinic').onchange=e=>{state.opClinic=e.target.value;persist()}; $('opDate').onchange=e=>{state.opDate=e.target.value;persist()};
  }
  function professionalRows(d, close=false){
    const rows=close?d.close.professionals:d.open.professionals;
    if(!rows.length) return '<p class="muted">Ainda não existem profissionais. Adicione os que têm consulta.</p>';
    return `<div class="table-wrap"><table><thead><tr><th>Profissional</th>${close?'<th>Realizadas</th><th>Faltas</th><th>Reagendadas</th><th>Canceladas</th>':'<th>Tem consulta</th><th>Consultas</th>'}<th>Vagas amanhã</th><th></th></tr></thead><tbody>${rows.map((p,i)=>`<tr><td><input value="${esc(p.name)}" onchange="App.updateProfessional(${i},'name',this.value,${close})"></td>${close?['done','missed','rescheduled','cancelled'].map(k=>`<td><input type="number" min="0" value="${p[k]||0}" onchange="App.updateProfessional(${i},'${k}',this.value,true)"></td>`).join(''):`<td><input type="checkbox" ${p.selected?'checked':''} onchange="App.updateProfessional(${i},'selected',this.checked,false)"></td><td><input type="number" min="0" value="${p.consults||0}" onchange="App.updateProfessional(${i},'consults',this.value,false)"></td>`}<td><input type="number" min="0" value="${p.slots||0}" onchange="App.updateProfessional(${i},'slots',this.value,${close})"></td><td><button class="danger" onclick="App.removeProfessional(${i},${close})">×</button></td></tr>`).join('')}</tbody></table></div>`;
  }
  function openingPanel(d){ return `<div class="card"><div class="actions" style="justify-content:space-between"><h3>Consultas e vagas por médico/técnico</h3><button class="secondary" onclick="App.addProfessional(false)">+ Profissional</button></div>${professionalRows(d)}<div class="form-grid" style="margin-top:14px"><div><label>Lista de espera</label><input id="oWait" type="number" min="0" value="${d.open.wait||0}"></div><div><label>Suspensos</label><input id="oSusp" type="number" min="0" value="${d.open.suspended||0}"></div><div><label>Reavaliações</label><input id="oReval" type="number" min="0" value="${d.open.revals||0}"></div><div style="align-self:end"><button class="primary" onclick="App.saveOpening()">Guardar abertura</button></div></div>${d.open.saved?`<div class="notice ok">Guardado por <b>${esc(user(d.open.by).name)}</b> em ${fmt(d.open.at)}. A tarefa foi concluída automaticamente.</div>`:''}</div><div class="card"><h3>Tarefas de abertura</h3>${taskRows('open',d)}</div>`; }
  function taskRows(phase,d){ const list=taskList(phase); return list.map(t=>{const st=d.taskStatus[t.id]||{status:'todo'};return `<div class="task-row"><div><b>${esc(t.name)}</b> ${t.required?'<span class="pill">Obrigatória</span>':''}<div class="meta">${esc(t.deadline||'Sem limite')} · ${esc(t.role)} ${st.at?`· ${esc(user(st.by).name)}, ${fmt(st.at)}`:''}</div></div><span class="pill ${st.status==='done'?'green':st.status==='doing'?'orange':''}">${st.status==='done'?'Concluída':st.status==='doing'?'Em curso':'Por fazer'}</span><div class="actions">${phase==='live'?`<button class="primary" onclick="App.openTaskAction('${t.id}')">Abrir ação</button>`:''}<button class="secondary" onclick="App.setTask('${t.id}','${st.status==='done'?'todo':'done'}')">${st.status==='done'?'Reabrir':'Concluir'}</button></div></div>`}).join('')||'<p class="muted">Sem tarefas ativas nesta fase.</p>'; }
  function livePanel(d){ return `<div class="notice">As tarefas abrem a ação operacional correspondente. Cada resultado guarda responsável, hora e histórico; tarefas concluídas podem ser reabertas.</div><div class="card"><h3>Tarefas vivas</h3>${taskRows('live',d)}</div><div class="card"><h3>Atividade do dia</h3>${state.audit.filter(x=>x.detail.includes(`${d.date}/${d.clinic}`)).slice(0,15).map(a=>`<div class="audit-line"><span>${fmt(a.at)}</span><b>${esc(user(a.by).name)}</b><span>${esc(a.action)} — ${esc(a.detail)}</span></div>`).join('')||'<p class="muted">Sem atividade registada.</p>'}</div>`; }
  function closingPanel(d){
    const o=d.open,c=d.close; return `<div class="card"><div class="actions" style="justify-content:space-between"><h3>Resultados por médico/técnico</h3><button class="secondary" onclick="App.addProfessional(true)">+ Profissional</button></div>${professionalRows(d,true)}<div class="form-grid" style="margin-top:14px"><div><label>Lista de espera final</label><input id="cWait" type="number" min="0" value="${c.wait||0}"></div><div><label>Suspensos finais</label><input id="cSusp" type="number" min="0" value="${c.suspended||0}"></div><div><label>Reavaliações pendentes</label><input id="cReval" type="number" min="0" value="${c.revals||0}"></div><div style="align-self:end"><button class="primary" onclick="App.saveClosing()">Guardar valores finais</button></div></div><div class="notice ok"><b>Abertura → Fecho:</b> lista ${o.wait||0} → ${c.wait||0} (${delta(o.wait,c.wait)}); suspensos ${o.suspended||0} → ${c.suspended||0} (${delta(o.suspended,c.suspended)}); reavaliações ${o.revals||0} → ${c.revals||0} (${delta(o.revals,c.revals)}); vagas ${sum(o.professionals,'slots')} → ${sum(c.professionals,'slots')}.</div></div><div class="card"><h3>Tarefas de fecho</h3>${taskRows('close',d)}<div class="actions" style="margin-top:14px"><button class="primary" onclick="App.attemptClose()">${d.closed?'Reabrir dia':'Fechar dia e criar resumo'}</button>${!d.closed?'<button class="danger" onclick="App.authorizedException()">Exceção autorizada</button>':''}</div>${d.summary?`<div class="notice ok"><b>Resumo diário:</b> ${esc(d.summary)}</div>`:''}</div>`;
  }
  const sum=(arr,k)=>arr.reduce((n,x)=>n+(+x[k]||0),0); const delta=(a,b)=>`${(+b||0)-(+a||0)>=0?'+':''}${(+b||0)-(+a||0)}`;
  function setPhase(p){state.opPhase=p;persist()}
  function addProfessional(close){const d=day(), arr=close?d.close.professionals:d.open.professionals;arr.push(close?{name:'',done:0,missed:0,rescheduled:0,cancelled:0,slots:0}:{name:'',selected:true,consults:0,slots:0});persist()}
  function removeProfessional(i,close){(close?day().close.professionals:day().open.professionals).splice(i,1);persist()}
  function updateProfessional(i,k,v,close){const p=(close?day().close.professionals:day().open.professionals)[i];p[k]=k==='name'||k==='selected'?v:+v;persist(false)}
  function saveOpening(){const d=day(); d.open.wait=+$('oWait').value;d.open.suspended=+$('oSusp').value;d.open.revals=+$('oReval').value;d.open.saved=true;d.open.at=now();d.open.by=state.currentUser;d.taskStatus.open_team={status:'done',at:now(),by:state.currentUser};d.taskStatus.open_counts={status:'done',at:now(),by:state.currentUser};audit('Operação','Abertura guardada',`${d.date}/${d.clinic}`);persist();toast('Abertura guardada e tarefas concluídas')}
  function saveClosing(){const d=day();d.close.wait=+$('cWait').value;d.close.suspended=+$('cSusp').value;d.close.revals=+$('cReval').value;d.close.saved=true;d.close.at=now();d.close.by=state.currentUser;d.taskStatus.close_consults={status:'done',at:now(),by:state.currentUser};d.taskStatus.close_counts={status:'done',at:now(),by:state.currentUser};audit('Operação','Valores de fecho guardados',`${d.date}/${d.clinic}`);persist();toast('Fecho guardado e tarefas concluídas')}
  function setTask(id,status){const d=day(),old=d.taskStatus[id]?.status||'todo';d.taskStatus[id]={status,at:now(),by:state.currentUser};audit('Tarefas',status==='todo'?'Tarefa reaberta':'Tarefa concluída',`${id}: ${old} → ${status}; ${d.date}/${d.clinic}`);persist()}
  function openTaskAction(id){const d=day(), t=state.tasks.find(x=>x.id===id);d.taskStatus[id]={status:'doing',at:now(),by:state.currentUser};audit('Tarefas','Ação iniciada',`${id}; ${d.date}/${d.clinic}`);persist(false);
    if(t.action==='wait'||t.action==='reval') { showView('wait'); renderAll(); toast('Pedidos filtráveis apresentados'); return; }
    const appointments=d.appointments||[]; const rows=t.action==='confirm'?appointments.map(a=>`<tr><td>${esc(a.time)}</td><td>${esc(a.patient)}</td><td>${esc(a.doctor)}</td><td><select id="result_${a.id}"><option>Confirmada</option><option>Sem resposta</option><option>Reagendada</option><option>Cancelada</option></select></td></tr>`).join(''):d.open.professionals.filter(x=>x.slots>0).map((p,i)=>`<tr><td>${esc(p.name)}</td><td>${p.slots}</td><td><input id="fill_${i}" type="number" min="0" max="${p.slots}" value="0"></td><td><input id="note_${i}" placeholder="Resultado / observação"></td></tr>`).join('');
    modal(t.name,`<div class="table-wrap"><table><thead><tr>${t.action==='confirm'?'<th>Hora</th><th>Utente</th><th>Médico</th><th>Resultado</th>':'<th>Profissional</th><th>Vagas</th><th>Preenchidas</th><th>Resultado</th>'}</tr></thead><tbody>${rows||'<tr><td colspan="4">Sem registos para trabalhar.</td></tr>'}</tbody></table></div><div class="actions" style="margin-top:14px"><button class="primary" onclick="App.finishTaskAction('${id}')">Guardar resultados e concluir</button></div>`); }
  function finishTaskAction(id){const d=day(),t=state.tasks.find(x=>x.id===id);if(t.action==='confirm') (d.appointments||[]).forEach(a=>a.status=$(`result_${a.id}`)?.value||a.status);d.taskStatus[id]={status:'done',at:now(),by:state.currentUser};audit('Tarefas','Resultados registados',`${t.name}; ${d.date}/${d.clinic}`);persist();closeModal();toast('Resultados guardados')}
  function attemptClose(){const d=day();if(d.closed){d.closed=false;audit('Operação','Dia reaberto',`${d.date}/${d.clinic}`);persist();return}const pending=[...taskList('live'),...taskList('close')].filter(t=>t.required&&d.taskStatus[t.id]?.status!=='done');if(pending.length){toast(`${pending.length} tarefa(s) obrigatória(s) pendente(s)`);modal('Fecho bloqueado',`<div class="notice bad">Conclua as tarefas obrigatórias: <b>${pending.map(x=>esc(x.name)).join(', ')}</b>, ou use uma exceção autorizada com justificação.</div>`);return}completeClose(d)}
  function completeClose(d,reason=''){d.closed=true;d.closedAt=now();d.closedBy=state.currentUser;d.summary=`${clinic(d.clinic).name}: ${sum(d.close.professionals,'done')} realizadas, ${sum(d.close.professionals,'missed')} faltas, ${sum(d.close.professionals,'rescheduled')} reagendadas; lista de espera terminou em ${d.close.wait||0}.`;if(reason)d.exception={reason,by:state.currentUser,at:now()};audit('Operação',reason?'Fecho com exceção autorizada':'Dia fechado',`${d.date}/${d.clinic}${reason?`; justificação: ${reason}`:''}`);persist();closeModal();toast('Dia fechado e resumo criado')}
  function authorizedException(){modal('Exceção autorizada',`<label>Justificação obrigatória</label><textarea id="exceptionReason" placeholder="Explique por que razão o dia pode ser fechado com tarefas pendentes"></textarea><label style="margin-top:10px">Confirmação de gestor</label><input id="managerCode" type="password" placeholder="Código de demonstração: 2026"><div class="actions" style="margin-top:14px"><button class="danger" onclick="App.confirmException()">Autorizar e fechar</button></div>`)}
  function confirmException(){const reason=$('exceptionReason').value.trim();if(!reason||$('managerCode').value!=='2026'){toast('Indique justificação e código válido');return}completeClose(day(),reason)}

  function requestMetrics(){const requests=state.requests,worked=requests.filter(r=>r.history.length||r.stage!=='Novo pedido').length, marked=requests.filter(r=>r.stage==='Marcado');const avg=marked.length?Math.round(marked.reduce((n,r)=>n+((new Date(r.completed||now())-new Date(r.created))/3600000),0)/marked.length):0;return {worked,marked:marked.length,avg};}
  function renderRequests(){const m=requestMetrics();$('waitContent').innerHTML=`<div class="cards"><div class="card"><div class="muted">Novos hoje</div><div class="metric">${state.requests.filter(r=>r.created.slice(0,10)===today()).length}</div></div><div class="card"><div class="muted">Trabalhados</div><div class="metric">${m.worked}</div></div><div class="card"><div class="muted">Marcados</div><div class="metric green">${m.marked}</div></div><div class="card"><div class="muted">Espera média até marcação</div><div class="metric">${m.avg} h</div></div></div><div class="funnel">${requestStages.map(stage=>`<div class="funnel-col"><div class="funnel-head"><span>${stage}</span><span>${state.requests.filter(r=>r.stage===stage).length}</span></div>${state.requests.filter(r=>r.stage===stage).map(requestCard).join('')}</div>`).join('')}</div><div class="card" style="margin-top:14px"><h3>Resultados fora do funil</h3>${state.requests.filter(r=>['Sem resposta','Recusou','Suspenso','Cancelado'].includes(r.stage)).map(requestCard).join('')||'<span class="muted">Sem registos.</span>'}</div>`;}
  function requestCard(r){return `<div class="funnel-card" onclick="App.openRequest('${r.id}')"><b>${esc(r.name)}</b><div class="meta">${esc(clinic(r.clinic)?.name)} · ${esc(r.specialty)}</div><div class="meta">${esc(r.doctor)} · ${esc(user(r.owner).name)}</div></div>`}
  function openRequestForm(){const u=user(), defaultClinic=u.clinic;modal('Novo pedido',`<div class="form-grid"><div><label>Clínica pretendida</label><select id="rClinic" onchange="App.refreshRequestSpecialties()" ${!u.canChangeClinic?'disabled':''}>${options(clinics,x=>x.id,x=>x.name)}</select></div><div><label>Especialidade</label><select id="rSpecialty" onchange="App.refreshRequestDoctors()"></select></div><div><label>Médico</label><select id="rDoctor"></select></div><div><label>Nome do utente</label><input id="rName"></div><div><label>Telefone / contactos</label><input id="rPhone"></div><div class="span-2"><label>Observações</label><textarea id="rNotes"></textarea></div></div><div class="meta" style="margin-top:10px">Entrada e responsável são registados automaticamente.</div><button class="primary" style="margin-top:14px" onclick="App.addRequest()">Criar pedido</button>`);$('rClinic').value=defaultClinic;refreshRequestSpecialties()}
  function refreshRequestSpecialties(){const c=clinic($('rClinic').value);$('rSpecialty').innerHTML=options(Object.keys(c.specialties),x=>x);refreshRequestDoctors()}
  function refreshRequestDoctors(){const c=clinic($('rClinic').value),spec=$('rSpecialty').value;$('rDoctor').innerHTML=options(c.specialties[spec]||[],x=>x)}
  function addRequest(){if(!$('rName').value.trim()||!$('rPhone').value.trim()){toast('Nome e contacto são obrigatórios');return}const r={id:uid('r'),created:now(),clinic:$('rClinic').value,specialty:$('rSpecialty').value,doctor:$('rDoctor').value,name:$('rName').value.trim(),phone:$('rPhone').value.trim(),notes:$('rNotes').value.trim(),stage:'Novo pedido',owner:state.currentUser,history:[]};state.requests.push(r);audit('Pedidos','Novo pedido criado',`${r.name} · ${clinic(r.clinic).name}`);persist();closeModal();toast('Pedido criado')}
  function openRequest(id){const r=state.requests.find(x=>x.id===id);modal(r.name,`<div class="form-grid"><div><label>Clínica</label><input disabled value="${esc(clinic(r.clinic).name)}"></div><div><label>Especialidade</label><input disabled value="${esc(r.specialty)}"></div><div><label>Médico</label><input disabled value="${esc(r.doctor)}"></div><div><label>Responsável</label><select id="editOwner">${options(users,x=>x.id,x=>x.name)}</select></div><div><label>Estado / resultado</label><select id="editStage">${options([...requestStages,'Sem resposta','Recusou','Suspenso','Cancelado'],x=>x)}</select></div><div class="span-2"><label>Resultado / nota da ação</label><textarea id="requestResult" placeholder="Ex.: contacto efetuado, aceita proposta para dia..."></textarea></div></div><div class="actions" style="margin-top:12px"><button class="primary" onclick="App.updateRequest('${r.id}')">Guardar ação</button><button class="secondary" onclick="App.startRequestChat('${r.id}')">Conversar sobre pedido</button></div><h3 style="margin-top:20px">Histórico</h3>${r.history.slice().reverse().map(h=>`<div class="audit-line"><span>${fmt(h.at)}</span><b>${esc(user(h.by).name)}</b><span>${esc(h.from)} → ${esc(h.to)} · ${esc(h.note)}</span></div>`).join('')||'<p class="muted">Sem alterações.</p>'}`);$('editOwner').value=r.owner;$('editStage').value=r.stage}
  function updateRequest(id){const r=state.requests.find(x=>x.id===id),old=r.stage,newStage=$('editStage').value,note=$('requestResult').value.trim();r.stage=newStage;r.owner=$('editOwner').value;if(newStage==='Marcado'&&!r.completed)r.completed=now();r.history.push({at:now(),by:state.currentUser,from:old,to:newStage,note});audit('Pedidos','Pedido trabalhado',`${r.name}: ${old} → ${newStage}${note?`; ${note}`:''}`);persist();closeModal();toast('Ação registada')}

  let activeConversation=null;
  function unreadCount(){return state.conversations.flatMap(c=>c.messages).filter(m=>m.from!==state.currentUser&&!m.readBy.includes(state.currentUser)).length}
  function updateUnread(){const n=unreadCount();$('unread').textContent=n;$('navUnread').textContent=n||''}
  function renderChat(){if(!activeConversation)activeConversation=state.conversations[0]?.id;const c=state.conversations.find(x=>x.id===activeConversation);$('chatContent').innerHTML=`<div class="split"><div class="card" style="padding:0">${state.conversations.map(x=>`<div class="conversation ${x.id===activeConversation?'active':''}" onclick="App.selectConversation('${x.id}')"><b>${esc(x.title)}</b><div class="meta">${x.requestId?'Associada a pedido':''} · ${x.messages.length} mensagens</div></div>`).join('')||'<p class="modal-pad muted">Sem conversas.</p>'}</div><div class="card">${c?`<h3>${esc(c.title)}</h3>${c.requestId?`<button class="secondary" onclick="App.openRequest('${c.requestId}')">Ver pedido associado</button>`:''}<div class="messages" id="messages">${c.messages.map(m=>`<div class="bubble ${m.from===state.currentUser?'mine':''}"><b>${esc(user(m.from).name)}</b><div>${esc(m.text)}</div><div class="meta">${fmt(m.at)} · ${m.readBy.length>1?'Lida':'Enviada'}</div></div>`).join('')}</div><div class="actions" style="margin-top:10px"><input id="chatMessage" placeholder="Escrever mensagem…" onkeydown="if(event.key==='Enter')App.sendMessage()"><button class="primary" onclick="App.sendMessage()">Enviar</button></div>`:'<p class="muted">Selecione ou crie uma conversa.</p>'}</div></div>`;if(c&&$('chat').classList.contains('active')){c.messages.forEach(m=>{if(!m.readBy.includes(state.currentUser))m.readBy.push(state.currentUser)});persist(false);updateUnread();setTimeout(()=>{const el=$('messages');if(el)el.scrollTop=el.scrollHeight},0)}}
  function selectConversation(id){activeConversation=id;renderChat()}
  function sendMessage(){const input=$('chatMessage'),text=input.value.trim();if(!text)return;const c=state.conversations.find(x=>x.id===activeConversation);c.messages.push({id:uid('m'),from:state.currentUser,at:now(),text,readBy:[state.currentUser]});audit('Chat','Mensagem enviada',c.title);persist();renderChat()}
  function newConversation(){modal('Nova conversa',`<label>Assunto</label><input id="convTitle"><label style="margin-top:10px">Destinatários</label>${users.filter(x=>x.id!==state.currentUser).map(x=>`<label class="check"><input type="checkbox" name="member" value="${x.id}"><span>${esc(x.name)} · ${esc(clinic(x.clinic).name)}</span></label>`).join('')}<button class="primary" style="margin-top:12px" onclick="App.createConversation()">Criar conversa</button>`)}
  function createConversation(){const title=$('convTitle').value.trim(),members=[...document.querySelectorAll('[name=member]:checked')].map(x=>x.value);if(!title||!members.length){toast('Indique assunto e destinatário');return}const c={id:uid('cv'),title,members:[state.currentUser,...members],requestId:null,messages:[]};state.conversations.push(c);activeConversation=c.id;audit('Chat','Conversa criada',title);persist();closeModal()}
  function startRequestChat(requestId){const r=state.requests.find(x=>x.id===requestId);let c=state.conversations.find(x=>x.requestId===requestId);if(!c){c={id:uid('cv'),title:`Pedido — ${r.name}`,members:users.map(x=>x.id),requestId,messages:[]};state.conversations.push(c);audit('Chat','Conversa associada a pedido',r.name)}activeConversation=c.id;closeModal();showView('chat');persist()}

  function renderHr(){const active=state.candidates.filter(x=>x.active);$('hrContent').innerHTML=`<div class="cards"><div class="card"><div class="muted">Processos ativos</div><div class="metric">${active.length}</div></div><div class="card"><div class="muted">Documentos em falta</div><div class="metric red">${active.reduce((n,c)=>n+missingDocs(c),0)}</div></div><div class="card"><div class="muted">Tipos de contrato</div><div class="metric">${state.contractTypes.filter(x=>x.active).length}</div><button class="secondary" onclick="App.manageContracts()">Configurar</button></div><div class="card"><div class="muted">Livro de ponto</div><div class="metric">GPS</div><button class="secondary" onclick="App.clockIn()">Assinar ponto</button></div></div><div class="kanban">${candidateStages.map(stage=>`<div class="kanban-col"><div class="funnel-head"><span>${stage}</span><span>${active.filter(x=>x.stage===stage).length}</span></div>${active.filter(x=>x.stage===stage).map(c=>`<div class="funnel-card" onclick="App.openCandidate('${c.id}')"><b>${esc(c.name)}</b><div class="meta">${esc(c.role)} · ${esc(clinic(c.clinic).name)}</div>${missingDocs(c)?`<span class="pill red">${missingDocs(c)} em falta</span>`:'<span class="pill green">Documentos OK</span>'}</div>`).join('')}</div>`).join('')}</div><div class="card" style="margin-top:14px"><h3>Arquivo de inativos</h3>${state.candidates.filter(x=>!x.active).map(x=>`<span class="pill">${esc(x.name)}</span>`).join('')||'<span class="muted">Sem colaboradores arquivados.</span>'}</div>`}
  function contractFor(c){return state.contractTypes.find(x=>x.id===c.contract)}function missingDocs(c){const ct=contractFor(c);return ct?ct.items.filter(i=>i.required&&!c.checks[i.id]?.validated).length:0}
  function openCandidateForm(){modal('Novo candidato',`<div class="form-grid"><div><label>Nome</label><input id="pName"></div><div><label>Email</label><input id="pEmail" type="email"></div><div><label>Telefone</label><input id="pPhone"></div><div><label>Função</label><input id="pRole"></div><div><label>Clínica</label><select id="pClinic">${options(clinics,x=>x.id,x=>x.name)}</select></div><div><label>Tipo de contrato</label><select id="pContract">${options(state.contractTypes.filter(x=>x.active),x=>x.id,x=>x.name)}</select></div></div><button class="primary" style="margin-top:14px" onclick="App.addCandidate()">Criar processo</button>`)}
  function addCandidate(){if(!$('pName').value.trim())return toast('Nome obrigatório');const c={id:uid('p'),name:$('pName').value,email:$('pEmail').value,phone:$('pPhone').value,role:$('pRole').value,clinic:$('pClinic').value,contract:$('pContract').value,stage:'Candidato',notes:'',active:true,checks:{},history:[]};state.candidates.push(c);audit('RH','Candidato criado',c.name);persist();closeModal()}
  function openCandidate(id){const c=state.candidates.find(x=>x.id===id),ct=contractFor(c);modal(c.name,`<div class="form-grid"><div><label>Etapa</label><select id="candidateStage">${options(candidateStages,x=>x)}</select></div><div><label>Contrato</label><select id="candidateContract">${options(state.contractTypes.filter(x=>x.active),x=>x.id,x=>x.name)}</select></div><div class="span-2"><label>Notas</label><textarea id="candidateNotes">${esc(c.notes)}</textarea></div></div><h3 style="margin-top:16px">Checklist documental protegida</h3>${(ct?.items||[]).map(i=>{const ck=c.checks[i.id]||{};return `<div class="check"><input type="checkbox" id="del_${i.id}" ${ck.delivered?'checked':''}><input type="checkbox" id="val_${i.id}" ${ck.validated?'checked':''}><div><b>${esc(i.name)}</b> ${i.required?'<span class="pill red">Obrigatório</span>':''}<div class="meta">1.º visto: entregue · 2.º visto: validado ${ck.at?`por ${esc(user(ck.by).name)} em ${fmt(ck.at)}`:''}</div></div></div>`}).join('')}<div class="actions" style="margin-top:14px"><button class="primary" onclick="App.saveCandidate('${id}')">Guardar</button><button class="danger" onclick="App.archiveCandidate('${id}')">Arquivar / inativar</button></div>`);$('candidateStage').value=c.stage;$('candidateContract').value=c.contract}
  function saveCandidate(id){const c=state.candidates.find(x=>x.id===id),old=c.stage;c.stage=$('candidateStage').value;c.notes=$('candidateNotes').value;const newContract=$('candidateContract').value;if(newContract!==c.contract)c.contract=newContract;const ct=contractFor(c);ct.items.forEach(i=>{const prev=c.checks[i.id]||{};const delivered=$(`del_${i.id}`)?.checked||false,validated=$(`val_${i.id}`)?.checked||false;c.checks[i.id]={delivered,validated,by:(delivered!==prev.delivered||validated!==prev.validated)?state.currentUser:prev.by,at:(delivered!==prev.delivered||validated!==prev.validated)?now():prev.at}});c.history.push({at:now(),by:state.currentUser,from:old,to:c.stage});audit('RH','Processo atualizado',`${c.name}: ${old} → ${c.stage}`);persist();closeModal()}
  function archiveCandidate(id){const c=state.candidates.find(x=>x.id===id);c.active=false;audit('RH','Colaborador arquivado',c.name);persist();closeModal()}
  function manageContracts(){modal('Tipos de contrato e checklists',`${state.contractTypes.map(ct=>`<div class="card"><div class="actions" style="justify-content:space-between"><b>${esc(ct.name)}</b><button class="${ct.active?'danger':'secondary'}" onclick="App.toggleContract('${ct.id}')">${ct.active?'Inativar':'Reativar'}</button></div>${ct.items.map(i=>`<div class="check"><span>${esc(i.name)} ${i.required?'<span class="pill">Obrigatório</span>':''}</span></div>`).join('')}<div class="actions"><input id="newItem_${ct.id}" placeholder="Novo item"><button class="secondary" onclick="App.addContractItem('${ct.id}')">Adicionar item</button></div></div>`).join('')}<button class="primary" onclick="App.addContractType()">+ Tipo de contrato</button>`)}
  function addContractType(){const name=prompt('Nome do tipo de contrato:');if(!name)return;state.contractTypes.push({id:uid('ct'),name,active:true,items:[]});audit('RH','Tipo de contrato criado',name);persist();manageContracts()}
  function addContractItem(id){const input=$(`newItem_${id}`),name=input.value.trim();if(!name)return;state.contractTypes.find(x=>x.id===id).items.push({id:uid('i'),name,required:true});audit('RH','Item de checklist criado',name);persist();manageContracts()}
  function toggleContract(id){const ct=state.contractTypes.find(x=>x.id===id);ct.active=!ct.active;audit('RH',ct.active?'Contrato reativado':'Contrato inativado',ct.name);persist();manageContracts()}
  function clockIn(){if(!navigator.geolocation){toast('Geolocalização não disponível');return}navigator.geolocation.getCurrentPosition(pos=>{state.timeEntries.push({id:uid('te'),user:state.currentUser,at:now(),type:'Entrada',geo:`${pos.coords.latitude.toFixed(5)}, ${pos.coords.longitude.toFixed(5)}`,signature:user().name});audit('RH','Livro de ponto assinado',`GPS ${pos.coords.latitude.toFixed(5)}, ${pos.coords.longitude.toFixed(5)}`);persist();toast('Ponto assinado com geolocalização')},()=>toast('Autorize a geolocalização para assinar'))}

  function renderTasks(){$('tasksContent').innerHTML=`<div class="table-wrap"><table><thead><tr><th>Nome</th><th>Fase</th><th>Clínicas</th><th>Perfil</th><th>Periodicidade / limite</th><th>Resposta / módulo</th><th>Estado</th><th></th></tr></thead><tbody>${state.tasks.map(t=>`<tr><td><b>${esc(t.name)}</b>${t.required?' <span class="pill">Obrigatória</span>':''}</td><td>${{open:'Abertura',live:'Durante o dia',close:'Fecho'}[t.phase]}</td><td>${t.clinics.includes('all')?'Todas':t.clinics.map(x=>esc(clinic(x)?.name)).join(', ')}</td><td>${esc(t.role)}</td><td>${esc(t.frequency)} · ${esc(t.deadline)}</td><td>${esc(t.response)} · ${esc(t.action)}</td><td><span class="pill ${t.active?'green':''}">${t.active?'Ativa':'Arquivada'}</span></td><td><button class="secondary" onclick="App.toggleTask('${t.id}')">${t.active?'Arquivar':'Reativar'}</button></td></tr>`).join('')}</tbody></table></div>`}
  function openTaskForm(){modal('Nova tarefa',`<div class="form-grid"><div class="span-2"><label>Nome</label><input id="tName"></div><div><label>Fase</label><select id="tPhase"><option value="open">Abertura</option><option value="live">Durante o dia</option><option value="close">Fecho</option></select></div><div><label>Obrigatória</label><select id="tRequired"><option value="1">Sim</option><option value="0">Não</option></select></div><div><label>Clínica</label><select id="tClinic"><option value="all">Todas</option>${options(clinics,x=>x.id,x=>x.name)}</select></div><div><label>Responsável / perfil</label><input id="tRole" value="Administrativa"></div><div><label>Periodicidade</label><select id="tFrequency"><option>Diária</option><option>Semanal</option><option>Mensal</option><option>Pontual</option></select></div><div><label>Hora limite</label><input id="tDeadline" type="time" value="17:00"></div><div><label>Tipo de resposta</label><select id="tResponse"><option>sim/não</option><option>número</option><option>texto</option><option>checklist</option><option>seleção de médico/técnico</option></select></div><div><label>Ação / módulo associado</label><select id="tAction"><option value="none">Sem ação</option><option value="planning">Planning</option><option value="wait">Pedidos</option><option value="confirm">Confirmações</option><option value="reval">Reavaliações</option><option value="hr">RH</option></select></div></div><button class="primary" style="margin-top:14px" onclick="App.addTask()">Criar tarefa</button>`)}
  function addTask(){const name=$('tName').value.trim();if(!name)return toast('Nome obrigatório');const t={id:uid('task'),name,phase:$('tPhase').value,required:$('tRequired').value==='1',clinics:[$('tClinic').value],role:$('tRole').value,frequency:$('tFrequency').value,deadline:$('tDeadline').value,response:$('tResponse').value,action:$('tAction').value,active:true};state.tasks.push(t);audit('Configuração','Tarefa criada',t.name);persist();closeModal()}
  function toggleTask(id){const t=state.tasks.find(x=>x.id===id);t.active=!t.active;audit('Configuração',t.active?'Tarefa reativada':'Tarefa arquivada',t.name);persist()}
  function renderAudit(){$('auditContent').innerHTML=`<div class="card">${state.audit.map(a=>`<div class="audit-line"><span>${fmt(a.at)}</span><span><b>${esc(user(a.by).name)}</b><br><span class="pill">${esc(a.module)}</span></span><span><b>${esc(a.action)}</b><br><span class="meta">${esc(a.detail)}</span></span></div>`).join('')||'<p class="muted">A demonstração ainda não tem ações registadas.</p>'}</div>`}
  function showView(id){document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.id===id));document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===id));$('nav').classList.remove('open');if(id==='chat')renderChat()}
  function resetDemo(){if(!confirm('Repor todos os dados de demonstração?'))return;state=seed();audit('Sistema','Dados de demonstração repostos','');persist();toast('Demonstração reposta')}
  function init(){load();document.querySelectorAll('[data-view]').forEach(b=>b.addEventListener('click',()=>showView(b.dataset.view)));$('menuBtn').onclick=()=>$('nav').classList.toggle('open');$('currentUser').onchange=e=>{state.currentUser=e.target.value;audit('Sessão','Utilizador de teste alterado',user().name);persist()};renderAll()}
  document.addEventListener('DOMContentLoaded',init);
  return {setPhase,addProfessional,removeProfessional,updateProfessional,saveOpening,saveClosing,setTask,openTaskAction,finishTaskAction,attemptClose,authorizedException,confirmException,openRequestForm,refreshRequestSpecialties,refreshRequestDoctors,addRequest,openRequest,updateRequest,newConversation,createConversation,selectConversation,sendMessage,startRequestChat,openCandidateForm,addCandidate,openCandidate,saveCandidate,archiveCandidate,manageContracts,addContractType,addContractItem,toggleContract,clockIn,openTaskForm,addTask,toggleTask,resetDemo};
})();
