/* One notification renderer; never copies or approves business records. Demo only. */
(()=>{'use strict';const K='grupo_saude_v4_demo_2',E=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));const server=document.documentElement.dataset.finance==='server';let scheduled=false,signature='',last=[],remote=[],generation=0,inflight=false,failure='';
const state=()=>{try{return JSON.parse(localStorage.getItem(K)||'{}')}catch{return{}}};
function items(){if(server)return remote;const s=state(),r=window.RoleAccessAdminV4,a=window.AccessScopeV4;if(!r||!a)return[];return GSAttentionCore.collect(s,{active:a.actor(s).active!==false,can:key=>r.permission(s,key),employee:id=>a.canEmployee(id,s),clinic:(id,key)=>a.canClinic(id,key,s)})}
function badge(node,value){if(!node)return;let b=node.querySelector('[data-attention-count]');if(!b){b=document.createElement('span');b.dataset.attentionCount='1';b.className='attention-counter';node.appendChild(b)}const label=GSAttentionCore.label(value);if(b.textContent!==label)b.textContent=label;b.hidden=!value;b.setAttribute('aria-label',value+' assuntos pendentes')}
function paint(){scheduled=false;last=items();const nav=document.getElementById('nav');for(const b of nav?.querySelectorAll('button')||[]){const key=b.dataset.view||b.id.replace(/^shortcut_/,'');b.querySelector('[data-fin-count]')?.remove();badge(b,b.hidden?0:GSAttentionCore.count(last,key))}for(const g of nav?.querySelectorAll('details[data-nav-group]')||[]){const keys=new Set([...g.querySelectorAll('button')].filter(b=>!b.hidden).map(b=>b.dataset.view||b.id.replace(/^shortcut_/,'')));badge(g.querySelector('summary'),new Set(last.filter(x=>keys.has(x.module)||keys.has(x.submenu)).map(x=>x.id)).size)}const legacy=document.getElementById('navUnread');if(legacy)legacy.hidden=true;badge(document.getElementById('attentionToggle'),last.length);const dialog=document.getElementById('attentionDialog');if(dialog?.open)panel()}
async function fetchItems(){if(inflight||!window.FinanceUIV4)return;inflight=true;const version=generation;try{const rows=await FinanceUIV4.call('attention-list');if(version===generation){remote=rows.filter(x=>x.module==='finance');failure='';paint()}}catch(e){if(version===generation){remote=[];failure=e.message;paint()}}finally{inflight=false}}
function refresh(){if(server){fetchItems();return}if(!scheduled){scheduled=true;queueMicrotask(paint)}}
async function read(id){if(server){await FinanceUIV4.call('attention-read',{id});await fetchItems();return}const s=state(),x=items().find(x=>x.id===id);if(!x)return;s.attentionRead||={};s.attentionRead[s.currentUser]||={};s.attentionRead[s.currentUser][id]={...(s.attentionRead[s.currentUser][id]||{}),readAt:new Date().toISOString()};localStorage.setItem(K,JSON.stringify(s));refresh()}
function panel(){const dialog=document.getElementById('attentionDialog');if(!dialog)return;const list=items();dialog.querySelector('[data-attention-list]').innerHTML=`<p class="muted">${E(failure)||list.length+' assuntos'} que exigem atenção. Ler uma notificação não aprova nem resolve o respetivo processo.</p>${list.map(x=>`<article class="attention-item ${x.readAt?'':'unread'}"><div><small>${E(x.module)} · ${x.readAt?'Lida':'Por ler'}</small><h3>${E(x.title)}</h3></div><div class="actions"><button data-attention-read="${E(x.id)}" class="secondary">Marcar como lida</button><button data-attention-open="${E(x.id)}" class="primary">Abrir assunto</button>${x.mode==='ack'?`<button data-attention-ack="${E(x.id)}" class="secondary">Confirmar tomada de conhecimento</button>`:''}</div></article>`).join('')||'<p>Sem assuntos pendentes no seu âmbito de acesso.</p>'}`;dialog.querySelectorAll('[data-attention-read]').forEach(b=>b.onclick=()=>safe(()=>read(b.dataset.attentionRead)));dialog.querySelectorAll('[data-attention-ack]').forEach(b=>b.onclick=()=>safe(()=>ack(b.dataset.attentionAck)));dialog.querySelectorAll('[data-attention-open]').forEach(b=>b.onclick=()=>safe(()=>open(b.dataset.attentionOpen)))}
async function safe(fn){try{await fn()}catch(e){alert(e.message);refresh()}}
async function ack(id){const x=items().find(x=>x.id===id);if(!x||x.mode!=='ack')return;if(server){await FinanceUIV4.call('attention-ack',{id});await fetchItems();return}if(x.kind==='invoice')await FinanceDemoV4.call('invoice-read',{id:x.entityId});if(x.kind==='payslip')await FinanceDemoV4.call('receipt-read',{id:x.entityId});const s=state();if(String(s.currentUser)!==x.recipientId)return;s.attentionRead||={};s.attentionRead[s.currentUser]||={};s.attentionRead[s.currentUser][id]={readAt:new Date().toISOString(),resolvedAt:new Date().toISOString()};localStorage.setItem(K,JSON.stringify(s));refresh()}
async function open(id){const x=items().find(x=>x.id===id);if(!x)return;await read(id);document.getElementById('attentionDialog')?.close();if(['invoice','payslip','entry','payment'].includes(x.kind))return window.FinanceUIV4.openRecord(x.kind==='payment'?'entry':x.kind,x.entityId,x.employeeId);if(x.kind==='performance'||x.kind==='peer')return window.HRPerformanceUIV4.open(x.employeeId);if(x.kind==='leave')return window.HRLeaveUIV4.open(x.entityId);if(x.kind==='document')return window.HRMasterV4.open(x.employeeId,'docs');if(x.kind==='occurrence')return window.HRMasterV4.open(x.employeeId,'resumo');if(x.kind==='request')return window.V4Integrations.openRequest(x.entityId);if(x.kind==='candidate'){App.showView('hr');return window.CommunicationsV4.candidate(x.entityId)}if(x.kind==='chat'){const s=state(),c=(s.conversations||[]).find(c=>(c.messages||[]).some(m=>String(m.id)===x.entityId));if(c){App.showView('chat');return App.selectConversation(c.id)}}if(RoleAccessAdminV4.guard(x.module))App.showView(x.module)}
function boot(){const actions=document.querySelector('.top-actions');if(actions&&!document.getElementById('attentionToggle')){const b=document.createElement('button');b.id='attentionToggle';b.className='icon-btn';b.textContent='Notificações';b.onclick=()=>{panel();document.getElementById('attentionDialog').showModal()};actions.prepend(b);const d=document.createElement('dialog');d.id='attentionDialog';d.innerHTML='<form method="dialog" class="modal-head"><h2>Centro de atenção</h2><button aria-label="Fechar">×</button></form><div class="modal-body" data-attention-list></div>';document.body.appendChild(d)}refresh();setInterval(()=>{if(server){if(!document.hidden)refresh();return}const current=localStorage.getItem(K)||'';if(current!==signature){signature=current;refresh()}},server?15000:1500)}
window.AttentionUIV4={items,refresh,read,open,ack};document.addEventListener('DOMContentLoaded',boot);for(const event of ['gs:state-changed','gs:user-changed','gs:permissions-applied','gs:view-changed'])document.addEventListener(event,()=>{generation++;remote=[];document.getElementById('attentionDialog')?.close();refresh()});window.addEventListener('storage',e=>{if(e.key===K)refresh()});
})();
