/* Attention is derived from canonical records. Reading is separate from resolving. */
(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.GSAttentionCore=api})(typeof globalThis!=='undefined'?globalThis:this,()=>{'use strict';
const norm=v=>String(v||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toUpperCase(),owner=x=>String(x.employeeId||x.userId||x.user||''),pending=v=>['PENDENTE','PENDING','EM FALTA','PENDENTE DE VALIDACAO','POR VALIDAR'].includes(norm(v));
function collect(s,policy){const recipient=String(s.currentUser||''),rows=new Map();if(!recipient||!policy.active)return[];
 const add=(kind,x,module,submenu,title,employeeId='',mode='action')=>{if(!x.id)return;const id=[kind,x.id,x.revision||0,x.status||x.stage||''].map(encodeURIComponent).join(':');rows.set(id,{id,recipientId:recipient,kind,entityId:String(x.id),module,submenu,title:String(title||'Assunto pendente'),employeeId:String(employeeId),mode,readAt:(s.attentionRead?.[recipient]?.[id]?.readAt||s.attentionRead?.[recipient]?.[id])||null,resolvedAt:s.attentionRead?.[recipient]?.[id]?.resolvedAt||null,at:x.updatedAt||x.createdAt||x.uploadedAt||x.at||'',clinicId:String(x.clinicId||x.clinic||'')})};
 const person=id=>policy.employee(String(id)),clinic=(x,key)=>policy.clinic(String(x.clinicId||x.clinic||''),key);
 if(policy.can('account'))for(const x of s.paymentNotifications||[])if(owner(x)===recipient&&!((s.financeV2?.entries||[]).find(e=>e.id===x.id)?.status==='Pendente'))add('payment',x,'finance','account','Pagamento confirmado: consultar a conta corrente',recipient,'ack');
 const fin=s.financeV2||{},financialDocuments=new Set([...(fin.invoices||[]),...(fin.payslips||[])].map(x=>String(x.documentId||'')).filter(Boolean));if(policy.can('financeManage'))for(const x of s.paymentMailIssues||fin.paymentMailIssues||[])if(['FAILED','UNCERTAIN'].includes(norm(x.status))||norm(x.status)==='SENDING'&&Date.now()-new Date(x.createdAt).getTime()>900000)add('payment-mail',x,'finance','financialManagement','Email de pagamento requer intervenção',x.employeeId);if(policy.can('account')){
 if(policy.can('financeManage')){for(const x of fin.emailAlerts||[])if(pending(x.status))add('email-alert',x,'finance','financialManagement','Email não carregado: verificar a mensagem original');for(const x of fin.regularizations||[])if(norm(x.status)!=='APROVADA')add('regularization',x,'finance','financialManagement','Regularização de pagamento por decidir',x.employeeId||x.user_id);for(const x of fin.mailDocuments||[])if(pending(x.status))add('mail-document',x,'finance','financialManagement','Documento por classificar e associar');}
 for(const x of fin.invoices||[])if(policy.can('financeManage')&&pending(x.status))add('invoice',x,'finance','invoices','Fatura por validar',x.employeeId);else if(owner(x)===recipient&&norm(x.status)==='RECUSADA'&&!x.readAt)add('invoice',x,'finance','invoices','Fatura recusada: '+(x.reason||'consultar motivo'),x.employeeId,'ack');
 for(const x of fin.payslips||[])if(policy.can('financeManage')&&pending(x.status))add('payslip',x,'finance','payslips','Recibo por associar / validar',x.employeeId);else if(owner(x)===recipient&&norm(x.status)==='VALIDADA'&&!x.readAt)add('payslip',x,'finance','payslips','Novo Recibo de Vencimento',x.employeeId,'ack');
 for(const x of fin.entries||[])if(policy.can('financeManage')&&pending(x.status))add('entry',x,'finance','account','Movimento por aprovar',x.employeeId);
 }
 if(policy.can('leaveRequest')||policy.can('leaveApprove'))for(const x of s.leave||[])if(pending(x.status)&&policy.can('leaveApprove')&&person(owner(x)))add('leave',x,'hr',/FERIAS/.test(norm(x.type))?'vacations':'sickness','Pedido de '+(x.type||'ausência')+' por decidir',owner(x));
 if(policy.can('personal')||policy.can('hrManage'))for(const [uid,list]of Object.entries(s.employeeDocuments||{}))if(person(uid))for(const x of list){if(x.financeDocumentId||financialDocuments.has(String(x.id)))continue;const expiry=String(x.expiryDate||x.expiresAt||x.validUntil||'').slice(0,10);if(pending(x.status)||expiry&&expiry<=new Date().toISOString().slice(0,10))add('document',x,'hr','documents',expiry?'Documento expirado / por atualizar':'Documento por completar',uid)}
 if(policy.can('hrManage'))for(const x of s.candidates||[])if((!x.clinicId&&!x.clinic||clinic(x,'hrManage'))&&(pending(x.status||x.stage)||['NOVO','RECEBIDO','ENTREVISTA'].includes(norm(x.status||x.stage))))add('candidate',x,'hr','candidates','Candidatura por acompanhar');
 if(policy.can('performanceManage'))for(const x of s.hrPerformance||[])if(person(x.employeeId)&&((s.hrPerformanceEvents||[]).filter(e=>e.evaluationId===x.id).at(-1)?.action||'Proposta')==='Proposta')add('performance',x,'hr','employees','Avaliação de desempenho por decidir',x.employeeId);
 if(policy.can('peerReview')&&(s.hrPerformanceRuleVersions||[]).at(-1)?.peerEnabled)for(const x of s.hrPeerCycles||[])if((x.members||[]).map(String).includes(recipient)&&clinic(x,'peerReview')&&((s.hrPeerCycleEvents||[]).filter(e=>e.cycleId===x.id).at(-1)?.action||'Aberto')==='Aberto'&&(x.members||[]).some(id=>String(id)!==recipient&&!(s.hrPeerResponses||[]).some(r=>r.cycleId===x.id&&String(r.reviewerId)===recipient&&String(r.targetId)===String(id))))add('peer',x,'hr','employees','Questionário entre colegas por responder',recipient);
 if(policy.can('clock'))for(const x of s.timeOccurrences||[])if(pending(x.status)&&person(owner(x)))add('occurrence',x,'clock','clock','Ocorrência de ponto por resolver',owner(x));
 if(policy.can('waiting'))for(const x of s.requests||[])if(!['MARCADO','CONCLUIDO','CANCELADO','RECUSADO','FECHADO'].includes(norm(x.stage||x.status))&&clinic(x,'waiting'))add('request',x,'wait','wait','Pedido por acompanhar: '+(x.name||''));
 if(policy.can('clinicTasks'))for(const d of Object.values(s.days||{}))if(!d.closed&&clinic(d,'clinicTasks'))for(const t of s.tasks||[]){if(t.active===false||!(t.clinics||[]).some(c=>c==='all'||String(c)===String(d.clinic))||(t.assignedTo&&String(t.assignedTo)!==recipient))continue;const status=d.taskStatus?.[t.id];if(['DONE','CONCLUIDA','CONCLUIDO'].includes(norm(typeof status==='string'?status:status?.status)))continue;add('task',{id:String(d.date)+'_'+d.clinic+'_'+t.id,clinic:d.clinic,at:d.date},'operation','operation','Tarefa pendente: '+t.name)}
 if(policy.can('marketing'))for(const x of s.marketing?.campaigns||[]){const matches=(s.clinics||[]).filter(c=>c.name===x.clinic),cid=x.clinicId||((matches.length===1)?matches[0].id:x.clinic);if(norm(x.status)==='PENDENTE DE APROVACAO'&&(!cid||policy.clinic(String(cid),'marketing')))add('campaign',x,'marketing','marketing','Conteúdo de marketing por aprovar: '+(x.title||''))}
 if(policy.can('security'))for(const x of s.security?.backups||[])if(pending(x.status)||['ERRO','FAILED','FALHOU'].includes(norm(x.status)))add('backup',x,'security','security','Backup requer intervenção');
 if(policy.can('settings')){const latest=new Map();for(const x of s.communicationRuns||[]){const key=x.kind+':'+x.sourceId;if(!latest.has(key)||String(x.at)>String(latest.get(key).at))latest.set(key,x)}for(const x of latest.values())if(pending(x.status)||['ERRO','FAILED','FALHOU'].includes(norm(x.status)))add('communication',x,'tables','tables','Execução de email/documentos requer intervenção')}
 if(policy.can('alerts'))for(const x of s.alerts||[])if(!['RESOLVIDO','CONCLUIDO','CANCELADO'].includes(norm(x.status))&&(!x.to||String(x.to)===recipient)&&clinic(x,'alerts'))add('alert',x,'alerts','alerts',x.title||'Alerta por resolver');
 if(policy.can('personal'))for(const c of s.conversations||[])if((c.members||[]).map(String).includes(recipient))for(const m of c.messages||[])if(String(m.from)!==recipient&&!(m.readBy||[]).map(String).includes(recipient))add('chat',{...m,id:m.id,at:m.at},'chat','chat','Mensagem por ler: '+c.title);
 return [...rows.values()].filter(x=>x.mode!=='ack'||!x.resolvedAt).sort((a,b)=>String(b.at).localeCompare(String(a.at))||a.id.localeCompare(b.id));
}
function count(items,key){return new Set(items.filter(x=>!key||x.module===key||x.submenu===key).map(x=>x.id)).size}function label(n){return n>99?'99+':String(n)}
return{collect,count,label,norm};});
