/* Four communication functions; migration keeps every previous custom address. */
(function(root){'use strict';
const definitions=[{id:'cv',name:'Currículos',type:'Upload',provider:'gmail',address:'gruposaude.rh@gmail.com',aliases:[]},{id:'payslips',name:'Recibos de vencimento e faturas',type:'Upload',provider:'gmail',address:'',aliases:['invoices']},{id:'backup',name:'Documentos / Backup',type:'Download',provider:'resend',address:'',aliases:['inactive']},{id:'tasks',name:'Notificações',type:'Download',provider:'resend',address:'',aliases:['alerts']}];
function normalize(records=[]){return definitions.map(def=>{const old=records.find(x=>x.id===def.id),other=records.filter(x=>def.aliases.includes(x.id)),fallback=other.find(x=>x.address),source=old&&(old.address||old.updatedAt||old.updatedBy)?old:fallback||old||{};return{...def,...source,id:def.id,name:def.name,address:source===old&&old?String(old.address||''):String(source.address||def.address),active:source.active===true,provider:source.provider||def.provider,destination:def.id==='payslips'?'Recibos de vencimento e faturas':def.name,previousConfigurations:[...(source.previousConfigurations||[]),...other].filter((x,i,a)=>a.findIndex(y=>JSON.stringify(x)===JSON.stringify(y))===i)}})}
function validate(id,value){const def=definitions.find(x=>x.id===id);if(!def)throw Error('Função de email desconhecida.');const address=String(value.address||'').trim().toLowerCase(),provider=value.provider||def.provider;if(!['gmail','microsoft365','resend'].includes(provider)||['cv','payslips'].includes(id)&&provider==='resend'||address&&!/^[^\s@<>]+@[^\s@<>]+\.[^\s@<>]+$/.test(address)||value.active&&!address)throw Error('Configure um email e fornecedor válidos.');return{address,provider,active:value.active===true,type:def.type}}
function safeEmailLink(value){try{const u=new URL(value);return u.protocol==='https:'&&!u.username&&!u.password&&['mail.google.com','outlook.office.com','outlook.office365.com'].includes(u.hostname)?u.href:null}catch{return null}}
function provisionalAssociation(people,context={},filename=''){
 const word=v=>' '+String(v||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toUpperCase().replace(/[^A-Z0-9]+/g,' ').trim()+' ',text=word(String(filename).slice(0,500)+' '+String(context.subject||'').slice(0,500)),from=String(context.from||'').toLowerCase().match(/[a-z0-9.!#$%&'*+/=?^_`{|}~-]+@[a-z0-9.-]+\.[a-z]{2,}/g)||[],hints=[];
 for(const p of people.filter(p=>p.active!==false)){const basis=[];if(from.length===1&&String(p.email||'').toLowerCase()===from[0])basis.push('Email do remetente coincide com a ficha');if(p.email&&String(filename+' '+(context.subject||'')).toLowerCase().includes(String(p.email).toLowerCase()))basis.push('Email identificado no nome/assunto');const tax=String(p.taxId||p.nif||p.hr?.nif||'').trim();if(/^\d{9}$/.test(tax)&&text.includes(' '+tax+' '))basis.push('NIF identificado no nome/assunto');const full=word(p.name);if(full.trim().split(' ').length>=2&&full.trim().length>=7&&text.includes(full))basis.push('Nome completo identificado no nome/assunto');if(basis.length)hints.push({id:String(p.id),basis})}
 const slip=/\b(RECIBO|VENCIMENTO|PAYSLIP|PAYROLL)\b/.test(text),inv=/\b(FATURA|FACTURA|INVOICE)\b/.test(text);return{employeeId:hints.length===1?hints[0].id:null,basis:hints.length===1?hints[0].basis:[],ambiguous:hints.length>1,candidateIds:hints.map(x=>x.id),kind:slip!==inv?(slip?'payslip':'invoice'):null,status:hints.length===1?'Provisória — aguarda aprovação':'Por identificar'}
}
const core={definitions,normalize,validate,safeEmailLink,provisionalAssociation};root.GSCommunicationsCore=core;if(typeof module!=='undefined')module.exports=core;
})(typeof window!=='undefined'?window:globalThis);
