/* Regras financeiras partilhadas por UI e servidor. Valores internos em cêntimos. */
(function(root){'use strict';
const error=m=>Object.assign(new Error(m),{financeDomain:true}),norm=v=>String(v||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toUpperCase().trim().replace(/^SUPERSEDED$/,'SUBSTITUIDO'),fail=m=>{throw error(m)},date=v=>{const d=new Date(v+'T12:00:00Z');if(!/^\d{4}-\d{2}-\d{2}$/.test(v||'')||!Number.isFinite(d.getTime())||d.toISOString().slice(0,10)!==v)fail('Data inválida.');return v},cents=v=>{const s=String(v??'').trim().replace(',','.');if(!/^-?\d{1,9}(\.\d{1,2})?$/.test(s))fail('Valor inválido: utilize no máximo duas casas decimais.');const negative=s[0]==='-',parts=s.replace('-','').split('.');const n=Number(parts[0])*100+Number((parts[1]||'').padEnd(2,'0'));return negative?-n:n},euro=n=>(n/100).toFixed(2),money=n=>(n/100).toLocaleString('pt-PT',{style:'currency',currency:'EUR'});
const manager=a=>!!a&&a.active!==false&&['CEO','ADMINISTRACAO'].includes(norm(a.role))&&a.permissions?.financeManage!==false&&a.permissions?.account!==false,read=a=>!!a&&a.active!==false&&['CEO','ADMINISTRACAO','ADMINISTRATIVA','ADMINISTRATIVO','CALL CENTER','CALLCENTER','MEDICO','MEDICO/A','TECNICO','TECNICO/A','BASICO'].includes(norm(a.role||a.kind))&&a.permissions?.account!==false,can=(a,id)=>read(a)&&(String(a.id)===String(id)||manager(a)),assertManager=a=>{if(!manager(a))fail('Gestão financeira exclusiva do CEO e Administração.')},assertRead=(a,id)=>{if(!can(a,id))fail('Sem autorização para consultar este colaborador.')},token=v=>String(v||'').normalize('NFKC').trim().toUpperCase().replace(/\s+/g,'');
function invoice(data,actor,now){if(!read(actor))fail('Sem autorização para enviar faturas.');const number=token(data.number),series=token(data.series);if(!number||number.length>80||series.length>80)fail('Número da fatura obrigatório (máximo 80 caracteres).');const value=cents(data.value);if(value<=0)fail('Valor da fatura deve ser positivo.');return{employeeId:String(actor.id),issuerKey:token(actor.taxId||actor.id),number,series,invoiceDate:date(data.invoiceDate),insertedDate:date(data.insertedDate),valueCents:value,notes:String(data.notes||'').slice(0,4000),status:'Pendente',uploadedAt:now,uploadedBy:String(actor.id)}}
function receipt(data,actor,now){if(!manager(actor)&&(!read(actor)||!data.replacementOf||String(data.employeeId)!==String(actor.id)))assertManager(actor);const year=Number(data.year),month=Number(data.month);if(!Number.isInteger(year)||year<2000||year>2100||!Number.isInteger(month)||month<1||month>12)fail('Mês e ano inválidos.');if(!data.employeeId)fail('Confirme manualmente o colaborador.');return{employeeId:String(data.employeeId),year,month,documentDate:date(data.documentDate),valueCents:data.value==null||data.value===''?null:cents(data.value),number:token(data.number),notes:String(data.notes||'').slice(0,4000),status:'Pendente',uploadedAt:now,uploadedBy:String(actor.id)}}
function entry(data,actor){assertManager(actor);if(!data.employeeId)fail('Selecione o colaborador.');if(!['Consulta','Tratamento','Ato','Bónus','Ajuste','Percentagem'].includes(data.type))fail('Tipo de movimento inválido.');const qty=Number(data.quantity||1),unit=cents(data.unitValue==null||data.unitValue===''?data.value:data.unitValue),pct=Number(data.percentage||0);if(!Number.isFinite(qty)||qty<=0||qty>10000||Math.abs(Math.round(qty*100)-qty*100)>0.000001||!Number.isFinite(pct)||pct<0||pct>100)fail('Quantidade ou percentagem inválida.');const valueCents=data.value==null?Math.round(qty*unit*(data.percentage!=null&&data.percentage!==''?pct/100:1)):cents(data.value);if(valueCents===0||valueCents<0&&data.type!=='Ajuste')fail('O crédito deve ser positivo; apenas ajustes permitem débito negativo.');if(data.type==='Bónus'&&(!/^\d{4}-Q[1-4]$/.test(data.quarter||'')))fail('Indique o trimestre do bónus.');return{employeeId:String(data.employeeId),clinicId:String(data.clinicId||''),date:date(data.date),type:data.type,description:String(data.description||data.type).slice(0,2000),valueCents,status:'Pendente',quantity:qty,unitCents:unit,percentage:pct,quarter:data.quarter||null}}
function state(v){if(norm(v)==='SUBSTITUIDO')return 'Substituído';return ['PAGO','PAGA'].includes(norm(v))?'Pago':['APROVADO','VALIDADA','VALIDADO','POR PAGAR'].includes(norm(v))?'Aprovado':'Pendente'}
function ledger(rows){
 const items=rows.map(x=>({...x,originalValueCents:x.originalValueCents??x.data?.originalValueCents??x.valueCents??cents(x.value),valueCents:norm(x.status)==='SUBSTITUIDO'?0:x.valueCents??cents(x.value),date:date(String(x.date||x.entry_date).slice(0,10)),type:x.type||x.kind,employeeId:String(x.employeeId||x.user_id),status:state(x.status),paymentOf:x.paymentOf||x.data?.paymentOf||null})),paid=new Map();
 const add=p=>{if(p.paymentOf&&p.status==='Pago'&&p.valueCents<0){const key=String(p.paymentOf),old=paid.get(key)||{value:0,at:null};old.value-=p.valueCents;const at=p.paidAt||p.date;if(!old.at||String(at)>String(old.at))old.at=at;paid.set(key,old)}};
 items.forEach(add);
 for(const x of [...items])if(x.valueCents>0&&x.status==='Pago'&&!paid.has(String(x.id))){const p={id:'legacy-paid:'+x.id,employeeId:x.employeeId,clinicId:x.clinicId||x.clinic_id,date:String(x.paidAt||x.paid_at||x.date).slice(0,10),type:'Pagamento',description:'Pagamento histórico · '+(x.description||x.type),valueCents:-x.valueCents,status:'Pago',paymentOf:x.id,paidAt:x.paidAt||x.paid_at||null,legacy:true,virtual:true};items.push(p);add(p)}
 for(const x of items)if(x.valueCents>0&&x.status!=='Pendente'){const p=paid.get(String(x.id))||{value:0,at:null};x.paidCents=p.value;x.outstandingCents=Math.max(0,x.valueCents-p.value);x.status=p.value>=x.valueCents?'Pago':'Aprovado';x.paidAt=p.value>=x.valueCents?p.at:null}
 return items.sort((a,b)=>a.date.localeCompare(b.date)||String(a.id).localeCompare(String(b.id)))
}
function statement(rows,actor,employeeId,start,end){assertRead(actor,employeeId);date(start);date(end);if(start>end)fail('A data final não pode ser anterior à inicial.');const all=ledger(rows.filter(x=>String(x.employeeId||x.user_id)===String(employeeId))),included=x=>x.status!=='Pendente';const previous=all.filter(x=>x.date<start&&included(x)).reduce((n,x)=>n+x.valueCents,0),items=all.filter(x=>x.date>=start&&x.date<=end),credits=items.filter(x=>included(x)&&x.valueCents>0).reduce((n,x)=>n+x.valueCents,0),debits=items.filter(x=>included(x)&&x.valueCents<0).reduce((n,x)=>n-x.valueCents,0),payments=items.filter(x=>x.type==='Pagamento'&&x.status==='Pago').reduce((n,x)=>n-x.valueCents,0);return{start,end,employeeId:String(employeeId),items,previousCents:previous,creditsCents:credits,debitsCents:debits,paymentsCents:payments,finalCents:previous+credits-debits}}
function file(bytes,mime,name,onlyPdf=false){if(!bytes?.length||bytes.length>3*1024*1024)fail('Documento obrigatório; máximo 3 MB.');const isPdf=bytes[0]===37&&bytes[1]===80&&bytes[2]===68&&bytes[3]===70&&bytes[4]===45,isJpeg=bytes[0]===255&&bytes[1]===216&&bytes[2]===255,isPng=bytes.slice(0,8).every((b,i)=>b===[137,80,78,71,13,10,26,10][i])&&bytes.length>=8;const detected=isPdf?'application/pdf':isJpeg?'image/jpeg':isPng?'image/png':null;if(!detected||detected!==mime||onlyPdf&&detected!=='application/pdf')fail('Documento inválido: PDF, JPG ou PNG (recibos apenas PDF).');return{mime:detected,name:String(name||'documento').replace(/[\u0000-\u001f/\\]/g,'_').slice(0,150),size:bytes.length}}
function notifications(data,actor){const own=String(actor.id),invoices=data.invoices.filter(x=>manager(actor)||String(x.employeeId)===own),payslips=data.payslips.filter(x=>manager(actor)||x.status==='Validada'&&String(x.employeeId)===own);return{emailAlertsPending:manager(actor)?(data.emailAlerts||[]).filter(x=>x.status==='Pendente').length:0,mailPending:manager(actor)?(data.mailDocuments||[]).filter(x=>x.status==='Pendente').length:0,regularizationsPending:manager(actor)?(data.regularizations||[]).filter(x=>x.status==='Pendente').length:0,invoicesPending:manager(actor)?invoices.filter(x=>x.status==='Pendente').length:0,receiptsPending:manager(actor)?payslips.filter(x=>x.status==='Pendente').length:0,rejected:invoices.filter(x=>String(x.employeeId)===own&&x.status==='Recusada'&&!x.readAt).length,newReceipts:payslips.filter(x=>String(x.employeeId)===own&&x.status==='Validada'&&!x.readAt).length,movementsPending:manager(actor)?data.entries.filter(x=>state(x.status)==='Pendente').length:0}}
function pdf(report,name){const lines=['Grupo Saude - Conta corrente',name,report.start+' a '+report.end,'Saldo anterior: '+euro(report.previousCents)+' EUR','Creditos: '+euro(report.creditsCents)+' EUR','Debitos: '+euro(report.debitsCents)+' EUR','Pagamentos: '+euro(report.paymentsCents)+' EUR','Saldo final: '+euro(report.finalCents)+' EUR','Data | Tipo | Descricao | Credito | Debito | Estado | Pago em',...report.items.flatMap(x=>{const s=x.date+' | '+x.type+' | '+(x.description||'')+' | '+(x.valueCents>0?euro(x.valueCents):'-')+' | '+(x.valueCents<0?euro(-x.valueCents):'-')+' | '+x.status+' | '+String(x.paidAt||'-').slice(0,10);return s.match(/.{1,95}/g)||['']}),'Convencao: pendentes nao afetam saldo; pagamentos sao debitos.'];const pages=[];for(let i=0;i<lines.length;i+=47)pages.push(lines.slice(i,i+47));const ascii=s=>String(s).normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^\x20-\x7e]/g,'?').replace(/[\\()]/g,'\\$&');const objs=['<< /Type /Catalog /Pages 2 0 R >>','', '<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>'];const kids=[];for(const page of pages){const p=objs.length+1,c=p+1;kids.push(p+' 0 R');objs.push('<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Resources << /Font << /F1 3 0 R >> >> /Contents '+c+' 0 R >>');const text='BT /F1 9 Tf 38 800 Td 16 TL '+page.map((x,i)=>(i?'T* ':'')+'('+ascii(x)+') Tj').join('\n')+' ET';objs.push('<< /Length '+text.length+' >>\nstream\n'+text+'\nendstream')}objs[1]='<< /Type /Pages /Kids ['+kids.join(' ')+'] /Count '+pages.length+' >>';let out='%PDF-1.4\n';const offsets=[0];for(let i=0;i<objs.length;i++){offsets.push(out.length);out+=(i+1)+' 0 obj\n'+objs[i]+'\nendobj\n'}const xref=out.length;out+='xref\n0 '+(objs.length+1)+'\n0000000000 65535 f \n'+offsets.slice(1).map(n=>String(n).padStart(10,'0')+' 00000 n \n').join('')+'trailer\n<< /Size '+(objs.length+1)+' /Root 1 0 R >>\nstartxref\n'+xref+'\n%%EOF';return new TextEncoder().encode(out)}
// Candidate detection never changes a document. Exact bytes are independent of dates/types.
function documentMatches(records,kind,value,hash,at=new Date().toISOString()){
 const now=Date.parse(at),min=now-7*86400000,emission=v=>v.invoiceDate||v.documentDate;
 const equal=records.filter(x=>hash&&x.fileHash===hash),same=records.filter(x=>x.kind===kind&&String(x.employeeId)===String(value.employeeId));
 const identity=same.filter(x=>x.status!=='Substituído'&&(!x.replacementOf||x.status==='Validada')).filter(x=>kind==='invoice'?token(x.number)===token(value.number)&&token(x.series)===token(value.series):x.year===value.year&&x.month===value.month);
 const similar=same.filter(x=>{const issued=Date.parse(emission(x)+'T12:00:00Z');if(!Number.isFinite(issued)||issued<min||issued>now+86400000||x.status==='Substituído')return false;const signals=[token(x.number)&&token(x.number)===token(value.number),emission(x)===emission(value),kind==='payslip'&&x.year===value.year&&x.month===value.month,x.valueCents!=null&&value.valueCents!=null&&x.valueCents===value.valueCents];return kind==='payslip'&&x.year===value.year&&x.month===value.month||signals.filter(Boolean).length>=2});
 return{exact:equal.length>0,identity:identity.map(x=>x.id),similar:similar.map(x=>({id:x.id,number:x.number||'',date:emission(x),year:x.year,month:x.month,valueCents:x.valueCents,status:x.status})),question:similar.length?'Este documento é novo ou pretende substituir um documento anterior?':null}
}
function documentIntent(records,kind,value,hash,data,actor,at){
 const matches=documentMatches(records,kind,value,hash,at);if(matches.exact)fail('Documento exatamente igual já carregado (duplicado), independentemente da data.');
 const target=data.replacementOf&&records.find(x=>x.kind===kind&&x.id===data.replacementOf);
 if(data.replacementOf){if(!target||String(target.employeeId)!==String(value.employeeId)||!['Validada','Recusada'].includes(target.status))fail('Selecione um documento anterior válido do mesmo colaborador e tipo.');assertRead(actor,target.employeeId);if(!String(data.replacementReason||'').trim())fail('Indique o motivo da substituição.');if(records.some(x=>x.kind===kind&&x.replacementOf===target.id&&x.status==='Pendente'))fail('Já existe uma substituição pendente para este documento.');if(data.replacementRevision!=null&&Number(data.replacementRevision)!==target.revision)fail('O documento anterior mudou. Reabra o registo.');}
 if(matches.similar.length&&!target&&data.duplicateDecision!=='new')fail(matches.question);
 if(kind==='invoice'&&matches.identity.some(id=>id!==target?.id))fail('Fatura duplicada do mesmo emitente, número e série. Selecione a substituição.');
 return{matches,replacementOf:target?.id||null,replacementRevision:target?.revision??null,replacementReason:String(data.replacementReason||'').trim().slice(0,4000)}
}
function archiveEligibility(plan,at=new Date().toISOString()){
 const reasons=[];if(!plan.reviewedBy||!plan.legalBasis||!plan.retainUntil)reasons.push('Revisão legal e prazo de conservação obrigatórios');if(plan.legalHold!==false)reasons.push('Bloqueio legal não levantado');if(!plan.uploadedAt||!Number.isFinite(Date.parse(plan.uploadedAt))||Date.parse(at)-Date.parse(plan.uploadedAt)<365*86400000)reasons.push('Documento online há menos de um ano');if(plan.backupStatus!=='Archived'||!plan.archiveReceipt||!/^[a-f0-9]{64}$/.test(plan.contentHash||'')||plan.backupHash!==plan.contentHash)reasons.push('Receção e arquivo da cópia não confirmados');if(plan.pendingReplacement||plan.pendingRegularization)reasons.push('Substituição ou regularização pendente');if(plan.retainUntil&&(!Number.isFinite(Date.parse(plan.retainUntil+'T23:59:59Z'))||Date.parse(plan.retainUntil+'T23:59:59Z')<Date.parse(at)))reasons.push('Rever prazo e fundamento antes de preparar remoção');return{eligible:reasons.length===0,reasons}
}
const C={documentMatches,documentIntent,archiveEligibility,error,norm,date,cents,euro,money,manager,read,can,assertManager,assertRead,invoice,receipt,entry,state,ledger,statement,file,notifications,pdf,token};root.GSFinanceCore=C;if(typeof module!=='undefined')module.exports=C;
})(typeof window!=='undefined'?window:globalThis);
