/* V4 — drag & drop do funil de pedidos, incluindo suporte touch */
(()=>{'use strict';
const KEY='grupo_saude_v4_demo_2';
const stages=['Pedido de Consulta','A aguardar Vaga','Sem especialidade na clínica','Marcado'];
const legacyStageMap={'Novo pedido':'Pedido de Consulta','Por contactar':'Pedido de Consulta','Contactado':'Pedido de Consulta','A aguardar vaga':'A aguardar Vaga','Proposta de consulta':'A aguardar Vaga'};
let dragging=null,touchCard=null;
const read=()=>{try{return JSON.parse(localStorage.getItem(KEY)||'null')}catch{return null}};
const write=s=>localStorage.setItem(KEY,JSON.stringify(s));
function normalizeStages(){const s=read();if(!s?.requests)return;s.requests.forEach(r=>{if(legacyStageMap[r.stage])r.stage=legacyStageMap[r.stage]});write(s)}
function stayOnRequests(){sessionStorage.setItem('gs_v4_view','wait')}
function restoreView(){if(sessionStorage.getItem('gs_v4_view')!=='wait')return;sessionStorage.removeItem('gs_v4_view');setTimeout(()=>document.querySelector('[data-view="wait"]')?.click(),40)}
function move(id,stage){const s=read(),r=s?.requests?.find(x=>x.id===id);if(!r||r.stage===stage)return;r.history=r.history||[];r.history.push({at:new Date().toISOString(),by:s.currentUser,from:r.stage,to:stage,action:'Movido no funil'});const old=r.stage;r.stage=stage;if(stage==='Marcado')r.completed=r.completed||new Date().toISOString();s.audit=s.audit||[];s.audit.unshift({id:`log_${Date.now()}`,at:new Date().toISOString(),by:s.currentUser,module:'Pedidos',action:'Pedido movido no funil',detail:`${r.name}: ${old} → ${stage}`});write(s);stayOnRequests();location.reload()}
function install(){const funnel=document.querySelector('#waitContent .funnel');if(!funnel)return;const cols=[...funnel.querySelectorAll('.funnel-col')];cols.forEach((col,i)=>{if(i>=stages.length){col.remove();return}const stage=stages[i];col.dataset.stage=stage;const title=col.querySelector('h3');if(title)title.textContent=stage;col.ondragover=e=>{e.preventDefault();col.classList.add('drag-over')};col.ondragleave=()=>col.classList.remove('drag-over');col.ondrop=e=>{e.preventDefault();col.classList.remove('drag-over');const id=e.dataTransfer.getData('text/plain')||dragging;if(id)move(id,stage)}});[...funnel.querySelectorAll('.funnel-card')].forEach(card=>{const m=(card.getAttribute('onclick')||'').match(/openRequest\('([^']+)'\)/);if(!m)return;card.dataset.requestId=m[1];card.draggable=true;card.title='Arraste para mudar de etapa';card.ondragstart=e=>{dragging=m[1];e.dataTransfer.effectAllowed='move';e.dataTransfer.setData('text/plain',m[1]);card.classList.add('dragging')};card.ondragend=()=>{dragging=null;card.classList.remove('dragging')};card.ontouchstart=()=>{touchCard=card;card.classList.add('dragging')};card.ontouchmove=e=>{const t=e.touches[0],el=document.elementFromPoint(t.clientX,t.clientY),col=el?.closest('.funnel-col');cols.forEach(c=>c.classList.toggle('drag-over',c===col))};card.ontouchend=e=>{const t=e.changedTouches[0],el=document.elementFromPoint(t.clientX,t.clientY),col=el?.closest('.funnel-col');cols.forEach(c=>c.classList.remove('drag-over'));card.classList.remove('dragging');if(col&&touchCard)move(touchCard.dataset.requestId,col.dataset.stage);touchCard=null}})}
const css=document.createElement('style');css.textContent='.funnel-card[draggable="true"]{cursor:grab;touch-action:none}.funnel-card.dragging{opacity:.5}.funnel-col.drag-over{outline:2px dashed #176b5b;outline-offset:-4px;background:#edf8f4}.funnel-col{transition:background .15s,outline .15s}';document.head.appendChild(css);
document.addEventListener('DOMContentLoaded',()=>{normalizeStages();restoreView();setTimeout(install,250)});new MutationObserver(()=>install()).observe(document.documentElement,{childList:true,subtree:true});
})();