/* Base de dados e ficheiros reais e temporários; nunca usa credenciais/deployments. */
const fs=require('node:fs'),path=require('node:path'),os=require('node:os');
const {DatabaseSync}=require('node:sqlite');const {FinanceService}=require('../lib/finance-service');
function fixture(){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'gs-finance-')),file=path.join(dir,'data.sqlite');let db;const open=()=>{db=new DatabaseSync(file);db.exec('PRAGMA foreign_keys=ON');};open();
 const schema=fs.readFileSync(path.join(__dirname,'../db/schema.sql'),'utf8').replace(/create extension[^;]+;/gi,'').replace(/default gen_random_uuid\(\)/gi,'').replace(/default now\(\)/gi,"default CURRENT_TIMESTAMP").replace(/'\{\}'::jsonb/g,"'{}'").replace(/bigserial primary key/gi,'integer primary key');db.exec(schema);
 db.exec("CREATE TABLE IF NOT EXISTS current_account_entries(id text primary key,user_id text references users(id),clinic_id text references clinics(id),entry_date text not null,kind text not null,description text not null,value numeric not null,status text not null default 'Por pagar',paid_at text,source_type text,source_id text,data text not null default '{}',created_at text,updated_at text,unique(source_type,source_id,kind)); CREATE TABLE IF NOT EXISTS app_settings(key text primary key,value text,updated_at text,updated_by text);");
 const migration=fs.readFileSync(path.join(__dirname,'../db/migrations/finance-v4-002.sql'),'utf8').replace("UNIQUE(issuer_key,number,series)", "CHECK(1=1)").replaceAll("CHECK(status IN ('Pendente','Validada','Recusada'))", "CHECK(status IN ('Pendente','Validada','Recusada','Substituído'))").replace(/ADD COLUMN IF NOT EXISTS/gi,'ADD COLUMN').replace(/default gen_random_uuid\(\)/gi,'').replace(/default now\(\)/gi,"default CURRENT_TIMESTAMP").replace(/'\{\}'::jsonb/g,"'{}'");db.exec(migration);db.exec(fs.readFileSync(path.join(__dirname,'../db/migrations/finance-v4-003.sql'),'utf8'));
 db.exec(fs.readFileSync(path.join(__dirname,'../db/migrations/finance-v4-004.sql'),'utf8').replace(/ALTER TABLE [^;]+ (DROP|ADD) CONSTRAINT[^;]+;/g,'').replace(/ADD COLUMN IF NOT EXISTS/gi,'ADD COLUMN').replaceAll("p.data->>'paymentOf'","json_extract(p.data,'$.paymentOf')").replaceAll("data->>'paymentOf'","json_extract(data,'$.paymentOf')").replaceAll('::uuid','').replaceAll('::text','').replace('FROM finance_payslips ON CONFLICT','FROM finance_payslips WHERE 1=1 ON CONFLICT'));
 const run=(q,p=[])=>{const values=[];q=q.replace(/\$(\d+)/g,(_,i)=>{values.push(p[Number(i)-1]??null);return'?' });return db.prepare(q).all(...values.map(x=>typeof x==='boolean'?+x:x))};
 const repo={query:async(q,p)=>run(q,p),batch:async statements=>{db.exec('BEGIN');try{const values=statements.map(s=>run(s.sql,s.params));db.exec('COMMIT');return values}catch(e){db.exec('ROLLBACK');throw e}}};
 const storage={put:async(key,bytes,mime)=>{const f=path.join(dir,key);fs.mkdirSync(path.dirname(f),{recursive:true});fs.writeFileSync(f,bytes);return{key}},remove:async key=>{fs.rmSync(path.join(dir,key),{force:true})},get:async key=>({bytes:fs.readFileSync(path.join(dir,key))})};
 const service=new FinanceService(repo,storage),roles=['CEO','Administração','Administrativa','Call Center','Médico/a','Técnico/a'];roles.forEach((role,i)=>{run('insert into users(id,name,email,role,active) values($1,$2,$3,$4,1)',['p'+i,'Pessoa '+i,'p'+i+'@example.pt',role]);run('insert into employees(id,user_id,name,data) values($1,$2,$3,$4)',['e'+i,'p'+i,'Pessoa '+i,JSON.stringify({nif:'tax-'+i,clinics:['clinic']})])});
 return{service,repo,storage,dir,run,reopen(){db.close();open()},close(){db.close();fs.rmSync(dir,{recursive:true,force:true})}};
}
module.exports={fixture};
