/* Execute the actual presentation and demonstration adapter; DOM is simulated, not a browser. */
const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),assert=require('node:assert/strict');
const root=path.join(__dirname,'..'),KEY='grupo_saude_v4_demo_2';
const original=fs.readFileSync(path.join(__dirname,'runtime.cjs'),'utf8');
const loader={URL,require,__dirname:path.join(__dirname),console,module:{exports:{}}};vm.createContext(loader);vm.runInContext(original.slice(0,original.indexOf('let passed=0;'))+'\nmodule.exports=environment;',loader);const environment=loader.module.exports;
let passed=0;async function test(n,fn){await fn();passed++;console.log('PASS finance UI:',n)}
function fixture(){const e=environment();e.context.URLSearchParams=URLSearchParams;e.context.TextEncoder=TextEncoder;e.context.Blob=Blob;e.context.crypto=require('node:crypto').webcrypto;e.context.atob=atob;e.context.fetch=fetch;e.context.FormData=FormData;for(const f of ['app.js','access-scope-v4.js','access-policy-core-v4.js','role-access-admin-v4.js'])e.run(f);for(const f of ['finance-core-v4.js','finance-demo-v4.js','finance-ui-v4.js'])e.run(f);const content=e.document.createElement('div');e.elements.set('financeContent',content);return e}
const doc=id=>({name:id+'.pdf',dataUrl:'data:application/pdf;base64,'+Buffer.from('%PDF-1.4\nUI test '+id).toString('base64')}),period={start:'2026-01-01',end:'2026-12-31'},invoice=id=>({number:id,invoiceDate:'2026-10-09',insertedDate:'2026-10-09',value:'50.25',document:doc(id)});
(async()=>{const actors=['u1','test_admin','test_adm','test_call','test_med','test_tec'];
 for(const id of actors)await test('direct three sections, own account and management role '+id,async()=>{const e=fixture(),s=e.read();s.currentUser=id;s.ceoRealUser='u1';s.finance={movements:[{id:'own-'+id,employeeId:id,person:'OWN',description:'OWN-FIN-'+id,type:'Consulta',value:100,status:'Por pagar',date:'2026-10-09'},{id:'secret',employeeId:'alien',person:'PRIVATE-FINANCE',type:'Consulta',value:999,status:'Por pagar',date:'2026-10-09'}]};e.write(s);for(const section of ['account','invoices','payslips']){await e.context.FinanceUIV4.open(section);const html=e.elements.get('financeContent').innerHTML;assert(html.includes('Faturas'));assert(html.includes('Recibos de Vencimento'));assert(html.includes('Conta corrente'));assert(!html.includes('NaN'));const isManager=['u1','test_admin'].includes(id);assert.equal(html.includes('data-fin-action="manage"'),isManager);assert(!html.includes('PRIVATE-FINANCE'));if(section==='account')assert(html.includes('100,00')||html.includes('100.00'));if(!isManager)assert(!html.includes('+ Bónus trimestral'))}const x=await e.context.FinanceUIV4.call('invoice-upload',{...invoice('own-'+id),employeeId:'u1'});assert.equal(x.employeeId,id);if(!['u1','test_admin'].includes(id)){await assert.rejects(()=>e.context.FinanceUIV4.call('entry-create',{employeeId:id,type:'Consulta',value:1,date:'2026-10-09'}),/exclusiva/);await assert.rejects(()=>e.context.FinanceUIV4.call('statement',{...period,employeeId:'u1'}),/autoriza/)}await e.context.FinanceUIV4.open('invoices');assert(e.elements.get('financeContent').innerHTML.includes(('own-'+id).toUpperCase()))});
 await test('invoice decision and payslip workflow, notifications, file ownership and corrected history',async()=>{const e=fixture(),switchTo=id=>{const s=e.read();s.currentUser=id;e.write(s);e.document.dispatchEvent({type:'gs:user-changed'})};switchTo('test_med');const x=await e.context.FinanceUIV4.call('invoice-upload',invoice('flow'));switchTo('u1');let bootstrap=await e.context.FinanceDemoV4.bootstrap();assert.equal(bootstrap.notifications.invoicesPending,1);await e.context.FinanceUIV4.call('invoice-decision',{id:x.id,revision:0,status:'Validada'});assert.equal((await e.context.FinanceDemoV4.bootstrap()).notifications.invoicesPending,0);const receipt=await e.context.FinanceUIV4.call('receipt-upload',{employeeId:'test_med',year:2026,month:10,documentDate:'2026-10-09',document:doc('receipt')});switchTo('test_med');await assert.rejects(()=>e.context.FinanceUIV4.call('document',{id:receipt.documentId}),/autorizado/);switchTo('u1');await e.context.FinanceUIV4.call('receipt-associate',{id:receipt.id,revision:0,employeeId:'test_med',year:2026,month:10,documentDate:'2026-10-09',confirmed:true});switchTo('test_med');assert.equal((await e.context.FinanceDemoV4.bootstrap()).notifications.newReceipts,1);assert((await e.context.FinanceUIV4.call('document',{id:receipt.documentId})).dataUrl);await e.context.FinanceUIV4.call('receipt-read',{id:receipt.id});assert.equal((await e.context.FinanceDemoV4.bootstrap()).notifications.newReceipts,0);assert.equal((await e.context.FinanceUIV4.call('statement',period)).finalCents,5025);switchTo('test_tec');await assert.rejects(()=>e.context.FinanceUIV4.call('document',{id:receipt.documentId}),/autorizado/);await assert.rejects(()=>e.context.FinanceUIV4.call('history',{kind:'invoice',id:x.id}),/autorizado/)});
 await test('switch mid-upload never writes document or invoice to another profile',async()=>{const e=fixture(),s=e.read();s.currentUser='test_med';e.write(s);const pending=e.context.FinanceUIV4.call('invoice-upload',invoice('race'));const next=e.read();next.currentUser='test_tec';e.write(next);e.document.dispatchEvent({type:'gs:user-changed'});await assert.rejects(()=>pending,/mudaram|mudou/);assert(!(e.read().financeV2?.invoices||[]).length)});
 await test('stored legacy records remain intact and appear in canonical date-filtered account',async()=>{const e=fixture(),s=e.read();s.currentUser='test_med';s.finance={movements:[{id:'legacy',employeeId:'test_med',person:'Doctor',type:'Consulta',value:50,date:'2026-09-01',status:'Pago',paidAt:'2026-09-05'}],acts:[{id:'kept-act'}],bonusRules:[{id:'kept-bonus'}]};s.currentAccounts={test_med:{movements:[{id:'separate',type:'Bónus',value:20,date:'2026-09-02',status:'Por pagar'}]}};e.write(s);const original=JSON.stringify(s.finance);const r=await e.context.FinanceUIV4.call('statement',{employeeId:'test_med',...period});assert.equal(r.finalCents,2000);assert.equal(r.paymentsCents,5000);assert.equal(JSON.stringify(e.read().finance),original)});
 await test('revoked permissions clear private UI immediately, direct calls forbidden',async()=>{const e=fixture(),s=e.read();s.currentUser='test_med';e.write(s);await e.context.FinanceUIV4.open('account');assert(e.elements.get('financeContent').innerHTML.includes('Conta corrente'));const next=e.read();next.userActionPermissions={test_med:{account:false}};e.write(next);e.document.dispatchEvent({type:'gs:permissions-applied'});assert.equal(e.elements.get('financeContent').innerHTML,'');await assert.rejects(()=>e.context.FinanceUIV4.call('bootstrap'),/autorização/)});
 await test('secure standalone fails closed and never invokes local adapter',async()=>{const e=environment();e.context.URLSearchParams=URLSearchParams;e.context.TextEncoder=TextEncoder;e.context.Blob=Blob;e.context.FormData=FormData;e.context.crypto=require('node:crypto').webcrypto;e.document.documentElement.dataset.finance='server';e.context.fetch=async()=>new Response(JSON.stringify({error:'Backend não configurado'}),{status:503});e.context.FinanceDemoV4={call(){throw Error('Local fallback forbidden')}};const content=e.document.createElement('div');e.elements.set('financeContent',content);e.run('finance-core-v4.js');e.run('finance-ui-v4.js');await e.context.FinanceUIV4.open('account');assert(content.innerHTML.includes('Backend não configurado'));assert(!content.innerHTML.includes('Local fallback'))});

 await test('legacy pending approval preserves original arrays, new adjustments may debit',async()=>{const e=fixture(),s=e.read();s.currentUser='u1';s.finance={movements:[{id:'oldpending',employeeId:'test_med',type:'Consulta',value:30,date:'2026-10-09',status:'Pendente'}]};e.write(s);await e.context.FinanceUIV4.call('entry-approve',{id:'oldpending'});assert.equal(e.read().finance.movements[0].status,'Pendente');const before=e.read().financeV2.events.length;await e.context.FinanceUIV4.call('entry-approve',{id:'oldpending'});assert.equal(e.read().financeV2.events.length,before);const credit=await e.context.FinanceUIV4.call('entry-create',{employeeId:'test_med',type:'Ajuste',value:'-5',date:'2026-10-09',idempotencyKey:'negative'});await e.context.FinanceUIV4.call('entry-approve',{id:credit.id});const r=await e.context.FinanceUIV4.call('statement',{employeeId:'test_med',...period});assert.equal(r.finalCents,2500)});

 await test('paid demo invoice replacement preserves documents, requires regularization and zeroes original only on approval',async()=>{const e=fixture(),go=id=>{const s=e.read();s.currentUser=id;e.write(s);e.document.dispatchEvent({type:'gs:user-changed'})},call=(a,b)=>e.context.FinanceDemoV4.call(a,b);go('test_med');const x=await call('invoice-upload',invoice('original-demo'));go('u1');await call('invoice-decision',{id:x.id,revision:0,status:'Validada'});const old=e.read().financeV2.entries[0];await call('payment-create',{entryId:old.id,value:'50.25',date:'2026-10-09',idempotencyKey:'paid-demo'});go('test_med');const child=await call('invoice-upload',{...invoice('original-demo'),document:doc('replacement-demo'),value:'60.25',replacementOf:x.id,replacementReason:'Correção'});assert.equal((await call('statement',period)).finalCents,0);go('u1');await call('invoice-decision',{id:child.id,revision:0,status:'Validada',reason:'Verificado'});const state=e.read();assert.equal(state.financeV2.invoices.find(p=>p.id===x.id).status,'Substituído');assert.equal(state.financeV2.entries.find(p=>p.id===old.id).valueCents,0);const reg=state.financeV2.regularizations[0];await assert.rejects(()=>call('payment-create',{entryId:reg.newEntryId,value:'10',date:'2026-10-09',idempotencyKey:'too-soon'}),/regularização/);await call('regularization-decision',{id:reg.id,revision:0,status:'Aprovada',reason:'Pagamento associado'});assert.equal((await call('statement',{...period,employeeId:'test_med'})).finalCents,1000);assert((await call('document',{id:x.documentId})).dataUrl);go('test_med');await assert.rejects(()=>call('regularization-list',{}),/exclusiva/);assert.equal((await call('statement',period)).finalCents,1000)});

 await test('demo financial identity continues to use the employee tax number and settings revocations hide configuration controls',async()=>{const e=fixture(),s=e.read();s.currentUser='test_med';s.employees.test_med.hr||={};s.employees.test_med.hr.nif='PT123456789';e.write(s);const x=await e.context.FinanceDemoV4.call('invoice-upload',invoice('tax-preserved'));assert.equal(x.issuerKey,'PT123456789');const next=e.read();next.currentUser='test_admin';next.userActionPermissions={test_admin:{settings:false}};e.write(next);await e.context.FinanceUIV4.open('manage');const html=e.elements.get('financeContent').innerHTML;assert(!html.includes('data-fin-action="archive-list"'));assert(!html.includes('data-fin-action="email"'));assert(html.includes('data-fin-action="act"'))});
 console.log(JSON.stringify({passed,scope:'Actual UI/controller/adapter with simulated DOM; no live browser'}));})().catch(e=>{console.error(e);process.exitCode=1});
