'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const {fixture}=require('./finance-fixture.cjs'),Mail=require('../lib/finance-payment-email'),Attention=require('../lib/attention-service'),A=require('../attention-core-v4'),P=require('../access-policy-core-v4');
let passed=0;async function test(name,fn){await fn();passed++;console.log('PASS improvements:',name)}
const policy=(role,id='a',overrides={})=>({active:true,can:key=>overrides[key]??P.defaults(P.norm(role)).includes(key),employee:uid=>uid===id||['CEO','Administração'].includes(role),clinic:cid=>cid==='active'});
(async()=>{const f=fixture(),s=f.service;try{
 f.run("insert into clinics(id,name,active) values('clinic','Clínica autorizada',1),('other','Outra clínica',1),('inactive','Inativa',0)");const actors=await s.people(),ceo=actors.find(x=>x.role==='CEO'),admin=actors.find(x=>x.role==='Administração'),doctor=actors.find(x=>x.id==='p4');
 await test('six roles: only managers receive finance approval counts; staff see own invoices only',()=>{for(const role of ['CEO','Administração','Administrativa','Call Center','Médico/a','Técnico/a']){const items=A.collect({currentUser:'a',financeV2:{invoices:[{id:'i',employeeId:'b',status:'Pendente'},{id:'own',employeeId:'a',status:'Recusada'}]}},policy(role));assert.equal(items.some(x=>x.entityId==='i'),['CEO','Administração'].includes(role));assert(items.some(x=>x.entityId==='own'))}});
 await test('counts 0, 1, 99+; source and parent dedup; reading does not resolve approval',()=>{const state={currentUser:'a',financeV2:{invoices:Array.from({length:105},(_,i)=>({id:'i'+i,status:'Pendente'}))}},p=policy('CEO');assert.equal(A.count([], 'finance'),0);assert.equal(A.label(1),'1');assert.equal(A.label(105),'99+');state.financeV2.invoices.push(state.financeV2.invoices[0]);let items=A.collect(state,p);assert.equal(A.count(items,'finance'),105);state.attentionRead={a:{[items[0].id]:{readAt:'now'}}};items=A.collect(state,p);assert(items[0].readAt);assert.equal(items.length,105);state.financeV2.invoices[0].status='Validada';state.financeV2.invoices.pop();assert.equal(A.collect(state,p).length,104)});
 await test('scope excludes inactive/unauthorized clinics, stranger chat and disabled modules',()=>{const state={currentUser:'a',requests:[{id:'one',clinic:'active',stage:'Novo'},{id:'two',clinic:'inactive',stage:'Novo'},{id:'three',clinic:'other',stage:'Novo'}],conversations:[{id:'c',members:['b'],messages:[{id:'secret',from:'b',readBy:[]}]}]};assert.deepEqual(A.collect(state,policy('Administrativa')).map(x=>x.entityId),['one']);assert.equal(A.collect(state,policy('Administrativa','a',{waiting:false})).length,0);assert.equal(A.collect(state,{...policy('CEO'),active:false}).length,0)});
 await test('backend scopes requests/candidates and never accepts client role or recipient',async()=>{f.run("insert into requests(id,clinic_id,stage) values('r1','clinic','Novo'),('r2','other','Novo'),('r3','inactive','Novo')");f.run("insert into candidates(id,clinic_id,stage) values('c1','clinic','Novo'),('c2','other','Novo')");const list=await Attention.list(s,admin);assert(list.some(x=>x.entityId==='r1'));assert(!list.some(x=>['r2','r3','c2'].includes(x.entityId)));assert((await Attention.list(s,ceo)).some(x=>x.entityId==='r2'));assert(!(await Attention.list(s,doctor)).some(x=>x.kind==='request'));await assert.rejects(()=>Attention.mark(s,doctor,{id:list[0].id,role:'CEO',recipientId:admin.id}),/autorização/)});
 await test('backend persists reads across sessions; action counts survive read; only informational events can resolve',async()=>{const item=(await Attention.list(s,admin)).find(x=>x.entityId==='r1');await Attention.mark(s,admin,{id:item.id});f.reopen();assert((await Attention.list(s,admin)).find(x=>x.id===item.id).readAt);await assert.rejects(()=>Attention.mark(s,admin,{id:item.id},true),/decisão/);assert(!(await Attention.list(s,{...admin,permissions:{waiting:false}})).some(x=>x.id===item.id))});
 const credit=await s.createEntry(ceo,{employeeId:doctor.id,type:'Consulta',date:'2026-10-01',description:'Atos profissionais',value:100,idempotencyKey:'mail-credit'});await s.approveEntry(admin,{id:credit.id});const payment1=await s.payment(ceo,{entryId:credit.id,value:40,date:'2026-10-09',idempotencyKey:'mail-payment-1'}),payment2=await s.payment(admin,{entryId:credit.id,value:60,date:'2026-10-09',idempotencyKey:'mail-payment-2'});
 await test('two payments same day enqueue two individual mails atomically with recipient and correct amount',()=>{const rows=f.run('select * from finance_payment_mail');assert.equal(rows.length,2);assert(rows.every(x=>x.recipient===doctor.email));assert.deepEqual(rows.map(x=>JSON.parse(x.payload).valueCents).sort((a,b)=>a-b),[4000,6000]);assert(rows.every(x=>x.status==='Queued'))});
 await test('payment retry is idempotent and cannot enqueue duplicate mail',async()=>{assert((await s.payment(ceo,{entryId:credit.id,value:40,date:'2026-10-09',idempotencyKey:'mail-payment-1'})).duplicate);assert.equal(f.run('select count(*) n from finance_payment_mail')[0].n,2)});
 const env={GS_FINANCE_ENVIRONMENT:'preview',GS_PAYMENT_EMAIL_API_KEY:'test-only',GS_PAYMENT_EMAIL_FROM:'test@example.pt'};let sends=0;const request=async(url,options)=>{sends++;assert.equal(url,'https://api.resend.com/emails');const body=JSON.parse(options.body);assert.deepEqual(body.to,[doctor.email]);assert(body.text.includes('Atos profissionais'));assert(options.headers['Idempotency-Key'].startsWith('gs-payment-'));return Response.json({id:'test-delivery-'+sends})};
 await test('unconfigured or production mailer fails closed without external requests',async()=>{let n=0;assert.equal((await Mail.send(s,ceo,payment1.id,{},()=>{n++})).status,'Queued');assert.equal((await Mail.send(s,ceo,payment1.id,{...env,VERCEL_ENV:'production'},()=>{n++})).status,'Queued');assert.equal(n,0)});
 await test('concurrent delivery claims yield one actual request and permanent Sent dedup',async()=>{const results=await Promise.all([Mail.send(s,ceo,payment1.id,env,request),Mail.send(s,admin,payment1.id,env,request)]);assert(results.some(x=>x.status==='Sent'));assert.equal(sends,1);assert((await Mail.send(s,ceo,payment1.id,env,request)).duplicate);assert.equal(sends,1);assert(f.run("select * from finance_events where action='Sent'").length)});
 await test('one mail per additional payment, correct independent idempotency keys',async()=>{assert.equal((await Mail.send(s,admin,payment2.id,env,request)).status,'Sent');assert.equal(sends,2);assert.equal(f.run("select count(*) n from finance_payment_mail where status='Sent'")[0].n,2)});
 await test('own payment notification separates read and resolved; staff cannot resolve another person’s',async()=>{const own=(await Attention.list(s,doctor)).filter(x=>x.kind==='payment');assert.equal(own.length,2);await Attention.mark(s,doctor,{id:own[0].id});assert.equal((await Attention.list(s,doctor)).filter(x=>x.kind==='payment').length,2);await assert.rejects(()=>Attention.mark(s,actors.find(x=>x.id==='p5'),{id:own[0].id},true),/autorização/);await Attention.mark(s,doctor,{id:own[0].id},true);assert.equal((await Attention.list(s,doctor)).filter(x=>x.kind==='payment').length,1)});
 await test('all non-management profiles are denied delivery, retry and recipient list',async()=>{for(const a of actors.filter(x=>!['CEO','Administração'].includes(x.role))){await assert.rejects(()=>Mail.list(s,a),/exclusiva/);await assert.rejects(()=>Mail.send(s,a,payment1.id,env,request),/exclusiva/)}await assert.rejects(()=>Mail.list(s,{...ceo,permissions:{financeManage:false}}),/exclusiva/)});
 async function newPayment(key){const x=await s.createEntry(ceo,{employeeId:doctor.id,type:'Ato',date:'2026-10-01',description:'Pagamento '+key,value:20,idempotencyKey:key});await s.approveEntry(ceo,{id:x.id});return s.payment(ceo,{entryId:x.id,value:20,date:'2026-10-09',idempotencyKey:key})}
 const rejected=await newPayment('provider-rejection');await test('explicit provider rejection supports audited manual retry with same provider key',async()=>{let key;assert.equal((await Mail.send(s,ceo,rejected.id,env,async(_,o)=>{key=o.headers['Idempotency-Key'];return Response.json({}, {status:429})})).status,'Failed');await assert.rejects(()=>Mail.send(s,ceo,rejected.id,env,request,{retry:true}),/motivo/);assert.equal((await Mail.send(s,ceo,rejected.id,{},request,{retry:true,reason:'Sem fornecedor'})).status,'Failed');assert.equal((await Mail.send(s,ceo,rejected.id,env,async(_,o)=>{assert.equal(o.headers['Idempotency-Key'],key);return Response.json({id:'safe-retry'})},{retry:true,reason:'Limite temporário resolvido'})).status,'Sent')});
 const uncertain=await newPayment('unknown');await test('timeout/unknown delivery never auto-retries and logs only sanitized error',async()=>{assert.equal((await Mail.send(s,ceo,uncertain.id,env,async()=>{throw Error('secret-test-token')})).status,'Uncertain');let calls=0;assert.equal((await Mail.send(s,ceo,uncertain.id,env,()=>{calls++},{retry:true,reason:'retry'})).status,'Uncertain');assert.equal(calls,0);assert(!JSON.stringify(f.run('select * from finance_payment_mail')).includes('secret-test-token'))});
 const expired=await newPayment('expired');await test('retry after provider idempotency window requires reconciliation, never duplicate sending',async()=>{f.run('update finance_payment_mail set first_attempt_at=$1 where payment_id=$2',['2020-01-01T00:00:00Z',expired.id]);let calls=0;assert.equal((await Mail.send(s,ceo,expired.id,env,()=>{calls++})).status,'Uncertain');assert.equal(calls,0)});
 const reverted=await newPayment('reversed');await test('reversed pending payment cannot send; reactivation of previously sent payment cannot resend',async()=>{await s.paymentState(ceo,{id:reverted.id,status:'Pendente',reason:'Correção'});let calls=0;assert.equal((await Mail.send(s,ceo,reverted.id,env,()=>{calls++})).status,'Cancelled');assert.equal(calls,0);assert.equal(f.run('select status from finance_payment_mail where payment_id=$1',[reverted.id])[0].status,'Cancelled');await s.paymentState(ceo,{id:reverted.id,status:'Pago',reason:'Confirmado'});assert.equal(f.run('select status from finance_payment_mail where payment_id=$1',[reverted.id])[0].status,'Queued');await s.paymentState(ceo,{id:payment1.id,status:'Pendente',reason:'Teste'});await s.paymentState(ceo,{id:payment1.id,status:'Pago',reason:'Confirmado novamente'});assert((await Mail.send(s,ceo,payment1.id,env,request)).duplicate)});
 await test('notification derivation scales and preserves sources without mutation',()=>{const state={currentUser:'a',employeeDocuments:{a:Array.from({length:3000},(_,i)=>({id:'d'+i,status:'Em falta'}))}},before=JSON.stringify(state),start=performance.now();assert.equal(A.collect(state,policy('CEO')).length,3000);assert(performance.now()-start<1500);assert.equal(JSON.stringify(state),before)});
 await test('financial document links do not double-count the same invoice approval',()=>{const state={currentUser:'a',financeV2:{invoices:[{id:'invoice',employeeId:'a',documentId:'document',status:'Pendente'}]},employeeDocuments:{a:[{id:'document',status:'Pendente'},{id:'finance:document',financeDocumentId:'document',status:'Pendente'}]}};assert.equal(A.collect(state,policy('CEO')).length,1)});
 await test('marketing, security and latest email execution counts exclude historical resolved errors',()=>{const state={currentUser:'a',marketing:{campaigns:[{id:'campaign',clinic:'active',status:'Pendente de aprovação'},{id:'published',clinic:'active',status:'Publicado'}]},security:{backups:[{id:'backup',status:'Failed'}]},communicationRuns:[{id:'old-error',kind:'email',sourceId:'same',status:'Erro',at:'2026-01-01'},{id:'resolved',kind:'email',sourceId:'same',status:'Concluído',at:'2026-01-02'},{id:'still-error',kind:'email',sourceId:'other',status:'Erro',at:'2026-01-02'}]};const list=A.collect(state,policy('CEO'));assert.equal(A.count(list,'marketing'),1);assert.equal(A.count(list,'security'),1);assert.equal(A.count(list,'tables'),1);assert(!list.some(x=>x.entityId==='old-error'))});
 await test('mail delivery issues appear only to managers and disappear after recorded resolution',async()=>{let list=await Attention.list(s,ceo);assert(list.some(x=>x.kind==='payment-mail'));assert(!(await Attention.list(s,doctor)).some(x=>x.kind==='payment-mail'));f.run("update finance_payment_mail set status='Sent' where status='Uncertain'");list=await Attention.list(s,ceo);assert(!list.some(x=>x.kind==='payment-mail'))});
 // Execute actual theme code using the existing simulated DOM, not a mirrored implementation.
 await test('theme belongs to active user and changing profile restores each preference',()=>{const source=fs.readFileSync(path.join(__dirname,'runtime.cjs'),'utf8'),loader={URL,require,__dirname,console,module:{exports:{}}};vm.createContext(loader);vm.runInContext(source.slice(0,source.indexOf('let passed=0;'))+'\nmodule.exports=environment;',loader);const e=loader.module.exports({currentUser:'a'});e.run('workspace-shell-v4.js');e.context.localStorage.setItem('gs-v4-theme:a','dark');e.context.WorkspaceShellV4.applyTheme();assert.equal(e.document.documentElement.dataset.theme,'dark');e.write({currentUser:'b'});e.context.WorkspaceShellV4.applyTheme();assert.equal(e.document.documentElement.dataset.theme,'light');e.write({currentUser:'a'});e.context.WorkspaceShellV4.applyTheme();assert.equal(e.document.documentElement.dataset.theme,'dark')});
 await test('RH clinic authorization blocks direct read and leave approval outside Administration scope',()=>{const src=fs.readFileSync(path.join(__dirname,'runtime.cjs'),'utf8'),loader={URL,require,__dirname,console,module:{exports:{}}};vm.createContext(loader);const core=src.match(/function core\(\)\{[^\n]+/)[0];vm.runInContext(src.slice(0,src.indexOf('let passed=0;'))+core+'\nmodule.exports=core;',loader);const e=loader.module.exports(),state=e.read();state.currentUser='test_admin';state.clinics=[{id:'c1',active:true},{id:'c2',active:true}];state.employees.test_admin.clinics=['c1'];state.employees.test_med.clinics=['c2'];state.leave=[{id:'forbidden-leave',employeeId:'test_med',clinicId:'c2',type:'Férias',days:['2026-10-09'],status:'Pendente'}];e.write(state);assert(!e.context.HRLeaveV4.canRead(state,state.leave[0]));assert.throws(()=>e.context.HRLeaveV4.decide('forbidden-leave','Aprovado'),/autorização/);assert.equal(e.read().leave[0].status,'Pendente')});
 await test('central master preserves other employee drafts and exact-identifier history isolation',()=>{const src=fs.readFileSync(path.join(__dirname,'runtime.cjs'),'utf8'),loader={URL,require,__dirname,console,module:{exports:{}}};vm.createContext(loader);const core=src.match(/function core\(\)\{[^\n]+/)[0];vm.runInContext(src.slice(0,src.indexOf('let passed=0;'))+core+'\nmodule.exports=core;',loader);const e=loader.module.exports();e.run('hr-master-v4.js');const state=e.read();state.users.push({id:'existing-draft',name:'Preservar',_new:true,hr:{}});e.write(state);e.context.HRMasterV4.create();assert(e.read().users.some(x=>x.id==='existing-draft'));const next=e.read();next.currentUser='test_med';next.audit=[{action:'OwnAction',userId:'test_med'},{action:'StrangerPrivateAction',detail:next.employees.test_med.name+' Another',userId:'different-person'}];e.write(next);e.context.HRMasterV4.open('test_med','historico');const html=e.elements.get('modalBody').innerHTML;assert(html.includes('OwnAction'));assert(!html.includes('StrangerPrivateAction'))});
 console.log(JSON.stringify({passed,scope:'Notification permissions, persistent SQL reads/outbox, real concurrent claims, mocked email provider, actual theme controller; no live credentials'}));
}finally{f.close()}})().catch(e=>{console.error(e);process.exitCode=1});
