/* Regressões de domínio, renderização e privacidade para a tarefa #8. */
module.exports=({core,test,assert,vm,flat,actor,leaveFixture})=>{
 function fixture(){const e=leaveFixture(),s=e.read();for(const [id,name] of [['peer2','Colega Dois'],['peer3','Colega Três']])s.users.push({id,name,role:'MEDICO/A',clinics:['c1'],active:true});s.hrPerformance=[{id:'legacy',custom:'preservar'}];s.payments=[{id:'keep-payment',amount:100}];s.currentAccounts={p:{movements:[{amount:10}]}};s.audit=[];e.write(s);return e}
 const rules=e=>{const P=e.context.HRPerformanceV4,r=P.defaults();r.peerEnabled=true;return P.approveRules(r,'Validar versão inicial')};
 const answers=c=>Object.fromEntries(c.map(q=>[q.id,4]));
 function proposal(e,extra={}){const P=e.context.HRPerformanceV4,r=P.rules();return P.submitEvaluation({employeeId:'p',kind:'Mensal',period:'2026-10',scores:answers(r.criteria),objectives:[{title:'Melhorar processos',target:'Concluir plano',progress:30}],feedback:'Bom trabalho e oportunidades de melhoria',reason:'Avaliação regular',...extra})}
 const cycle=e=>e.context.HRPerformanceV4.openCycle({clinicId:'c1',kind:'Mensal',period:'2026-10',reason:'Ciclo piloto'});
 test('issue8: calendar precedes details/history for CEO and own employee',()=>{const e=fixture(),U=e.context.HRLeaveUIV4;for(const id of ['u1','p']){actor(e,id);assert(U.open('original'));const html=e.elements.get('modalBody').innerHTML;assert(html.indexOf('id="leaveContext"')<html.indexOf('Clínica'));assert(html.indexOf('id="leaveContext"')<html.indexOf('Histórico'));assert(e.elements.get('leaveContext').innerHTML.includes('leave-grid'));if(id==='p')assert(!e.elements.get('leaveContext').innerHTML.includes('Colega'))}});
 test('issue8: approvals list shares calendars and independently navigates each request',()=>{const e=fixture(),s=e.read();s.leave.find(x=>x.id==='original').status='Pendente';e.write(s);e.context.ApprovalsV4.open('vac');const body=e.elements.get('modalBody').innerHTML;assert(body.includes('approvalCalendar_0'));assert(!body.includes('2026-07-06, 2026-07-07'));const before=e.elements.get('approvalCalendar_0').innerHTML;assert(before.includes('leave-grid'));const b=e.document.createElement('button');b.dataset.leaveAction='context-next';b.dataset.leaveId='original';b.click();assert(e.elements.get('approvalCalendar_0').innerHTML.includes('agosto'));assert.notEqual(e.elements.get('approvalCalendar_0').innerHTML,before)});
 test('issue8: monthly calendar displays peers outside requested days and correct daily coverage',()=>{const e=fixture(),s=e.read(),D=e.context.HRLeaveV4,U=e.context.HRLeaveUIV4;s.leave.push({id:'outside',employeeId:'peer',type:'Férias',days:['2026-07-20'],status:'Aprovado'});e.write(s);const x=s.leave.find(x=>x.id==='original'),html=U.calendarMarkup(s,x,'2026-07','c1');assert(html.includes('20/07/2026'));const info=D.context(s,x,['2026-07-20'],'c1',D.days(x));assert.equal(info.coverage[0].absent,1);assert.equal(info.coverage[0].available,3)});
 test('issue8: employee master offers direct partial edit only with authorization and preserves balance',()=>{const e=fixture();e.run('hr-master-v4.js');e.context.HRMasterV4.open('p','ferias');const html=e.elements.get('modalBody').innerHTML;assert(html.includes('Editar / Reagendar'));assert(html.includes('data-leave-action="edit"'));e.context.HRLeaveV4.requestChange('original',['2026-07-07'],['2026-08-03'],'Teste ficha');assert.equal(e.context.HRLeaveV4.balance(e.read(),'p',2026).approved,5);actor(e,'p');e.context.HRMasterV4.open('p','ferias');assert(!e.elements.get('modalBody').innerHTML.includes('Editar / Reagendar'));const before=e.elements.get('modalBody').innerHTML;e.context.HRMasterV4.open('peer','dados');assert.equal(e.elements.get('modalBody').innerHTML,before)});
 test('issue8: rules require CEO, unique criteria, valid weights and anonymity floor',()=>{const e=fixture(),P=e.context.HRPerformanceV4,r=P.defaults(),before=e.read();actor(e,'admin');assert.throws(()=>P.approveRules(r,'Tentativa'),/CEO/);actor(e,'u1');for(const input of [{...r,threshold:2},{...r,criteria:r.criteria.map(x=>({...x,weight:1}))},{...r,criteria:[{id:'same',label:'A',weight:50},{id:'same',label:'B',weight:50}]}])assert.throws(()=>P.approveRules(input,'Teste'));assert.equal(e.read().hrPerformanceRuleVersions,undefined);const x=rules(e);assert.equal(x.version,1);assert.equal(e.read().hrPerformance[0].custom,'preservar');assert.deepEqual(e.read().payments,before.payments)});
 test('issue8: empty/unvalidated proposals, invalid periods and incomplete scores never write',()=>{const e=fixture(),P=e.context.HRPerformanceV4;assert.throws(()=>proposal(e),/validar/);rules(e);const before=e.read();for(const extra of [{period:'2026-13'},{kind:'Mensal',period:'2026-2'},{feedback:''},{scores:{}},{objectives:[{title:'Meta',progress:101}]},{scores:Object.fromEntries(P.rules().criteria.map(q=>[q.id,'4']))}])assert.throws(()=>proposal(e,extra));assert.deepEqual(e.read(),before);assert.equal(P.period('Trimestral','2026-T1').end,'2026-03-31');assert.equal(P.period('Anual','2028').end,'2028-12-31')});
 test('issue8: administrative proposal calculates score but requires CEO validation to publish',()=>{const e=fixture(),P=e.context.HRPerformanceV4;rules(e);actor(e,'admin');const x=proposal(e);assert.equal(x.score,4);assert.equal(P.evaluations('p')[0].status,'Proposta');assert.throws(()=>P.decideEvaluation(x.id,'Validada','Confirmar'),/CEO/);actor(e,'p');assert.equal(P.evaluations().length,0);actor(e,'u1');P.decideEvaluation(x.id,'Validada','Concordo');actor(e,'p');assert.equal(P.evaluations()[0].status,'Validada');assert.equal(P.evaluations()[0].objectives[0].progress,30);assert.throws(()=>P.evaluations('peer'));assert(e.read().alerts.some(a=>a.to==='p'&&a.action==='performanceDetail'))});
 test('issue8: decisions and revisions append records without modifying originals or financial data',()=>{const e=fixture(),P=e.context.HRPerformanceV4;rules(e);const x=proposal(e),first=e.read().hrPerformance.find(v=>v.id===x.id),money=e.read().payments;P.decideEvaluation(x.id,'Validada','Confirmar');assert.throws(()=>P.decideEvaluation(x.id,'Validada','Duplicação'));assert.throws(()=>proposal(e),/referenciar/);const y=proposal(e,{supersedes:x.id,feedback:'Plano revisto',reason:'Nova evidência'});P.decideEvaluation(y.id,'Validada','Revisão validada');assert.deepEqual(e.read().hrPerformance.find(v=>v.id===x.id),first);assert.equal(P.evaluations('p').length,2);assert.deepEqual(e.read().payments,money);assert.deepEqual(e.read().currentAccounts.p.movements,[{amount:10}]);assert.equal(e.read().hrPerformanceEvents.length,2)});
 test('issue8: duplicate pending and rejected proposals preserve all prior history',()=>{const e=fixture(),P=e.context.HRPerformanceV4;rules(e);const x=proposal(e);assert.throws(()=>proposal(e),/pendente/);assert.throws(()=>P.decideEvaluation(x.id,'Recusada',''));P.decideEvaluation(x.id,'Recusada','Corrigir critérios');const y=proposal(e);assert.notEqual(y.id,x.id);assert.equal(P.evaluations('p').find(x=>x.id===y.id).status,'Proposta');assert.equal(P.evaluations('p').find(v=>v.id===x.id).status,'Recusada');actor(e,'p');assert.equal(P.evaluations().length,0)});
 test('issue8: rules are versioned; old evaluations and cycles keep original snapshots',()=>{const e=fixture(),P=e.context.HRPerformanceV4;rules(e);const x=proposal(e),c=cycle(e),next=P.rules();next.threshold=4;next.criteria.reverse();P.approveRules(next,'Novas regras');assert.equal(P.rules().version,2);assert.equal(e.read().hrPerformance.find(v=>v.id===x.id).rules.version,1);assert.equal(P.cycles()[0].threshold,3);assert.equal(e.read().hrPeerCycles[0].rules.version,1)});
 test('issue8: cycles require explicit CEO activation and sufficient clinic members',()=>{const e=fixture(),P=e.context.HRPerformanceV4;assert.throws(()=>cycle(e));rules(e);actor(e,'admin');assert.throws(()=>cycle(e),/CEO/);actor(e,'u1');assert.throws(()=>P.openCycle({clinicId:'c2',kind:'Mensal',period:'2026-10',reason:'Pequena equipa'}),/suficientes/);const x=cycle(e);assert.equal(x.status,'Aberto');assert.throws(()=>cycle(e),/sobreposto/);assert.throws(()=>P.openCycle({clinicId:'c1',kind:'Anual',period:'2026',reason:'Outro corte'}),/sobreposto/)});
 test('issue8: no self-review, cross-clinic review, inactive member or duplicate response',()=>{const e=fixture(),P=e.context.HRPerformanceV4;rules(e);const c=cycle(e),a=answers(c.criteria);actor(e,'p');assert.throws(()=>P.submitPeer(c.id,'p',a));assert.throws(()=>P.submitPeer(c.id,'otherclinic',a));assert.throws(()=>P.submitPeer(c.id,'unknown',a));P.submitPeer(c.id,'peer',a);assert.throws(()=>P.submitPeer(c.id,'peer',a),/Já respondeu/);assert(P.peerTargets(c.id).find(p=>p.id==='peer').submitted);actor(e,'otherclinic');assert.equal(P.cycles().length,0);assert.throws(()=>P.peerTargets(c.id));actor(e,'peer2');const s=e.read();s.users.find(p=>p.id==='peer').active=false;e.write(s);assert.throws(()=>P.submitPeer(c.id,'peer',a));assert.equal(e.read().hrPeerResponses.length,1)});
 test('issue8: incomplete or malformed peer scores do not write response/history',()=>{const e=fixture(),P=e.context.HRPerformanceV4;rules(e);const c=cycle(e);actor(e,'p');const before=e.read();assert.throws(()=>P.submitPeer(c.id,'peer',{}));assert.throws(()=>P.submitPeer(c.id,'peer',Object.fromEntries(c.criteria.map(q=>[q.id,6]))));assert.deepEqual(e.read(),before)});
 test('issue8: peer aggregates withheld before close and below anonymity threshold',()=>{const e=fixture(),P=e.context.HRPerformanceV4;rules(e);const c=cycle(e),a=answers(c.criteria);for(const id of ['peer','peer2']){actor(e,id);P.submitPeer(c.id,'p',a)}actor(e,'u1');assert.equal(P.peerResult(c.id,'p').released,false);assert(!('score' in P.peerResult(c.id,'p')));P.closeCycle(c.id,'Fechar piloto');const out=P.peerResult(c.id,'p');assert.equal(out.released,false);assert(!JSON.stringify(out).includes('peer'));assert(!('criteria' in out));assert(!('count' in out))});
 test('issue8: released aggregates omit reviewers, exact counts, identifiers and individual responses',()=>{const e=fixture(),P=e.context.HRPerformanceV4;rules(e);const c=cycle(e);for(const [id,v] of [['peer',3],['peer2',4],['peer3',5]]){actor(e,id);P.submitPeer(c.id,'p',Object.fromEntries(c.criteria.map(q=>[q.id,v])))}actor(e,'u1');P.closeCycle(c.id,'Fechar e divulgar agregados');actor(e,'p');const result=P.peerResult(c.id,'p');assert.equal(result.released,true);assert.equal(result.score,4);const json=JSON.stringify(result);for(const privateField of ['reviewer','targetId','cycleId','createdAt','peer2','peer3','count'])assert(!json.includes(privateField),privateField);assert.throws(()=>P.peerResult(c.id,'peer'));assert.equal(P.cycleResults(c.id).length,1);assert(!JSON.stringify(P.cycleResults(c.id)).includes('Colega'));e.context.HRPerformanceUIV4.results(c.id);assert(!e.elements.get('modalBody').innerHTML.includes('Colega'));assert.equal(e.read().hrPeerPrivateEvents.length,3);assert(!e.read().audit.some(a=>/Submetido|peerresponse/.test(a.action||a.recordId||'')))});
 test('issue8: closed results immutable and no response/second-close accepted',()=>{const e=fixture(),P=e.context.HRPerformanceV4;rules(e);const c=cycle(e);P.closeCycle(c.id,'Fechar');const before=e.read();assert.throws(()=>P.closeCycle(c.id,'Reabrir'));actor(e,'p');assert.throws(()=>P.submitPeer(c.id,'peer',answers(c.criteria)));const after=e.read();assert.deepEqual(after.hrPeerResults,before.hrPeerResults);assert.deepEqual(after.hrPeerCycleEvents,before.hrPeerCycleEvents)});
 test('issue8: changed memberships, suspended questionnaires and revoked permissions block submissions',()=>{const e=fixture(),P=e.context.HRPerformanceV4;rules(e);const c=cycle(e),a=answers(c.criteria);actor(e,'p');const s=e.read();s.users.find(p=>p.id==='p').clinics=['c2'];e.write(s);assert.throws(()=>P.submitPeer(c.id,'peer',a));s.users.find(p=>p.id==='p').clinics=['c1'];s.roleActionPermissions['MEDICO/A'].peerReview=false;e.write(s);assert.throws(()=>P.submitPeer(c.id,'peer',a));actor(e,'u1');const r=P.rules();r.peerEnabled=false;P.approveRules(r,'Suspender novos envios');actor(e,'peer');assert.throws(()=>P.submitPeer(c.id,'p',a));assert.equal(e.read().hrPeerResponses,undefined)});
 for(const [id,role] of [['u1','CEO'],['admin','ADMINISTRAÇÃO'],['p','ADMINISTRATIVA'],['p','CALL CENTER'],['p','MEDICO/A'],['p','TECNICO/A'],['p','BASICO']])test('issue8: performance permissions and rendered entry for '+role,()=>{const e=fixture(),P=e.context.HRPerformanceV4;rules(e);const s=e.read();s.currentUser=id;s.ceoRealUser='u1';if(id==='p')s.users.find(p=>p.id===id).role=role;e.write(s);const manager=['CEO','ADMINISTRAÇÃO'].includes(role);assert.equal(P.canManage(s),manager);assert(P.canSelf(s));assert(P.canPeer(s));assert.equal(P.ceo(s),role==='CEO');assert(e.context.HRPerformanceUIV4.open());const html=e.elements.get('modalBody').innerHTML;assert.equal(html.includes('Nova avaliação'),manager);assert.equal(html.includes('Configurar / validar regras'),role==='CEO');if(!manager){assert.throws(()=>proposal(e));assert.throws(()=>P.approveRules(P.defaults(),'Teste'));assert.throws(()=>P.openCycle({clinicId:'c1',kind:'Mensal',period:'2026-10',reason:'Teste'}))}});
 test('issue8: existing false permissions are preserved and unknown/inactive users denied',()=>{const e=fixture(),s=e.read();s.currentUser='p';s.roleActionPermissions['MEDICO/A'].performanceRead=false;s.roleActionPermissions['MEDICO/A'].peerReview=false;e.write(s);e.context.RoleAccessAdminV4.ensure();assert.equal(e.context.HRPerformanceV4.canSelf(e.read()),false);assert.equal(e.context.HRPerformanceUIV4.open(),false);s.currentUser='missing';e.write(s);assert.equal(e.context.HRPerformanceV4.canManage(e.read()),false);s.currentUser='p';s.users.find(p=>p.id==='p').active=false;e.write(s);assert.equal(e.context.HRPerformanceV4.canPeer(e.read()),false)});
 test('issue8: performance forms revalidate writes and close on profile/permission change',()=>{const e=fixture();rules(e);e.context.HRPerformanceUIV4.rulesForm();actor(e,'p');e.document.dispatchEvent({type:'gs:user-changed'});assert.equal(e.elements.get('modal').open,false);assert.equal(e.elements.get('modalBody').innerHTML,'');assert.equal(e.context.HRPerformanceUIV4.rulesForm(),false);actor(e,'admin');e.context.HRPerformanceUIV4.open();e.document.dispatchEvent({type:'gs:permissions-applied'});assert.equal(e.elements.get('modal').open,false)});
 test('issue8: HTML escapes feedback/objectives and peer UI contains no raw response objects',()=>{const e=fixture(),P=e.context.HRPerformanceV4;rules(e);const x=proposal(e,{feedback:'<script>alert(1)</script>',objectives:[{title:'<img onerror=bad>',progress:0}]});P.decideEvaluation(x.id,'Validada','Confirmar');e.context.HRPerformanceUIV4.detail(x.id);const html=e.elements.get('modalBody').innerHTML;assert(!html.includes('<script>'));assert(!html.includes('<img onerror'));assert(html.includes('&lt;script&gt;'));assert(!html.includes('employeeId'));const c=cycle(e);actor(e,'p');e.context.HRPerformanceUIV4.peerForm(c.id,'peer');assert(!e.elements.get('modalBody').innerHTML.includes('reviewerId'))});
 test('issue8: independent modals do not restore a previous leave detail during access updates',()=>{const e=fixture();rules(e);e.context.HRLeaveUIV4.open('original');e.context.HRPerformanceUIV4.open();e.document.dispatchEvent({type:'gs:permissions-applied'});assert.equal(e.elements.get('modal').open,false);assert.equal(e.elements.get('modalBody').innerHTML,'')});
 test('issue8: approvals list closes and removes names when changing profile',()=>{const e=fixture();e.context.ApprovalsV4.open('vac');assert(e.elements.get('modalBody').innerHTML.includes('Colega'));actor(e,'p');e.document.dispatchEvent({type:'gs:user-changed'});assert.equal(e.elements.get('modal').open,false);assert.equal(e.elements.get('modalBody').innerHTML,'')});
 test('issue8: detail retains multiple clinic selector and shared context restriction',()=>{const e=fixture(),s=e.read();s.users.find(p=>p.id==='p').clinics=['c1','c2'];e.write(s);e.context.HRLeaveUIV4.open('original');assert(e.elements.get('leaveContext').innerHTML.includes('leaveContextClinic'));e.document.dispatchEvent({type:'change',target:{dataset:{},value:'c2',hasAttribute:k=>k==='data-leave-clinic'}});assert(e.elements.get('leaveContext').innerHTML.includes('Outra clínica'));assert(!e.elements.get('leaveContext').innerHTML.includes('Colega'))});
 test('issue8: authorized UI entry, proposal submission and CEO decision call shared domain',()=>{const e=fixture(),U=e.context.HRPerformanceUIV4,P=e.context.HRPerformanceV4;rules(e);U.form('p');for(const c of P.rules().criteria)e.elements.get('perf_score_'+c.id).value='4';for(const [id,value] of [['perfEmployee','p'],['perfKind','Mensal'],['perfPeriod','2026-11'],['perfObjectives','Processos | Concluir plano | 25'],['perfFeedback','Avaliação UI'],['perfProposalReason','Proposta normal']])e.elements.get(id).value=value;const button=e.document.createElement('button');button.dataset.performanceAction='submit-evaluation';button.click();const record=P.evaluations('p')[0];assert.equal(record.period.value,'2026-11');assert.equal(record.objectives[0].progress,25);e.elements.get('perfDecisionReason').value='Validado pelo CEO';button.dataset.performanceAction='validate';button.click();assert.equal(P.evaluations('p')[0].status,'Validada');assert(e.elements.get('modalBody').innerHTML.includes('Validada'))});
 test('issue8: financial integration exports reference only after CEO validation and never writes money',()=>{const e=fixture(),P=e.context.HRPerformanceV4;rules(e);const x=proposal(e);assert.throws(()=>P.financialReviewReference(x.id));P.decideEvaluation(x.id,'Validada','Confirmar');const before=e.read(),out=P.financialReviewReference(x.id);assert.equal(out.automaticPayment,false);assert.equal(out.amount,null);assert.deepEqual(e.read(),before);actor(e,'admin');assert.throws(()=>P.financialReviewReference(x.id),/CEO/)});

 test('issue8: rules form creates a new version and renders protected rule history',()=>{const e=fixture(),U=e.context.HRPerformanceUIV4,P=e.context.HRPerformanceV4;U.rulesForm();for(const [id,value] of [['perfCriteria','Qualidade | 60\nEquipa | 40'],['perfPeerCriteria','Cooperação | 50\nComunicação | 50'],['perfThreshold','3'],['perfRuleReason','Validar pesos']])e.elements.get(id).value=value;e.elements.get('perfPeerEnabled').checked=true;assert(U.saveRules());assert.equal(P.rules().criteria.length,2);U.rulesForm();assert(e.elements.get('modalBody').innerHTML.includes('Versão 1'));assert(e.elements.get('modalBody').innerHTML.includes('Validar pesos'));actor(e,'admin');assert.throws(()=>P.ruleHistory(),/CEO/)});

};
