const fs=require('node:fs'),assert=require('node:assert/strict');
(async()=>{const {onRequest}=await import('data:text/javascript;base64,'+fs.readFileSync('functions/api/preview.js').toString('base64'));let passed=0;const test=async(name,fn)=>{await fn();passed++;console.log('PASS proxy:',name)},base='https://test.grupo-saude.pages.dev',env={GS_ENVIRONMENT:'preview',GS_TEST_BACKEND_URL:'https://isolated-backend.example/',GS_TEST_BACKEND_TOKEN:'test-only-not-a-secret',GS_PREVIEW_ORIGINS:base};const request=(action,extra={})=>new Request(base+'/api/preview?action='+action,{method:'POST',headers:{origin:base,'content-type':'application/json'},body:'{}',...extra});let calls=0;const fetchOriginal=global.fetch;global.fetch=async()=>{calls++;return new Response('{}',{headers:{'content-type':'application/json'}})};
try{
await test('unconfigured backend never makes outbound calls',async()=>{assert.equal((await onRequest({request:request('signIn'),env:{}})).status,503);assert.equal(calls,0)});
await test('production environment blocked',async()=>{assert.equal((await onRequest({request:request('signIn'),env:{...env,GS_ENVIRONMENT:'production'}})).status,503);assert.equal(calls,0)});
await test('non HTTPS and credential-bearing backend rejected',async()=>{for(const url of ['http://example/','https://user:password@example/','https://example/path'])assert.equal((await onRequest({request:request('signIn'),env:{...env,GS_TEST_BACKEND_URL:url}})).status,503);assert.equal(calls,0)});
await test('preview origin whitelist, cross origin, absent Origin, JSON and route guards',async()=>{assert.equal((await onRequest({request:request('signIn'),env:{...env,GS_PREVIEW_ORIGINS:'https://other.example'}})).status,403);for(const headers of [{origin:'https://other.example','content-type':'application/json'},{'content-type':'application/json'},{origin:base,'content-type':'text/plain'}])assert.equal((await onRequest({request:request('signIn',{headers}),env})).status,403);assert.equal((await onRequest({request:request('unknown'),env})).status,405);assert.equal(calls,0)});
await test('malformed and oversized requests never forwarded',async()=>{assert.equal((await onRequest({request:request('signIn',{body:'invalid'}),env})).status,400);assert.equal((await onRequest({request:request('signIn',{body:JSON.stringify({x:'a'.repeat(65537)})}),env})).status,413);assert.equal(calls,0)});
await test('allowed request forwards only to fixed same-origin backend path with no cache',async()=>{global.fetch=async(url,options)=>{assert.equal(url.href,'https://isolated-backend.example/auth/request-reset');assert.equal(options.redirect,'error');assert.equal(options.headers.authorization,'Bearer '+env.GS_TEST_BACKEND_TOKEN);assert.equal(options.headers['x-preview-origin'],base);return new Response('{"ok":true}',{headers:{'content-type':'application/json'}})};const r=await onRequest({request:request('requestReset'),env});assert.equal(r.status,200);assert.equal(r.headers.get('cache-control'),'no-store');assert.deepEqual(await r.json(),{ok:true})});
await test('unsafe cookie rejected; secure host cookie preserved',async()=>{for(const cookie of ['session=x','session=x; Secure; HttpOnly; SameSite=Lax; Domain=example']){global.fetch=async()=>new Response('{}',{headers:{'content-type':'application/json','set-cookie':cookie}});assert.equal((await onRequest({request:request('signIn'),env})).status,502)}global.fetch=async()=>new Response('{}',{headers:{'content-type':'application/json','set-cookie':'__Host-gs_session=x; Path=/; Secure; HttpOnly; SameSite=Lax'}});const r=await onRequest({request:request('signIn'),env});assert.equal(r.status,200);assert.match(r.headers.get('set-cookie'),/HttpOnly/)});
await test('backend outage and non JSON response fail closed',async()=>{global.fetch=async()=>{throw Error('private credential must not leak')};let r=await onRequest({request:request('signIn'),env});assert.equal(r.status,502);assert(!(await r.text()).includes('credential'));global.fetch=async()=>new Response('html',{headers:{'content-type':'text/html'}});assert.equal((await onRequest({request:request('signIn'),env})).status,502)});
console.log(JSON.stringify({passed,scope:'Proxy com backend simulado; serviços reais não configurados'}));
}finally{global.fetch=fetchOriginal}})().catch(e=>{console.error(e);process.exitCode=1});
