// Execução do código real num DOM simulado. Não substitui testes num navegador.
const fs=require('node:fs');
const vm=require('node:vm');
const assert=require('node:assert/strict');

const path=require('node:path');
const root=path.join(__dirname,'..');
const KEY='grupo_saude_v4_demo_2';
function environment(initial){
 const storage=new Map(initial?[[KEY,JSON.stringify(initial)]]:[]),elements=new Map(),listeners=new Map(),timers=[];
 class Element{
  constructor(id='',classes=''){this.id=id;this.dataset={};this.style={setProperty(){},removeProperty(){}};this.hidden=false;this.children=[];this.value='';this._html='';this.parentElement=null;this.handlers={};const c=new Set(classes.split(' ').filter(Boolean));this.classList={contains:x=>c.has(x),add:x=>c.add(x),remove:x=>c.delete(x),toggle(x,on){if(on??!c.has(x))c.add(x);else c.delete(x)}};if(id)elements.set(id,this)}
  set innerHTML(html){this._html=html;for(const m of html.matchAll(/id=["']([^"']+)["']/g))if(!elements.has(m[1]))new Element(m[1]);}
  get innerHTML(){return this._html}
  addEventListener(n,f){(this.handlers[n]??=[]).push(f)}
  appendChild(e){if(e.parentElement)e.parentElement.children=e.parentElement.children.filter(x=>x!==e);e.parentElement=this;this.children.push(e);return e}
  setAttribute(k,v){this[k]=v}
  insertBefore(e){return this.appendChild(e)}
  prepend(e){e.parentElement=this;this.children.unshift(e)}
  remove(){elements.delete(this.id);if(this.parentElement)this.parentElement.children=this.parentElement.children.filter(x=>x!==this)}
  removeAttribute(k){if(k==='hidden')this.hidden=false}
  querySelector(s){if(s==='.page-head')return this.head;if(s==='button')return this.children.find(x=>x.tagName==='BUTTON')||new Element();if(s==='.cards')return this.grid;return this.querySelectorAll(s)[0]||null}
  querySelectorAll(s){const all=this.children.flatMap(x=>[x,...x.querySelectorAll('*')]);if(s==='*')return all;if(s==='button')return all.filter(x=>x.tagName==='BUTTON');if(s==='[data-rhtabs]')return all.filter(x=>x.dataset.rhtabs);if(s==='details[data-nav-group]')return all.filter(x=>x.dataset.navGroup);if(s==='[data-view]')return all.filter(x=>x.dataset.view);const view=/^\[data-view="([^"]+)"\]$/.exec(s);if(view)return all.filter(x=>x.dataset.view===view[1]);return []}
  closest(s){if(s==='[data-performance-action]'&&this.dataset.performanceAction)return this;if(s==='[data-leave-action]'&&this.dataset.leaveAction)return this;if(s==='[data-approval-decision]'&&this.dataset.approvalDecision)return this;if(s.includes('[data-view]')&&this.dataset.view)return this;return null}
  click(){const e={target:this,preventDefault(){},stopImmediatePropagation(){this.stopped=true}};for(const f of listeners.get('click')||[]){f(e);if(e.stopped)break}if(!e.stopped)this.onclick?.(e)}
  showModal(){this.open=true} close(){this.open=false}
 }
 const ids=['tables','clock','dashboard','operation','wait','chat','hr','tasks','audit','clinics'];
 for(const id of ids){const e=new Element(id,'view'+(id==='dashboard'?' active':''));e.head=new Element();e.grid=new Element();new Element(id+'Content')}
 for(const id of ['nav','menuBtn','currentUser','modal','modalTitle','modalBody','toast','unread','navUnread'])new Element(id);
 const top=new Element('top','top-actions');
 function nav(id){const b=new Element('nav-'+id,id==='dashboard'?'active':'');b.tagName='BUTTON';b.dataset.view=id;elements.get('nav').appendChild(b);return b}
 ids.forEach(nav);
 const document={body:new Element('body'),readyState:'loading',activeElement:null,documentElement:new Element(),getElementById:id=>elements.get(id)||null,createElement:tag=>{const e=new Element();e.tagName=tag.toUpperCase();return e},addEventListener(n,f,options){const arr=listeners.get(n)||[];options===true?arr.unshift(f):arr.push(f);listeners.set(n,arr)},dispatchEvent(e){for(const f of [...(listeners.get(e.type)||[])])f(e)},querySelectorAll(s){const all=[...elements.values()];if(s==='.view')return all.filter(x=>x.classList.contains('view'));if(s==='.view.active'||s==='section.view.active')return all.filter(x=>x.classList.contains('view')&&x.classList.contains('active'));if(s==='[data-view]'||s==='#nav [data-view]')return elements.get('nav').querySelectorAll('[data-view]');if(s==='#nav [data-view].active')return this.querySelectorAll('#nav [data-view]').filter(x=>x.classList.contains('active'));return []},querySelector(s){if(s==='.top-actions')return top;const h=/^#(\w+) \.page-head$/.exec(s);if(h)return elements.get(h[1]).head;if(s.startsWith('#nav [data-view=')){const id=s.match(/"(.*?)"/)?.[1];return elements.get('nav-'+id)}return this.querySelectorAll(s)[0]||null}};
 const context={document,localStorage:{getItem:k=>storage.get(k)||null,setItem:(k,v)=>storage.set(k,String(v))},console,Intl,Date,Math,JSON,Set,Map,URL,alert(){},confirm:()=>false,prompt:()=>null,location:{reload(){}},navigator:{},MutationObserver:class{observe(){}},CustomEvent:class{constructor(type,options={}){this.type=type;this.detail=options.detail}},setTimeout:(f,delay)=>{timers.push({f,delay});return timers.length},clearTimeout(){},setInterval(){},queueMicrotask:f=>timers.push({f,delay:0}),addEventListener(){},dispatchEvent(){}};
 context.matchMedia=()=>({matches:false});context.window=context;vm.createContext(context);
 const run=(f,source)=>vm.runInContext(source??fs.readFileSync(path.join(root,f),'utf8'),context,{filename:f,timeout:2000});
 const flush=()=>{const batch=timers.splice(0).sort((a,b)=>a.delay-b.delay);for(const t of batch)t.f()};
 return {context,document,elements,run,flush,nav,read:()=>JSON.parse(storage.get(KEY)),write:s=>storage.set(KEY,JSON.stringify(s))};
}
let passed=0;
function test(name,fn){fn();passed++;console.log('PASS',name)}
const baselineDir=process.env.GS_BASELINE_DIR;
const baseline=f=>fs.readFileSync(path.join(baselineDir,f),'utf8');
if(baselineDir){
test('baseline: RH and approvals scripts fail before any code can run',()=>{
 for(const f of ['clinic-hr-architecture.js','approvals-center-v4.js'])assert.throws(()=>new vm.Script(baseline(f)),SyntaxError);
});
test('baseline: extensions create partial state before App DOM initialization',()=>{
 const e=environment();e.run('app.js',baseline('app.js'));e.run('access-scope-v4.js',baseline('access-scope-v4.js'));
 assert.throws(()=>e.document.dispatchEvent({type:'DOMContentLoaded'}),/forEach/);
});
test('baseline: undefined clinics interrupts a seeded startup',()=>{
 const e=environment();e.run('app.js',baseline('app.js'));
 assert.throws(()=>e.document.dispatchEvent({type:'DOMContentLoaded'}),/clinics is not defined/);
});
}else console.log('SKIP historical reproduction: set GS_BASELINE_DIR to files from upstream 84fba5a');
function core(){const e=environment();for(const f of ['app.js','hr-leave-domain-v4.js','hr-leave-ui-v4.js','hr-performance-domain-v4.js','hr-performance-ui-v4.js','access-scope-v4.js','clinic-hr-architecture.js','ceo-reserved-area-switcher-v4.js','role-access-admin-v4.js'])e.run(f);e.document.dispatchEvent({type:'DOMContentLoaded'});e.flush();return e}
test('fresh startup, synchronous initialization and direct CEO RH',()=>{
 const e=core();assert(e.read().candidates);assert(e.read().users.some(x=>x.id==='u1'));
 assert(e.context.App.showView('hr'));assert(e.elements.get('hr').classList.contains('active'));assert.match(e.elements.get('hrContent').innerHTML,/Colaboradores/);assert.match(e.elements.get('hrContent').innerHTML,/Candidatos/);
 assert.equal(e.document.querySelectorAll('.view.active').length,1);
});
test('approval access follows active profile, not ceoRealUser',()=>{
 const e=core();e.run('approvals-center-v4.js');const s=e.read();s.currentUser='test_med';s.ceoRealUser='u1';s.leave=[{id:'pending',employeeId:'test_med',type:'Férias',days:['2026-10-08'],status:'Pendente'}];e.write(s);e.context.ApprovalsV4.decide('leave','pending','','Aprovado');assert.equal(e.read().leave[0].status,'Pendente');
 s.currentUser='test_admin';e.write(s);e.context.ApprovalsV4.decide('leave','pending','','Aprovado');assert.equal(e.read().leave[0].status,'Aprovado');
});
const actors=[['u1','CEO'],['test_admin','ADMINISTRAÇÃO'],['test_adm','ADMINISTRATIVA'],['test_call','CALL CENTER'],['test_med','MEDICO/A'],['test_tec','TECNICO/A'],['test_bas','BASICO']];
for(const [id,role] of actors)test('direct access and permissions: '+role,()=>{
 const e=core(),s=e.read();s.currentUser=id;s.ceoViewingAs=id==='u1'?null:id;e.write(s);e.document.dispatchEvent({type:'gs:user-changed'});
 e.context.RoleAccessAdminV4.apply();
 for(const view of ['dashboard','clock','operation','wait','chat','hr','tasks','audit','tables','clinics']){
  const allowed=e.context.RoleAccessAdminV4.guard(view);const active=e.document.querySelectorAll('.view.active')[0];
  assert.equal(e.context.App.showView(view),allowed,view);
  if(allowed){assert(e.elements.get(view).classList.contains('active'));assert.equal(e.document.querySelectorAll('.view.active').length,1)}
  else assert.equal(e.document.querySelectorAll('.view.active')[0],active,'denied navigation preserves current view');
 }
 assert.equal(e.context.RoleAccessAdminV4.can('hrManage'),['CEO','ADMINISTRAÇÃO'].includes(role));
});
test('RH click then another module is never reverted by delayed RH navigation',()=>{
 const e=core();e.elements.get('nav-hr').click();e.elements.get('nav-dashboard').click();e.flush();assert(e.elements.get('dashboard').classList.contains('active'));
});
test('profile change and immediate CEO return needs no reload',()=>{
 const e=core();for(const id of ['test_med','u1']){e.elements.get('currentUser').onchange({target:{value:id}})}
 assert.equal(e.read().currentUser,'u1');assert.equal(e.read().ceoViewingAs,null);assert(e.context.App.showView('hr'));
});
test('saved restrictions and HR documents survive normalization and render',()=>{
 const e=core(),s=e.read();s.roleActionPermissions['ADMINISTRAÇÃO'].hrManage=false;s.employeeDocuments={test_med:[{id:'keep',dataUrl:'data:text/plain;base64,QQ=='}]};s.leave=[{id:'vac-keep',status:'Aprovado'}];s.customData={keep:true};e.write(s);e.context.RoleAccessAdminV4.ensure();e.context.App.showView('hr');const after=e.read();
 assert.equal(after.roleActionPermissions['ADMINISTRAÇÃO'].hrManage,false);assert.deepEqual(after.employeeDocuments,s.employeeDocuments);assert.deepEqual(after.leave,s.leave);assert.deepEqual(after.customData,s.customData);
});
test('saved duplicate identities are not deleted by the CEO selector',()=>{
 const e=core(),s=e.read();s.users.push({id:'duplicate-keep',email:s.users.find(u=>u.id==='test_admin').email,name:'Outro registo',role:'ADMINISTRAÇÃO'});s.employees['duplicate-keep']={id:'duplicate-keep',name:'Outro registo',hr:{custom:'keep'}};e.write(s);e.context.CEOReservedAreaV4.render();assert(e.read().users.some(u=>u.id==='duplicate-keep'));assert.equal(e.read().employees['duplicate-keep'].hr.custom,'keep');
});
test('edited actor and master clinics are used by the operation renderer',()=>{
 const e=core(),s=e.read();s.currentUser='test_admin';s.employees.test_admin.name='Nome editado no RH';s.employees.test_admin.clinics=['real'];s.clinics=[{id:'real',name:'Clínica real',active:true}];e.write(s);assert(e.context.App.showView('operation'));assert.match(e.elements.get('operationContent').innerHTML,/Nome editado no RH/);assert.match(e.elements.get('operationContent').innerHTML,/Clínica real/);
 s.clinics=[];e.write(s);e.context.App.showView('operation');assert.match(e.elements.get('operationContent').innerHTML,/Sem clínica/);
});
test('calendar and approvals generate valid inline handlers' ,()=>{
 const e=core();e.run('approvals-center-v4.js');const s=e.read();s.leave=[{id:'pending',employeeId:'test_med',type:'Férias',status:'Pendente',start:'2026-10-08',end:'2026-10-09'}];e.write(s);
 e.context.ApprovalsV4.open();
 for(const m of e.elements.get('modalBody').innerHTML.matchAll(/onclick="([^"]*)"/g))new vm.Script(m[1].replaceAll('&#39;',"'").replaceAll('&quot;','"').replaceAll('&amp;','&'));
 e.context.V4VacationCalendar.open();e.context.V4VacationCalendar.refresh();
 for(const m of e.elements.get('vacCalendarBody').innerHTML.matchAll(/onclick="([^"]*)"/g))new vm.Script(m[1].replaceAll('&#39;',"'").replaceAll('&quot;','"').replaceAll('&amp;','&'));
});
test('unknown identity does not become CEO',()=>{
 const e=core(),s=e.read();s.currentUser='missing';e.write(s);assert.equal(e.context.RoleAccessAdminV4.can('hrManage'),false);assert.equal(e.context.App.showView('hr'),false);
});
test('late module nav uses same delegated navigation',()=>{
 const e=core();const section=new (e.elements.get('hr').constructor)('reports','view');e.nav('reports');let renders=0;e.context.GSEnterprise={render:id=>{assert.equal(id,'reports');renders++}};e.elements.get('nav-reports').click();assert(section.classList.contains('active'));assert.equal(renders,1);
});
function leaveFixture(){const e=core(),s=e.read();s.currentUser='u1';s.employees={};s.users=[{id:'u1',name:'CEO',role:'CEO'},{id:'admin',name:'Administração',role:'ADMINISTRAÇÃO'},...['p','peer','otherclinic','otherrole'].map((id,i)=>({id,name:['Pessoa','Colega','Outra clínica','Outra função'][i],role:i===3?'TECNICO/A':'MEDICO/A',clinics:[i===2?'c2':'c1'],hr:{vacationDays:22}}))];s.clinics=[{id:'c1',name:'Clínica Um'},{id:'c2',name:'Clínica Dois'}];s.clinicCalendars={c1:{2026:{municipal:[{date:'2026-06-24',name:'Feriado municipal'}]}}};s.leave=[{id:'original',employeeId:'p',type:'Férias',clinicId:'c1',days:['2026-07-06','2026-07-07','2026-07-08','2026-07-09','2026-07-10'],start:'2026-07-06',end:'2026-07-10',status:'Aprovado',createdAt:'2026-01-05T10:00:00Z',reason:'Descanso'},{id:'peer-vac',employeeId:'peer',type:'Férias',days:['2026-07-07'],status:'Aprovado'},{id:'peer-pending',employeeId:'peer',type:'Férias',days:['2026-07-08'],status:'Pendente'},{id:'peer-sick',employeeId:'peer',type:'Baixa',start:'2026-07-09',end:'2026-07-09',status:'Aprovado'},{id:'other-clinic',employeeId:'otherclinic',type:'Férias',days:['2026-07-07'],status:'Aprovado'},{id:'other-role',employeeId:'otherrole',type:'Férias',days:['2026-07-07'],status:'Aprovado'}];s.audit=[];s.alerts=[];s.employeeDocuments={};e.write(s);e.run('approvals-center-v4.js');e.run('vacation-calendar-v4.js');e.run('hr-vacation-planning-v4.js');return e}
const flat=v=>JSON.parse(JSON.stringify(v));
const original=e=>e.read().leave.find(x=>x.id==='original');
const actor=(e,id)=>{const s=e.read();s.currentUser=id;s.ceoRealUser='u1';e.write(s)};
test('issue6: clinic/role context distinguishes approved, pending and medical absences',()=>{const e=leaveFixture(),D=e.context.HRLeaveV4,c=D.context(e.read(),original(e));assert.deepEqual(flat(c.absences.map(v=>v.record.id)),['peer-vac','peer-pending','peer-sick']);assert.equal(c.coverage.find(x=>x.date==='2026-07-07').available,0);assert.equal(c.coverage.find(x=>x.date==='2026-07-08').available,1);assert.equal(c.coverage.find(x=>x.date==='2026-07-08').potentialAvailable,0)});
test('issue6: municipal/national/movable holidays and weekends share one balance',()=>{const e=leaveFixture(),D=e.context.HRLeaveV4,s=e.read();for(const d of ['2026-06-10','2026-06-24','2026-04-03','2026-06-04','2026-07-11'])assert.equal(D.working(s,'c1',d),false,d);assert.equal(D.working(s,'c2','2026-06-24'),true);s.leave.push({id:'week',employeeId:'p',type:'Férias',status:'Aprovado',start:'2026-06-22',end:'2026-06-28'});assert.equal(D.balance(s,'p',2026).approved,9)});
test('issue6: exact partial rebooking preserves unselected days, original, audit and notifications',()=>{const e=leaveFixture(),D=e.context.HRLeaveV4,x=D.requestChange('original',['2026-07-07','2026-07-08'],['2026-08-03','2026-08-04'],'Necessidade pessoal');assert.equal(x.status,'Aprovado');assert.deepEqual(original(e).days,['2026-07-06','2026-07-09','2026-07-10','2026-08-03','2026-08-04']);assert.equal(original(e).originalDays.length,5);assert.equal(original(e).revisions.length,1);assert.equal(D.balance(e.read(),'p',2026).approved,5);assert(e.read().audit.some(a=>a.recordId==='original'&&a.before&&a.after));assert(e.read().alerts.some(a=>a.to==='p'));assert(e.read().alerts.some(a=>a.to==='admin'));assert.equal(e.read().leave.length,7)});
test('issue6: mandatory reason and invalid/holiday/unequal replacement leave data untouched',()=>{const e=leaveFixture(),D=e.context.HRLeaveV4,before=e.read();for(const args of [[['2026-07-07'],['2026-08-03'],''],[['2026-07-07'],['2026-06-24'],'teste'],[['2026-07-07'],['2026-08-03','2026-08-04'],'teste'],[['2026-07-20'],['2026-08-03'],'teste'],[['2026-07-07'],['2026-02-30'],'teste']])assert.throws(()=>D.requestChange('original',...args));assert.deepEqual(e.read(),before)});
test('issue6: employee change remains pending without changing calendar or balance',()=>{const e=leaveFixture(),D=e.context.HRLeaveV4;actor(e,'p');const before=original(e),x=D.requestChange('original',['2026-07-07'],['2026-08-03'],'Reagendar');assert.equal(x.status,'Pendente');assert.deepEqual(original(e),before);assert.equal(D.balance(e.read(),'p',2026).approved,5);assert.equal(D.balance(e.read(),'p',2026).pending,0);assert.throws(()=>D.requestChange('original',['2026-07-08'],['2026-08-04'],'Outro'));assert.throws(()=>D.decide(x.id,'Aprovado'));actor(e,'admin');D.decide(x.id,'Aprovado','Validado');assert(original(e).days.includes('2026-08-03'));assert(!original(e).days.includes('2026-07-07'));assert.throws(()=>D.decide(x.id,'Aprovado'));assert.equal(D.balance(e.read(),'p',2026).approved,5)});
test('issue6: refusing a partial request preserves original and records reason',()=>{const e=leaveFixture(),D=e.context.HRLeaveV4;actor(e,'p');const x=D.requestChange('original',['2026-07-07'],['2026-08-03'],'Reagendar'),before=original(e);actor(e,'admin');assert.throws(()=>D.decide(x.id,'Recusado',''));D.decide(x.id,'Recusado','Necessidade da equipa');assert.deepEqual(original(e),before);assert.equal(e.read().leave.find(v=>v.id===x.id).decisionNote,'Necessidade da equipa')});
test('issue6: stale partial request cannot overwrite a subsequent original edit',()=>{const e=leaveFixture(),D=e.context.HRLeaveV4;actor(e,'p');const x=D.requestChange('original',['2026-07-07'],['2026-08-03'],'Reagendar');const s=e.read();s.currentUser='u1';s.leave.find(v=>v.id==='original').revision=1;e.write(s);const before=e.read();assert.throws(()=>D.decide(x.id,'Aprovado'),/entretanto/);assert.deepEqual(e.read(),before)});
test('issue6: team conflicts are advisory but own approved sickness blocks replacement',()=>{const e=leaveFixture(),D=e.context.HRLeaveV4,s=e.read();s.leave.push({id:'team-target',employeeId:'peer',type:'Férias',days:['2026-08-03'],status:'Aprovado'});e.write(s);const x=D.requestChange('original',['2026-07-06'],['2026-08-03'],'Equipa informada');assert(flat(x.conflictIds).includes('team-target'));const z=e.read();z.leave.push({id:'own-sick',employeeId:'p',type:'Baixa',start:'2026-08-04',end:'2026-08-04',status:'Aprovado'});e.write(z);assert.throws(()=>D.requestChange('original',['2026-07-07'],['2026-08-04'],'Outro'),/baixa/)});
test('issue6: approved record cannot be reapproved; reversals explicit and audited',()=>{const e=leaveFixture(),D=e.context.HRLeaveV4;const before=e.read();assert.throws(()=>D.decide('original','Aprovado'));assert.deepEqual(e.read(),before);assert.throws(()=>D.reverse('original',''));D.reverse('original','Reavaliar decisão');assert.equal(original(e).status,'Pendente');assert(e.read().audit.some(a=>a.action==='Decisão revertida'));D.decide('original','Aprovado','Confirmado');assert.equal(original(e).status,'Aprovado')});
test('issue6: reverting a partial rebooking restores original without deleting history',()=>{const e=leaveFixture(),D=e.context.HRLeaveV4,before=original(e).days,x=D.requestChange('original',['2026-07-07'],['2026-08-03'],'Reagendar');D.reverse(x.id,'Retomar período anterior');assert.deepEqual(original(e).days,before);assert.equal(e.read().leave.find(v=>v.id===x.id).status,'Revertido');assert.equal(original(e).revisions.length,2);assert.equal(D.balance(e.read(),'p',2026).approved,5)});
test('issue6: cross-year rebooking recalculates both years and respects zero entitlement',()=>{const e=leaveFixture(),D=e.context.HRLeaveV4;D.requestChange('original',['2026-07-07'],['2027-01-04'],'Ano seguinte');assert.equal(D.balance(e.read(),'p',2026).approved,4);assert.equal(D.balance(e.read(),'p',2027).approved,1);const s=e.read();s.users.find(x=>x.id==='p').hr.vacationDays=0;e.write(s);const before=e.read();assert.throws(()=>D.requestChange('original',['2026-07-08'],['2027-01-05'],'Sem saldo'),/saldo/);assert.deepEqual(e.read(),before)});
test('issue6: medical approval restores only exact vacation days and can safely reapprove',()=>{const e=leaveFixture(),D=e.context.HRLeaveV4,s=e.read();s.leave.push({id:'own-sick',employeeId:'p',type:'Baixa',start:'2026-07-07',end:'2026-07-08',status:'Pendente'});s.employeeDocuments.p=[{id:'doc',leaveId:'own-sick',status:'Pendente'}];e.write(s);D.decide('own-sick','Aprovado');assert.deepEqual(original(e).days,['2026-07-06','2026-07-09','2026-07-10']);assert.equal(D.balance(e.read(),'p',2026).approved,3);assert.equal(e.read().employeeDocuments.p[0].status,'Aprovado');D.reverse('own-sick','Erro no período');assert.equal(original(e).days.length,5);D.decide('own-sick','Aprovado');assert.equal(e.read().leave.find(v=>v.id==='own-sick').adjustments.length,1);D.reverse('own-sick','Rever novamente');assert.equal(original(e).days.length,5)});
test('issue6: medical period edits restore unaffected vacation days atomically',()=>{const e=leaveFixture(),D=e.context.HRLeaveV4,s=e.read();s.leave.push({id:'own-sick',employeeId:'p',type:'Baixa',start:'2026-07-07',end:'2026-07-08',status:'Pendente'});e.write(s);D.decide('own-sick','Aprovado');D.editSick('own-sick','2026-07-08','2026-07-09','Correção do certificado');assert.deepEqual(original(e).days,['2026-07-06','2026-07-07','2026-07-10']);assert.equal(original(e).originalDays.length,5)});
test('issue6: medical reversal cannot overwrite a later vacation adjustment',()=>{const e=leaveFixture(),D=e.context.HRLeaveV4,s=e.read();s.leave.push({id:'own-sick',employeeId:'p',type:'Baixa',start:'2026-07-07',end:'2026-07-07',status:'Pendente'});e.write(s);D.decide('own-sick','Aprovado');D.requestChange('original',['2026-07-08'],['2026-08-03'],'Reagendar');const before=e.read();assert.throws(()=>D.reverse('own-sick','Restaurar'),/alteradas/);assert.deepEqual(e.read(),before)});
test('issue6: new vacation rejects duplicates, holidays, own sick leave and insufficient balance',()=>{const e=leaveFixture(),D=e.context.HRLeaveV4;assert.throws(()=>D.createVacation('p',['2026-07-07']));assert.throws(()=>D.createVacation('p',['2026-06-24']));const x=D.createVacation('p',['2026-08-03']);assert.equal(x.status,'Aprovado');assert.equal(D.balance(e.read(),'p',2026).approved,6);actor(e,'p');const y=D.createVacation('p',['2026-08-04']);assert.equal(y.status,'Pendente');assert.equal(D.balance(e.read(),'p',2026).pending,1);assert.throws(()=>D.createVacation('peer',['2026-08-05']));const s=e.read();s.users.find(x=>x.id==='p').hr.vacationDays=6;e.write(s);assert.throws(()=>D.createVacation('p',['2026-08-05']),/insuficiente/)});
test('issue6: readable details omit serialized fields and repeated approve action',()=>{const e=leaveFixture(),U=e.context.HRLeaveUIV4;assert(U.open('original'));const html=e.elements.get('modalBody').innerHTML;for(const label of ['Pessoa','Clínica Um','MEDICO/A','Dias úteis','Estado','Pedido em','Decisor','Motivo','Histórico'])assert(html.includes(label),label);assert(!html.includes('data-leave-action="approve"'));assert(!html.includes('employeeId'));assert(!html.includes('<pre>'));const context=e.elements.get('leaveContext').innerHTML;assert(context.includes('Colega'));assert(!context.includes('Outra clínica'));assert(!context.includes('Outra função'));assert(context.includes('leave-grid'));U.month(1);assert(e.elements.get('leaveContext').innerHTML.includes('agosto'))});
test('issue6: calendar cells open exact records and do not paint holes after rebooking',()=>{const e=leaveFixture(),D=e.context.HRLeaveV4,U=e.context.HRLeaveUIV4;D.requestChange('original',['2026-07-07'],['2026-08-03'],'Reagendar');U.calendar('p');const input=e.elements.get('vacMonth');input.value='2026-07';e.document.dispatchEvent({type:'change',target:{dataset:{leaveFilter:'month'},value:'2026-07'}});const html=e.elements.get('vacCalendarBody').innerHTML;assert(html.includes('data-leave-id="original"'));assert(!html.includes('em 07/07/2026'));assert(html.includes('em 06/07/2026'));assert(!html.includes('prompt('));e.context.V4VacationCalendar.edit('original');assert(e.elements.get('modalBody').innerHTML.includes('Período original preservado'))});
for(const [role,id] of [['CEO','u1'],['ADMINISTRAÇÃO','admin'],['ADMINISTRATIVA','p'],['CALL CENTER','p'],['MEDICO/A','p'],['TECNICO/A','p'],['BASICO','p']])test('issue6: leave privacy and authorization profile '+role,()=>{const e=leaveFixture(),D=e.context.HRLeaveV4,s=e.read();s.currentUser=id;if(id==='p')s.users.find(x=>x.id==='p').role=role;e.write(s);const privileged=['CEO','ADMINISTRAÇÃO'].includes(role);assert.equal(D.canReview(s),privileged);assert.equal(D.canEdit(s),privileged);assert.equal(D.context(s,original(e)).team.length>0,privileged);assert.equal(D.canRead(s,s.leave.find(x=>x.id==='peer-vac')),privileged);if(!privileged){assert.throws(()=>D.decide('peer-vac','Aprovado'));assert.throws(()=>D.requestChange('peer-vac',['2026-07-07'],['2026-08-03'],'Teste'));assert.equal(e.context.HRLeaveUIV4.open('peer-vac'),false)}});
test('issue6: permission revocation and user switch clear private details immediately',()=>{const e=leaveFixture(),D=e.context.HRLeaveV4,U=e.context.HRLeaveUIV4;actor(e,'admin');U.open('peer-vac');const s=e.read();s.roleActionPermissions['ADMINISTRAÇÃO'].hrManage=false;s.roleActionPermissions['ADMINISTRAÇÃO'].leaveApprove=false;e.write(s);e.document.dispatchEvent({type:'gs:permissions-applied'});assert.equal(e.elements.get('modal').open,false);assert.equal(e.elements.get('modalBody').innerHTML,'');actor(e,'u1');U.open('peer-vac');actor(e,'p');e.document.dispatchEvent({type:'gs:user-changed'});assert.equal(e.elements.get('modal').open,false);assert.equal(D.canReview(e.read()),false)});
test('issue6: employee sees only addressed RH notifications',()=>{const e=leaveFixture(),D=e.context.HRLeaveV4;D.requestChange('original',['2026-07-07'],['2026-08-03'],'Reagendar');actor(e,'p');const html=e.context.HRLeaveUIV4.notifications(e.read());assert(html.includes('Férias reagendadas'));assert.equal((html.match(/Consultar/g)||[]).length,1);actor(e,'peer');assert.equal(e.context.HRLeaveUIV4.notifications(e.read()),'')});

test('issue6: individual picker handlers compile and existing vacation click opens its exact detail',()=>{const e=leaveFixture(),U=e.context.HRLeaveUIV4;e.context.VacationCalendarV4.open('p');e.context.VacationCalendarV4.prev();const html=e.elements.get('vacCal').innerHTML;for(const m of html.matchAll(/onclick="([^"]*)"/g))new vm.Script(m[1].replaceAll('&#39;',"'").replaceAll('&quot;','"').replaceAll('&amp;','&'));const b=e.document.createElement('button');b.dataset.leaveAction='open';b.dataset.leaveId='original';b.click();assert(e.elements.get('modalBody').innerHTML.includes('Descanso'));assert(e.elements.get('modalBody').innerHTML.includes('Pessoa'));assert(U.form('original')!==false)});
test('issue6: empty vacation/medical records cannot be approved',()=>{const e=leaveFixture(),D=e.context.HRLeaveV4,s=e.read();s.leave.push({id:'empty',employeeId:'p',type:'Férias',days:[],status:'Pendente'},{id:'empty-sick',employeeId:'p',type:'Baixa',status:'Pendente'});e.write(s);const before=e.read();assert.throws(()=>D.decide('empty','Aprovado'));assert.throws(()=>D.decide('empty-sick','Aprovado'));assert.deepEqual(e.read(),before)});
require('./performance.cjs')({core,test,assert,vm,flat,actor,leaveFixture});
require('./consolidation.cjs')({core,test,assert,vm});
console.log(JSON.stringify({passed,scope:'JavaScript real + DOM simulado; navegador e backend não executados'}));
