/** Encaminhamento restrito para o endpoint financeiro persistente de teste. */
export async function onRequest({request,env}){
 const headers={'content-type':'application/json; charset=utf-8','cache-control':'private, no-store','x-content-type-options':'nosniff'},error=(status,message)=>new Response(JSON.stringify({error:message}),{status,headers});
 if(['main','master'].includes(env.CF_PAGES_BRANCH)||env.GS_ENVIRONMENT!=='preview'||!env.GS_FINANCE_BACKEND_URL||!env.GS_FINANCE_PROXY_TOKEN)return error(503,'Financeiro persistente de teste não configurado.');
 const url=new URL(request.url),origin=request.headers.get('origin'),allowed=(env.GS_PREVIEW_ORIGINS||'').split(',').map(x=>x.trim());if(!allowed.includes(url.origin)||origin&&origin!==url.origin)return error(403,'Origem não autorizada.');
 const gets=['bootstrap','statement','history','document','email-config','payment-email-list','attention-list','entry-detail','regularization-list','mail-document-list','email-list','archive-list','email-alert-list'],posts=['email-alert-resolve','document-check','regularization-decision','receipt-decision','mail-document-classify','email-save','email-test','archive-review','archive-backup','archive-confirm','archive-prepare','invoice-upload','invoice-edit','invoice-decision','receipt-upload','receipt-associate','receipt-read','invoice-read','entry-create','entry-edit','entry-approve','payment-create','payment-state','email-config','email-run','payment-email-retry','attention-read','attention-ack'],action=url.searchParams.get('action')||'bootstrap';if(!(request.method==='GET'&&gets.includes(action)||request.method==='POST'&&posts.includes(action)))return error(405,'Ação ou método não permitido.');if(request.method==='POST'&&(!origin||request.headers.get('content-type')?.split(';')[0]!=='application/json'))return error(403,'Pedido inválido.');
 let backend;try{backend=new URL(env.GS_FINANCE_BACKEND_URL);if(backend.protocol!=='https:'||backend.pathname!=='/'||backend.username||backend.password||backend.search||backend.hash)throw Error()}catch{return error(503,'Configuração de backend inválida.')}
 let body;if(request.method==='POST'){if(Number(request.headers.get('content-length'))>4250000)return error(413,'Pedido demasiado grande.');body=await request.text();if(new TextEncoder().encode(body).length>4250000)return error(413,'Pedido demasiado grande.');try{JSON.parse(body)}catch{return error(400,'JSON inválido.')}}
 const target=new URL('/api/v4-finance',backend);for(const key of ['action','id','kind','employeeId','start','end'])if(url.searchParams.has(key))target.searchParams.set(key,url.searchParams.get(key));
 try{const r=await fetch(target,{method:request.method,body,redirect:'error',signal:AbortSignal.timeout(25000),headers:{'content-type':'application/json','authorization':'Bearer '+env.GS_FINANCE_PROXY_TOKEN,'x-gs-origin':url.origin,cookie:request.headers.get('cookie')||''}});const type=r.headers.get('content-type')||'';if(!type.includes('application/json')&&!(action==='document'&&r.ok&&['application/pdf','image/png','image/jpeg'].some(x=>type.startsWith(x))))return error(502,'Resposta inválida do serviço.');const out=new Headers(headers);out.set('content-type',type);const actor=r.headers.get('x-gs-finance-actor');if(actor)out.set('x-gs-finance-actor',actor);if(action==='document')out.set('content-disposition',r.headers.get('content-disposition')||'attachment');return new Response(r.body,{status:r.status,headers:out})}catch{return error(502,'Serviço financeiro indisponível. Nenhuma operação confirmada.')}
}
