'use strict';
const A=require('../attention-core-v4'),P=require('../access-policy-core-v4'),C=require('../finance-core-v4');
const json=v=>typeof v==='string'?JSON.parse(v||'{}'):v||{};
async function list(s,actor){if(!actor?.active||!P.ROLES.includes(P.norm(actor.role)))throw C.error('Sem autorização para notificações.');
 const role=P.norm(actor.role),saved=(await s.query("select value from app_settings where key='role_action_permissions'"))[0],matrix=json(saved?.value),can=key=>{if(['financeManage','hrManage','leaveApprove','performanceManage'].includes(key)&&!['CEO','ADMINISTRAÇÃO'].includes(role))return false;if(actor.permissions?.[key]!==undefined)return actor.permissions[key]===true||actor.permissions[key]===1;return matrix[role]?.[key]!==undefined?matrix[role][key]===true:P.defaults(role).includes(key)};
 const people=await s.people(),clinics=await s.query('select id from clinics where active=true'),allowed=new Set(clinics.filter(c=>role==='CEO'||role==='CALL CENTER'||actor.clinics.includes(String(c.id))).map(c=>String(c.id))),employee=id=>id===actor.id||can('hrManage')&&(role==='CEO'||people.find(p=>p.id===id)?.clinics.some(c=>allowed.has(String(c))));
 const state={currentUser:actor.id,users:people,attentionRead:{[actor.id]:Object.fromEntries((await s.query('select * from finance_attention_read where user_id=$1',[actor.id])).map(x=>[x.event_id,{readAt:x.read_at,resolvedAt:x.resolved_at}]))},financeV2:{invoices:[],payslips:[],entries:[]},leave:[],employeeDocuments:{}};
 if(C.read(actor)){const f=await s.bootstrap(actor);state.financeV2=f;if(C.manager(actor))state.paymentMailIssues=(await s.query("select id,user_id,status,created_at from finance_payment_mail where status in ('Failed','Uncertain','Sending')")).map(x=>({id:x.id,employeeId:String(x.user_id),status:x.status,createdAt:x.created_at}));const mail=await s.query("select m.payment_id,m.user_id,m.created_at from finance_payment_mail m join current_account_entries p on p.id=m.payment_id where m.user_id=$1 and p.status='Pago'",[actor.id]);state.paymentNotifications=mail.map(x=>({id:String(x.payment_id),employeeId:String(x.user_id),createdAt:x.created_at,status:'Pago'}))}
 if(can('waiting'))state.requests=(await s.query('select id,clinic_id,stage,updated_at from requests')).filter(x=>allowed.has(String(x.clinic_id))).map(x=>({id:String(x.id),clinicId:x.clinic_id,stage:x.stage,updatedAt:x.updated_at}));
 if(can('hrManage'))state.candidates=(await s.query('select id,clinic_id,stage,updated_at from candidates')).filter(x=>!x.clinic_id||allowed.has(String(x.clinic_id))).map(x=>({id:String(x.id),clinicId:x.clinic_id,stage:x.stage,updatedAt:x.updated_at}));
 if(can('personal')||can('hrManage')){const docs=await s.query('select id,employee_id,filename,status,valid_until from documents');for(const x of docs){const p=people.find(p=>p.employeeId===String(x.employee_id));if(p&&employee(p.id)){(state.employeeDocuments[p.id]||=[]).push({id:String(x.id),name:x.filename,status:x.status,validUntil:x.valid_until})}}}
 if(can('clock'))state.timeOccurrences=(await s.query("select t.id,e.user_id,t.status,t.occurred_at from time_entries t join employees e on e.id=t.employee_id where t.status='Pendente'")).filter(x=>employee(String(x.user_id))).map(x=>({id:String(x.id),userId:String(x.user_id),status:x.status,at:x.occurred_at}));
 return A.collect(state,{active:actor.active,can,employee,clinic:(id,key)=>allowed.has(id)&&can(key)});
}
async function mark(s,actor,input,resolve=false){const item=(await list(s,actor)).find(x=>x.id===input.id);if(!item)throw C.error('Notificação indisponível ou sem autorização.');if(resolve&&item.mode!=='ack')throw C.error('Este processo exige uma decisão no módulo correspondente.');const time=new Date().toISOString();await s.query('insert into finance_attention_read(user_id,event_id,read_at,resolved_at) values($1,$2,$3,$4) on conflict(user_id,event_id) do update set read_at=excluded.read_at,resolved_at=coalesce(excluded.resolved_at,finance_attention_read.resolved_at)',[actor.id,item.id,time,resolve?time:null]);return{readAt:time,resolved:resolve}}
module.exports={list,mark};
