const { put }=require('@vercel/blob');
const { neon }=require('@neondatabase/serverless');
module.exports=async function(req,res){
 if(req.method!=='POST')return res.status(405).json({ok:false,code:'METHOD_NOT_ALLOWED'});
 if(!process.env.DATABASE_URL)return res.status(503).json({ok:false,code:'DATABASE_NOT_CONFIGURED'});
 const base=process.env.DATABASE_NEON_AUTH_BASE_URL,cookie=req.headers.cookie||'';if(!base||!cookie)return res.status(401).json({ok:false,code:'AUTH_REQUIRED'});
 const sr=await fetch(base.replace(/\/$/,'')+'/get-session',{headers:{cookie,accept:'application/json'}});if(!sr.ok)return res.status(401).json({ok:false,code:'AUTH_REQUIRED'});const session=await sr.json();if(!session?.user?.id)return res.status(401).json({ok:false,code:'AUTH_REQUIRED'});
 const sql=neon(process.env.DATABASE_URL);const u=await sql.query("select id,role,active from users where auth_subject=$1",[String(session.user.id)]);const me=u[0];if(!me?.active)return res.status(403).json({ok:false,code:'FORBIDDEN'});
 const employeeId=String(req.headers['x-employee-id']||'').trim()||null,candidateId=String(req.headers['x-candidate-id']||'').trim()||null; if((employeeId||candidateId)&&!['Administração','CEO'].includes(me.role))return res.status(403).json({ok:false,code:'FORBIDDEN'}); const kind=String(req.headers['x-document-kind']||'Documento').slice(0,80),description=decodeURIComponent(String(req.headers['x-document-description']||'')).trim().slice(0,300),receiptNo=decodeURIComponent(String(req.headers['x-receipt-number']||'')).trim().slice(0,80),receiptValue=Number(req.headers['x-receipt-value']||0),receiptDate=String(req.headers['x-receipt-date']||'').slice(0,10),startsAt=String(req.headers['x-starts-at']||'').slice(0,10)||null,validUntil=String(req.headers['x-valid-until']||'').slice(0,10)||null,name=decodeURIComponent(String(req.headers['x-file-name']||'documento.bin')).replace(/[^a-zA-Z0-9._ -]/g,'_'),mime=String(req.headers['content-type']||'application/octet-stream');
 if(!description)return res.status(400).json({ok:false,code:'DESCRIPTION_REQUIRED'});if(kind==='Recibo'&&(!receiptNo||!receiptDate||!(receiptValue>=0)))return res.status(400).json({ok:false,code:'RECEIPT_METADATA_REQUIRED'});const allowed=['application/pdf','image/jpeg','image/png','image/webp'];if(!allowed.includes(mime))return res.status(415).json({ok:false,code:'FILE_TYPE_NOT_ALLOWED'});
 const chunks=[];let size=0;for await(const chunk of req){size+=chunk.length;if(size>10*1024*1024)return res.status(413).json({ok:false,code:'FILE_TOO_LARGE'});chunks.push(chunk)}if(!size)return res.status(400).json({ok:false,code:'EMPTY_FILE'});
 const path='rh/'+me.id+'/'+Date.now()+'-'+name;const blob=await put(path,Buffer.concat(chunks),{access:'private',addRandomSuffix:true,contentType:mime,storeId:'store_GYyF5IpPjWna8kdj'});
 const rows=await sql.query("insert into documents(employee_id,candidate_id,kind,filename,storage_key,mime_type,starts_at,valid_until,status,data) values($8,$9,$1,$2,$3,$4,$5,$6,case when $6::date is not null and $6::date<current_date then 'Caducado' when $6::date is not null and $6::date<=current_date+interval '30 days' then 'A caducar' else 'Regularizado' end,$7::jsonb) returning id,kind,filename,mime_type,status,received_at",[kind,name,blob.pathname,mime,startsAt,validUntil,JSON.stringify({ownerUserId:me.id,private:true,description,receiptNo:kind==='Recibo'?receiptNo:null,receiptValue:kind==='Recibo'?receiptValue:null,receiptDate:kind==='Recibo'?receiptDate:null}),employeeId,candidateId]);await sql.query("insert into audit_log(actor_id,module,action,entity_type,entity_id,detail) values($1,'Documentos','UPLOAD_PRIVADO','document',$2,$3::jsonb)",[me.id,String(rows[0].id),JSON.stringify({kind,name,size,description,receiptNo:kind==='Recibo'?receiptNo:null,receiptValue:kind==='Recibo'?receiptValue:null,receiptDate:kind==='Recibo'?receiptDate:null})]);return res.status(201).json({ok:true,item:rows[0]});
};
