const { neon }=require('@neondatabase/serverless');
const schema=[
"create extension if not exists pgcrypto",
"create table if not exists clinics(id text primary key,name text not null,city text,domain text,active boolean not null default true,created_at timestamptz not null default now(),updated_at timestamptz not null default now())",
"create table if not exists users(id uuid primary key default gen_random_uuid(),auth_subject text unique,email text unique not null,name text not null,role text not null check(role in ('Call Center','Médico/a','Técnico/a','Administrativa','Administração','CEO')),active boolean not null default true,created_at timestamptz not null default now(),updated_at timestamptz not null default now())",
"create table if not exists user_clinics(user_id uuid references users(id) on delete cascade,clinic_id text references clinics(id) on delete cascade,primary key(user_id,clinic_id))",
"create table if not exists specialties(id uuid primary key default gen_random_uuid(),name text unique not null,active boolean not null default true)",
"create table if not exists clinic_specialties(clinic_id text references clinics(id) on delete cascade,specialty_id uuid references specialties(id) on delete cascade,primary key(clinic_id,specialty_id))",
"create table if not exists employees(id uuid primary key default gen_random_uuid(),user_id uuid references users(id),name text not null,status text not null default 'Ativo',role text,archived_at timestamptz,data jsonb not null default '{}'::jsonb,created_at timestamptz not null default now(),updated_at timestamptz not null default now())",
"create table if not exists candidates(id uuid primary key default gen_random_uuid(),email text,name text,phone text,clinic_id text references clinics(id),desired_role text,stage text not null default 'Novo',source text not null default 'Manual',source_message_id text unique,owner_id uuid references users(id),next_action_at timestamptz,data jsonb not null default '{}'::jsonb,created_at timestamptz not null default now(),updated_at timestamptz not null default now())",
"create table if not exists requests(id uuid primary key default gen_random_uuid(),clinic_id text references clinics(id),specialty_id uuid references specialties(id),patient_ref text,stage text not null default 'Pedido de Consulta',doctor_id uuid references users(id),data jsonb not null default '{}'::jsonb,created_at timestamptz not null default now(),updated_at timestamptz not null default now())",
"create table if not exists time_entries(id uuid primary key default gen_random_uuid(),employee_id uuid references employees(id),clinic_id text references clinics(id),kind text not null,occurred_at timestamptz not null,gps jsonb,status text not null default 'Aceite',data jsonb not null default '{}'::jsonb,created_at timestamptz not null default now())",
"create table if not exists documents(id uuid primary key default gen_random_uuid(),employee_id uuid references employees(id) on delete cascade,candidate_id uuid references candidates(id) on delete cascade,kind text not null,filename text not null,storage_key text not null,mime_type text,starts_at date,valid_until date,received_at timestamptz not null default now(),retention_until date,status text not null default 'Recebido',data jsonb not null default '{}'::jsonb)",
"create table if not exists email_ingest(id uuid primary key default gen_random_uuid(),provider text not null,message_id text unique not null,sender text,subject text,received_at timestamptz,status text not null default 'Pendente',candidate_id uuid references candidates(id),error text,created_at timestamptz not null default now())",
"create table if not exists document_backup_jobs(id uuid primary key default gen_random_uuid(),document_id uuid references documents(id) on delete cascade,destination text not null,status text not null default 'Pendente',attempts integer not null default 0,last_attempt_at timestamptz,delivered_at timestamptz,error text,created_at timestamptz not null default now())",
"create table if not exists technician_sales(id uuid primary key default gen_random_uuid(),clinic_id text references clinics(id),technician_id uuid references users(id),sale_date date not null,lasers integer not null default 0,others integer not null default 0,bonus_value numeric(12,2) not null default 0,data jsonb not null default '{}'::jsonb,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(clinic_id,technician_id,sale_date))",
"create table if not exists audit_log(id bigserial primary key,actor_id uuid references users(id),module text not null,action text not null,entity_type text,entity_id text,detail jsonb not null default '{}'::jsonb,created_at timestamptz not null default now())"
];
async function ensure(sql){for(const q of schema)await sql.query(q)}
async function actor(req,sql){const sub=req.headers['x-neon-auth-sub'];if(!sub)return null;const r=await sql.query("select u.id,u.email,u.name,u.role,u.active,coalesce(array_agg(uc.clinic_id) filter(where uc.clinic_id is not null),array[]::text[]) clinics from users u left join user_clinics uc on uc.user_id=u.id where u.auth_subject=$1 group by u.id",[sub]);return r[0]&&r[0].active?r[0]:null}
const adminRoles=new Set(['Administração','CEO']);
module.exports=async function handler(req,res){res.setHeader('Cache-Control','no-store');if(!process.env.DATABASE_URL)return res.status(503).json({ok:false,code:'DATABASE_NOT_CONFIGURED'});try{const sql=neon(process.env.DATABASE_URL);const me=await actor(req,sql);const write=req.method!=='GET'&&req.method!=='HEAD';if(write&&!me)return res.status(401).json({ok:false,code:'AUTH_REQUIRED'});if(req.method==='GET'&&req.query&&req.query.health==='1'){if(process.env.VERCEL_ENV==='preview')await ensure(sql);await sql.query("insert into clinics(id,name,city,domain) values ('abranfir','Abranfir','Abrantes','abranfir.gruposaude.pt'),('loures','Grupo Saúde — Loures','Loures','loures.gruposaude.pt'),('lagoa','Clínica Particular de Lagoa','Lagoa','lagoa.gruposaude.pt'),('medisobral','MediSobral','Sobral de Monte Agraço','medisobral.gruposaude.pt'),('algarfisio','AlgarFisio','Portimão','algarfisio.gruposaude.pt') on conflict(id) do nothing");const r=await sql.query("select current_database() db, now() server_time, (select count(*) from information_schema.tables where table_schema='public')::int tables");return res.status(200).json({ok:true,backend:'v4',database:'connected',db:r[0].db,tables:r[0].tables,serverTime:r[0].server_time})}if(req.method==='GET'&&req.query&&req.query.resource==='clinics'){const rows=await sql.query("select id,name,city,domain,active from clinics order by name");return res.status(200).json({ok:true,items:rows})}if(req.method==='POST'&&req.query&&req.query.resource==='clinics'){if(!adminRoles.has(me.role))return res.status(403).json({ok:false,code:'FORBIDDEN'});const b=req.body||{};if(!b.id||!b.name)return res.status(400).json({ok:false,code:'INVALID_CLINIC'});const rows=await sql.query('insert into clinics(id,name,city,domain,active) values ($1,$2,$3,$4,$5) on conflict(id) do update set name=excluded.name,city=excluded.city,domain=excluded.domain,active=excluded.active,updated_at=now() returning id,name,city,domain,active',[b.id,b.name,b.city||null,b.domain||null,b.active!==false]);return res.status(200).json({ok:true,item:rows[0]})}if(req.method==='GET'&&req.query&&req.query.resource==='users'){const rows=await sql.query("select u.id,u.email,u.name,u.role,u.active,coalesce(json_agg(uc.clinic_id) filter(where uc.clinic_id is not null),'[]') clinics from users u left join user_clinics uc on uc.user_id=u.id group by u.id order by u.name");return res.status(200).json({ok:true,items:rows})}
if(req.method==='POST'&&req.query&&req.query.resource==='users'){if(!adminRoles.has(me.role))return res.status(403).json({ok:false,code:'FORBIDDEN'});const b=req.body||{},roles=['Call Center','Médico/a','Técnico/a','Administrativa','Administração','CEO'];if(!b.email||!b.name||!roles.includes(b.role))return res.status(400).json({ok:false,code:'INVALID_USER'});const rows=await sql.query("insert into users(email,name,role,active,auth_subject) values($1,$2,$3,$4,$5) on conflict(email) do update set name=excluded.name,role=excluded.role,active=excluded.active,auth_subject=coalesce(excluded.auth_subject,users.auth_subject),updated_at=now() returning id,email,name,role,active",[String(b.email).toLowerCase(),b.name,b.role,b.active!==false,b.authSubject||null]);const id=rows[0].id;await sql.query("delete from user_clinics where user_id=$1",[id]);for(const cid of (b.clinics||[]))await sql.query("insert into user_clinics(user_id,clinic_id) values($1,$2) on conflict do nothing",[id,cid]);await sql.query("insert into audit_log(module,action,entity_type,entity_id,detail) values('Utilizadores','UPSERT','user',$1,$2::jsonb)",[String(id),JSON.stringify({email:b.email,role:b.role,clinics:b.clinics||[]})]);return res.status(200).json({ok:true,item:{...rows[0],clinics:b.clinics||[]}})}
if(req.method==='POST'&&req.query&&req.query.resource==='technician-sales'){if(!['Administrativa','Administração','CEO'].includes(me.role))return res.status(403).json({ok:false,code:'FORBIDDEN'});const b=req.body||{};if(!b.clinicId||!b.technicianId||!b.saleDate)return res.status(400).json({ok:false,code:'INVALID_SALE'});if(me.role==='Administrativa'&&!me.clinics.includes(b.clinicId))return res.status(403).json({ok:false,code:'WRONG_CLINIC'});const r=await sql.query("insert into technician_sales(clinic_id,technician_id,sale_date,lasers,others,bonus_value,data) values($1,$2,$3,$4,$5,$6,$7::jsonb) on conflict(clinic_id,technician_id,sale_date) do update set lasers=excluded.lasers,others=excluded.others,bonus_value=excluded.bonus_value,data=excluded.data,updated_at=now() returning *",[b.clinicId,b.technicianId,b.saleDate,Number(b.lasers)||0,Number(b.others)||0,Number(b.bonusValue)||0,JSON.stringify(b.data||{})]);await sql.query("insert into audit_log(actor_id,module,action,entity_type,entity_id,detail) values($1,'Fecho Clínica','VENDAS_TECNICO','technician_sale',$2,$3::jsonb)",[me.id,String(r[0].id),JSON.stringify(r[0])]);return res.status(200).json({ok:true,item:r[0]})}
if(req.method==='GET'&&req.query&&req.query.resource==='technician-sales'){if(!me)return res.status(401).json({ok:false,code:'AUTH_REQUIRED'});let rows;if(me.role==='Técnico/a')rows=await sql.query("select * from technician_sales where technician_id=$1 order by sale_date desc",[me.id]);else if(adminRoles.has(me.role))rows=await sql.query("select ts.*,u.name technician_name from technician_sales ts join users u on u.id=ts.technician_id order by sale_date desc");else rows=await sql.query("select ts.*,u.name technician_name from technician_sales ts join users u on u.id=ts.technician_id where ts.clinic_id=any($1::text[]) order by sale_date desc",[me.clinics]);return res.status(200).json({ok:true,items:rows})}
if(req.method==='GET'&&req.query&&req.query.resource==='me'){if(!me)return res.status(401).json({ok:false,code:'AUTH_REQUIRED'});return res.status(200).json({ok:true,user:me})}if(req.method==='GET'&&req.query&&req.query.resource==='permissions'){const roles=await sql.query("select role,count(*)::int users from users where active=true group by role order by role");return res.status(200).json({ok:true,roles})}return res.status(404).json({ok:false,code:'NOT_FOUND'})}catch(e){return res.status(500).json({ok:false,code:'DATABASE_ERROR',message:e.message})}}
